import json
import re
import os

# Complete vocabulary database for French-English-Bangla mappings
GLOBAL_VOCAB = {
    # Names & Proper Nouns
    "tariq": {"lemma": "Tariq", "en": "Tariq (first name)", "bn": "তারিক (নাম)", "pos": "noun"},
    "kabir": {"lemma": "Kabir", "en": "Kabir (first name)", "bn": "কবীর (নাম)", "pos": "noun"},
    "rahim": {"lemma": "Rahim", "en": "Rahim (first name)", "bn": "রহিম (নাম)", "pos": "noun"},
    "fahim": {"lemma": "Fahim", "en": "Fahim (first name)", "bn": "ফাহিম (নাম)", "pos": "noun"},
    "samir": {"lemma": "Samir", "en": "Samir (first name)", "bn": "সমীর (নাম)", "pos": "noun"},
    "pierre": {"lemma": "Pierre", "en": "Pierre (French first name)", "bn": "পিয়ের (ফরাসি নাম)", "pos": "noun"},
    "laurent": {"lemma": "Laurent", "en": "Laurent (surname/name)", "bn": "লরেন্ট (নাম)", "pos": "noun"},
    "paris": {"lemma": "Paris", "en": "Paris", "bn": "প্যারিস", "pos": "noun"},
    "france": {"lemma": "France", "en": "France", "bn": "ফ্রান্স", "pos": "noun"},
    "châtelet": {"lemma": "Châtelet", "en": "Châtelet (major metro station in Paris)", "bn": "শাতলে (প্যারিসের প্রধান মেট্রো স্টেশন)", "pos": "noun"},
    "porte": {"lemma": "porte", "en": "door / gate", "bn": "দরজা / গেট", "pos": "noun"},
    "clignancourt": {"lemma": "Clignancourt", "en": "Clignancourt (place in Paris)", "bn": "ক্লিনিয়াঁকুর (প্যারিসের একটি স্থান)", "pos": "noun"},

    # Articles & Determiners
    "le": {"lemma": "le", "en": "the (masculine)", "bn": "টি / টা (পুংলিঙ্গ)", "pos": "article"},
    "la": {"lemma": "le", "en": "the (feminine)", "bn": "টি / টা (স্ত্রীলিঙ্গ)", "pos": "article"},
    "les": {"lemma": "le", "en": "the (plural)", "bn": "গুলি / গুলো", "pos": "article"},
    "l": {"lemma": "le", "en": "the (before vowel)", "bn": "টি / টা", "pos": "article"},
    "un": {"lemma": "un", "en": "a / an (masculine)", "bn": "একটি", "pos": "article"},
    "une": {"lemma": "un", "en": "a / an (feminine)", "bn": "একটি", "pos": "article"},
    "des": {"lemma": "un", "en": "some / of the (plural)", "bn": "কিছু / গুলির", "pos": "article"},
    "du": {"lemma": "de + le", "en": "of the / some (masculine)", "bn": "এর / কিছু", "pos": "article"},
    "de": {"lemma": "de", "en": "of / from", "bn": "এর / থেকে", "pos": "preposition"},
    "d": {"lemma": "de", "en": "of / from (before vowel)", "bn": "এর / থেকে", "pos": "preposition"},
    "au": {"lemma": "à + le", "en": "at the / to the (masculine)", "bn": "তে / দিকে", "pos": "preposition"},
    "aux": {"lemma": "à + les", "en": "at the / to the (plural)", "bn": "তে / গুলির প্রতি", "pos": "preposition"},
    "à": {"lemma": "à", "en": "to / at", "bn": "তে / প্রতি", "pos": "preposition"},

    # Pronouns
    "je": {"lemma": "je", "en": "I", "bn": "আমি", "pos": "pronoun"},
    "j": {"lemma": "je", "en": "I (before vowel)", "bn": "আমি", "pos": "pronoun"},
    "tu": {"lemma": "tu", "en": "you (informal)", "bn": "তুমি", "pos": "pronoun"},
    "il": {"lemma": "il", "en": "he / it", "bn": "সে (পুরুষ)", "pos": "pronoun"},
    "elle": {"lemma": "elle", "en": "she / it", "bn": "সে (মহিলা)", "pos": "pronoun"},
    "on": {"lemma": "on", "en": "one / we", "bn": "আমরা / মানুষ", "pos": "pronoun"},
    "nous": {"lemma": "nous", "en": "we / us", "bn": "আমরা / আমাদের", "pos": "pronoun"},
    "vous": {"lemma": "vous", "en": "you (formal/plural)", "bn": "আপনি / আপনারা", "pos": "pronoun"},
    "ils": {"lemma": "il", "en": "they (masculine)", "bn": "তারা", "pos": "pronoun"},
    "elles": {"lemma": "elle", "en": "they (feminine)", "bn": "তারা (মহিলা)", "pos": "pronoun"},
    "me": {"lemma": "me", "en": "me / myself", "bn": "আমাকে / নিজেকে", "pos": "pronoun"},
    "m": {"lemma": "me", "en": "me (before vowel)", "bn": "আমাকে", "pos": "pronoun"},
    "te": {"lemma": "te", "en": "you (object)", "bn": "তোমাকে", "pos": "pronoun"},
    "t": {"lemma": "te", "en": "you (before vowel)", "bn": "তোমাকে", "pos": "pronoun"},
    "se": {"lemma": "se", "en": "himself / herself / themselves", "bn": "নিজেকে / নিজেরা", "pos": "pronoun"},
    "s": {"lemma": "se", "en": "himself / herself (before vowel)", "bn": "নিজেকে", "pos": "pronoun"},
    "moi": {"lemma": "moi", "en": "me", "bn": "আমি / আমাকে", "pos": "pronoun"},
    "toi": {"lemma": "toi", "en": "you (stressed)", "bn": "তুমি / তোমাকে", "pos": "pronoun"},
    "lui": {"lemma": "lui", "en": "to him / to her / him", "bn": "তাকে", "pos": "pronoun"},
    "leur": {"lemma": "leur", "en": "to them / their", "bn": "তাদের / তাদের কাছে", "pos": "pronoun"},
    "y": {"lemma": "y", "en": "there / to it", "bn": "সেখানে / এতে", "pos": "pronoun"},
    "en": {"lemma": "en", "en": "in / of it / by", "bn": "মধ্যে / এটার / দিয়ে", "pos": "preposition"},
    "qui": {"lemma": "qui", "en": "who / which (subject)", "bn": "যে / কে", "pos": "pronoun"},
    "que": {"lemma": "que", "en": "that / which / what (object)", "bn": "যে / কী", "pos": "pronoun"},
    "qu": {"lemma": "que", "en": "that / what (before vowel)", "bn": "যে / কী", "pos": "pronoun"},
    "ce": {"lemma": "ce", "en": "this / that", "bn": "এই / এটা", "pos": "pronoun"},
    "c": {"lemma": "ce", "en": "it / this (before est)", "bn": "এটা", "pos": "pronoun"},
    "cet": {"lemma": "ce", "en": "this (before vowel masculine)", "bn": "এই", "pos": "adjective"},
    "cette": {"lemma": "ce", "en": "this (feminine)", "bn": "এই (স্ত্রীলিঙ্গ)", "pos": "adjective"},
    "ces": {"lemma": "ce", "en": "these / those", "bn": "এইগুলি", "pos": "adjective"},
    "cela": {"lemma": "cela", "en": "that / this", "bn": "এটা / ওটা", "pos": "pronoun"},
    "mon": {"lemma": "son", "en": "my (masculine)", "bn": "আমার", "pos": "pronoun"},
    "ma": {"lemma": "son", "en": "my (feminine)", "bn": "আমার", "pos": "pronoun"},
    "mes": {"lemma": "son", "en": "my (plural)", "bn": "আমার (বহুবচন)", "pos": "pronoun"},
    "ton": {"lemma": "son", "en": "your (masculine)", "bn": "তোমার", "pos": "pronoun"},
    "ta": {"lemma": "son", "en": "your (feminine)", "bn": "তোমার", "pos": "pronoun"},
    "tes": {"lemma": "son", "en": "your (plural)", "bn": "তোমার (বহুবচন)", "pos": "pronoun"},
    "son": {"lemma": "son", "en": "his / her / its (masculine)", "bn": "তার", "pos": "pronoun"},
    "sa": {"lemma": "son", "en": "his / her / its (feminine)", "bn": "তার", "pos": "pronoun"},
    "ses": {"lemma": "son", "en": "his / her / its (plural)", "bn": "তার (বহুবচন)", "pos": "pronoun"},
    "notre": {"lemma": "notre", "en": "our", "bn": "আমাদের", "pos": "pronoun"},
    "nos": {"lemma": "notre", "en": "our (plural)", "bn": "আমাদের", "pos": "pronoun"},
    "votre": {"lemma": "votre", "en": "your (formal)", "bn": "আপনার", "pos": "pronoun"},
    "vos": {"lemma": "votre", "en": "your (formal plural)", "bn": "আপনার (বহুবচন)", "pos": "pronoun"},
    "leurs": {"lemma": "leur", "en": "their (plural)", "bn": "তাদের", "pos": "pronoun"},
    "tout": {"lemma": "tout", "en": "all / everything", "bn": "সব / সবকিছু", "pos": "adjective"},
    "tous": {"lemma": "tout", "en": "all (plural masculine)", "bn": "সবাই / সব", "pos": "adjective"},
    "toute": {"lemma": "tout", "en": "all (feminine singular)", "bn": "সমস্ত / পুরো", "pos": "adjective"},
    "toutes": {"lemma": "tout", "en": "all (feminine plural)", "bn": "সবগুলি", "pos": "adjective"},
    "chaque": {"lemma": "chaque", "en": "each / every", "bn": "প্রতিটি", "pos": "adjective"},
    "chacun": {"lemma": "chacun", "en": "each one", "bn": "প্রত্যেকে", "pos": "pronoun"},

    # Conjunctions & Prepositions
    "et": {"lemma": "et", "en": "and", "bn": "এবং", "pos": "conjunction"},
    "ou": {"lemma": "ou", "en": "or", "bn": "অথবা", "pos": "conjunction"},
    "où": {"lemma": "où", "en": "where", "bn": "কোথায় / যেখানে", "pos": "adverb"},
    "mais": {"lemma": "mais", "en": "but", "bn": "কিন্তু", "pos": "conjunction"},
    "donc": {"lemma": "donc", "en": "so / therefore", "bn": "তাই / সুতরাং", "pos": "conjunction"},
    "or": {"lemma": "or", "en": "now / yet", "bn": "তবে", "pos": "conjunction"},
    "ni": {"lemma": "ni", "en": "neither / nor", "bn": "না", "pos": "conjunction"},
    "car": {"lemma": "car", "en": "because / for", "bn": "কারণ", "pos": "conjunction"},
    "parce": {"lemma": "parce que", "en": "because (part 1)", "bn": "কারণ", "pos": "conjunction"},
    "parceque": {"lemma": "parce que", "en": "because", "bn": "কারণ", "pos": "conjunction"},
    "si": {"lemma": "si", "en": "if / yes (contradicting)", "bn": "যদি / হ্যাঁ", "pos": "conjunction"},
    "quand": {"lemma": "quand", "en": "when", "bn": "যখন / কখন", "pos": "conjunction"},
    "comme": {"lemma": "comme", "en": "as / like", "bn": "যেমন / মতো", "pos": "conjunction"},
    "dans": {"lemma": "dans", "en": "in / inside", "bn": "মধ্যে", "pos": "preposition"},
    "sur": {"lemma": "sur", "en": "on / upon", "bn": "উপরে", "pos": "preposition"},
    "sous": {"lemma": "sous", "en": "under / beneath", "bn": "নিচে", "pos": "preposition"},
    "avec": {"lemma": "avec", "en": "with", "bn": "সাথে", "pos": "preposition"},
    "sans": {"lemma": "sans", "en": "without", "bn": "ছাড়া / ব্যতীত", "pos": "preposition"},
    "pour": {"lemma": "pour", "en": "for / in order to", "bn": "জন্য / উদ্দেশ্যে", "pos": "preposition"},
    "chez": {"lemma": "chez", "en": "at the place of", "bn": "কাছে / বাসায় / চেম্বারে", "pos": "preposition"},
    "par": {"lemma": "par", "en": "by / through / per", "bn": "দ্বারা / মাধ্যমে / প্রতি", "pos": "preposition"},
    "vers": {"lemma": "vers", "en": "towards / around", "bn": "দিকে / প্রায়", "pos": "preposition"},
    "devant": {"lemma": "devant", "en": "in front of", "bn": "সামনে", "pos": "preposition"},
    "derrière": {"lemma": "derrière", "en": "behind", "bn": "পেছনে", "pos": "preposition"},
    "entre": {"lemma": "entre", "en": "between", "bn": "মাঝে / মধ্যে", "pos": "preposition"},
    "pendant": {"lemma": "pendant", "en": "during", "bn": "সময়ে / চলাকালীন", "pos": "preposition"},
    "depuis": {"lemma": "depuis", "en": "since / for (duration)", "bn": "থেকে / ধরে", "pos": "preposition"},
    "avant": {"lemma": "avant", "en": "before", "bn": "পূর্বে / আগে", "pos": "preposition"},
    "après": {"lemma": "après", "en": "after", "bn": "পরে", "pos": "preposition"},
    "près": {"lemma": "près", "en": "near", "bn": "কাছে / নিকটে", "pos": "preposition"},

    # Adverbs & Negation
    "ne": {"lemma": "ne", "en": "not (first part of negation)", "bn": "না", "pos": "adverb"},
    "n": {"lemma": "ne", "en": "not (before vowel)", "bn": "না", "pos": "adverb"},
    "pas": {"lemma": "pas", "en": "not", "bn": "না", "pos": "adverb"},
    "plus": {"lemma": "plus", "en": "more / no more", "bn": "আরও / আর না", "pos": "adverb"},
    "jamais": {"lemma": "jamais", "en": "never", "bn": "কখনো না", "pos": "adverb"},
    "rien": {"lemma": "rien", "en": "nothing", "bn": "কিছু না", "pos": "pronoun"},
    "très": {"lemma": "très", "en": "very", "bn": "খুব", "pos": "adverb"},
    "trop": {"lemma": "trop", "en": "too / excessively", "bn": "অতিরিক্ত / বেশি", "pos": "adverb"},
    "bien": {"lemma": "bien", "en": "well / good", "bn": "ভালো / বেশ", "pos": "adverb"},
    "mal": {"lemma": "mal", "en": "badly / pain", "bn": "খারাপভাবে / ব্যথা", "pos": "adverb"},
    "aussi": {"lemma": "aussi", "en": "also / too", "bn": "ও / আরও", "pos": "adverb"},
    "toujours": {"lemma": "toujours", "en": "always / still", "bn": "সবসময় / এখনও", "pos": "adverb"},
    "souvent": {"lemma": "souvent", "en": "often", "bn": "প্রায়ই", "pos": "adverb"},
    "parfois": {"lemma": "parfois", "en": "sometimes", "bn": "মাঝে মাঝে", "pos": "adverb"},
    "maintenant": {"lemma": "maintenant", "en": "now", "bn": "এখন", "pos": "adverb"},
    "aujourdhui": {"lemma": "aujourd'hui", "en": "today", "bn": "আজ", "pos": "adverb"},
    "hier": {"lemma": "hier", "en": "yesterday", "bn": "গতকাল", "pos": "adverb"},
    "demain": {"lemma": "demain", "en": "tomorrow", "bn": "আগামীকাল", "pos": "adverb"},
    "ici": {"lemma": "ici", "en": "here", "bn": "এখানে", "pos": "adverb"},
    "là": {"lemma": "là", "en": "there", "bn": "সেখানে", "pos": "adverb"},
    "beaucoup": {"lemma": "beaucoup", "en": "a lot / much", "bn": "অনেক / প্রচুর", "pos": "adverb"},
    "peu": {"lemma": "peu", "en": "little / few", "bn": "কম / অল্প", "pos": "adverb"},
    "unpeu": {"lemma": "un peu", "en": "a little bit", "bn": "একটু / কিছুটা", "pos": "adverb"},
    "assez": {"lemma": "assez", "en": "enough / quite", "bn": "যথেষ্ট / বেশ", "pos": "adverb"},
    "encore": {"lemma": "encore", "en": "again / still", "bn": "আবার / এখনও", "pos": "adverb"},
    "déjà": {"lemma": "déjà", "en": "already", "bn": "ইতিমধ্যে / আগেই", "pos": "adverb"},
    "alors": {"lemma": "alors", "en": "then / so", "bn": "তখন / তাহলে", "pos": "adverb"},
    "ensuite": {"lemma": "ensuite", "en": "then / next", "bn": "তারপর", "pos": "adverb"},
    "puis": {"lemma": "puis", "en": "then", "bn": "তারপর", "pos": "adverb"},
    "enfin": {"lemma": "enfin", "en": "finally / at last", "bn": "অবশেষে", "pos": "adverb"},
    "surtout": {"lemma": "surtout", "en": "especially / above all", "bn": "বিশেষ করে", "pos": "adverb"},
    "vite": {"lemma": "vite", "en": "fast / quickly", "bn": "দ্রুত", "pos": "adverb"},
    "lentement": {"lemma": "lentement", "en": "slowly", "bn": "ধীরে ধীরে", "pos": "adverb"},
    "calmement": {"lemma": "calmement", "en": "calmly", "bn": "শান্তভাবে", "pos": "adverb"},
    "poliment": {"lemma": "poliment", "en": "politely", "bn": "ভদ্রভাবে", "pos": "adverb"},
    "gentiment": {"lemma": "gentiment", "en": "kindly / nicely", "bn": "দয়ার সাথে", "pos": "adverb"},
    "directement": {"lemma": "directement", "en": "directly", "bn": "সরাসরি", "pos": "adverb"},
    "parfaitement": {"lemma": "parfaitement", "en": "perfectly", "bn": "নিখুঁতভাবে", "pos": "adverb"},
    "exactement": {"lemma": "exactement", "en": "exactly", "bn": "ঠিক / নিখুঁতভাবে", "pos": "adverb"},
    "attentivement": {"lemma": "attentivement", "en": "attentively / carefully", "bn": "মনোযোগ সহকারে", "pos": "adverb"},
    "chaleureusement": {"lemma": "chaleureusement", "en": "warmly", "bn": "উষ্ণভাবে / আন্তরিকভাবে", "pos": "adverb"},
    "confortablement": {"lemma": "confortablement", "en": "comfortably", "bn": "আরামদায়কভাবে", "pos": "adverb"},
    "facilement": {"lemma": "facilement", "en": "easily", "bn": "সহজে", "pos": "adverb"},
    "régulièrement": {"lemma": "régulièrement", "en": "regularly", "bn": "নিয়মিতভাবে", "pos": "adverb"},
    "seulement": {"lemma": "seulement", "en": "only", "bn": "শুধুমাত্র", "pos": "adverb"},
    "juste": {"lemma": "juste", "en": "just / right", "bn": "ঠিক / শুধুমাত্র", "pos": "adverb"},
    "ensemble": {"lemma": "ensemble", "en": "together", "bn": "একসাথে", "pos": "adverb"},
    "oui": {"lemma": "oui", "en": "yes", "bn": "হ্যাঁ", "pos": "expression"},
    "non": {"lemma": "non", "en": "no", "bn": "না", "pos": "expression"},
    "bonjour": {"lemma": "bonjour", "en": "hello / good morning", "bn": "শুভ সকাল / হ্যালো", "pos": "expression"},
    "bonsoir": {"lemma": "bonsoir", "en": "good evening", "bn": "শুভ সন্ধ্যা", "pos": "expression"},
    "merci": {"lemma": "merci", "en": "thank you", "bn": "ধন্যবাদ", "pos": "expression"},
    "plaît": {"lemma": "plaire", "en": "pleases", "bn": "পছন্দ হওয়া / খুশি করা", "pos": "verb"},
    "silvousplaît": {"lemma": "s'il vous plaît", "en": "please (formal)", "bn": "দয়া করে", "pos": "expression"},
    "enchanté": {"lemma": "enchanté", "en": "pleased to meet you", "bn": "আপনার সাথে পরিচিত হয়ে আনন্দিত", "pos": "expression"},
    "bienvenue": {"lemma": "bienvenue", "en": "welcome", "bn": "স্বাগতম", "pos": "expression"},
    "excusezmoi": {"lemma": "excuser", "en": "excuse me (formal)", "bn": "আমাকে মাফ করবেন", "pos": "expression"},
    "au-revoir": {"lemma": "au revoir", "en": "goodbye", "bn": "বিদায়", "pos": "expression"},
    "aurevoir": {"lemma": "au revoir", "en": "goodbye", "bn": "বিদায়", "pos": "expression"},

    # Numbers
    "zéro": {"lemma": "zéro", "en": "zero", "bn": "শূন্য", "pos": "noun"},
    "un": {"lemma": "un", "en": "one", "bn": "এক", "pos": "adjective"},
    "deux": {"lemma": "deux", "en": "two", "bn": "দুই", "pos": "adjective"},
    "trois": {"lemma": "trois", "en": "three", "bn": "তিন", "pos": "adjective"},
    "quatre": {"lemma": "quatre", "en": "four", "bn": "চার", "pos": "adjective"},
    "cinq": {"lemma": "cinq", "en": "five", "bn": "পাঁচ", "pos": "adjective"},
    "six": {"lemma": "six", "en": "six", "bn": "ছয়", "pos": "adjective"},
    "sept": {"lemma": "sept", "en": "seven", "bn": "সাত", "pos": "adjective"},
    "huit": {"lemma": "huit", "en": "eight", "bn": "আট", "pos": "adjective"},
    "neuf": {"lemma": "neuf", "en": "nine / new", "bn": "নয় / নতুন", "pos": "adjective"},
    "dix": {"lemma": "dix", "en": "ten", "bn": "দশ", "pos": "adjective"},
    "quinze": {"lemma": "quinze", "en": "fifteen", "bn": "পনেরো", "pos": "adjective"},
    "vingt": {"lemma": "vingt", "en": "twenty", "bn": "কুড়ি / বিশ", "pos": "adjective"},
    "trente": {"lemma": "trente", "en": "thirty", "bn": "ত্রিশ", "pos": "adjective"},
    "quarante": {"lemma": "quarante", "en": "forty", "bn": "চল্লিশ", "pos": "adjective"},
    "cinquante": {"lemma": "cinquante", "en": "fifty", "bn": "পঞ্চাশ", "pos": "adjective"},
    "soixante": {"lemma": "soixante", "en": "sixty", "bn": "ষাট", "pos": "adjective"},
    "cent": {"lemma": "cent", "en": "hundred", "bn": "একশত", "pos": "adjective"},
    "mille": {"lemma": "mille", "en": "thousand", "bn": "হাজার", "pos": "adjective"},
    "premier": {"lemma": "premier", "en": "first (masculine)", "bn": "প্রথম", "pos": "adjective"},
    "première": {"lemma": "premier", "en": "first (feminine)", "bn": "প্রথম", "pos": "adjective"},
    "deuxième": {"lemma": "deuxième", "en": "second", "bn": "দ্বিতীয়", "pos": "adjective"},
    "troisième": {"lemma": "troisième", "en": "third", "bn": "তৃতীয়", "pos": "adjective"},
    "quatrième": {"lemma": "quatrième", "en": "fourth", "bn": "চতুর্থ", "pos": "adjective"},
}

print(f"Loaded {len(GLOBAL_VOCAB)} base vocabulary items.")
