#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import os
import json

# Comprehensive lexicon for French -> (Lemma, EN, BN, POS)
LEXICON = {
    # Names
    "tariq": ("Tariq", "Tariq (first name)", "তারিক (নাম)", "noun"),
    "kabir": ("Kabir", "Kabir (first name)", "কবীর (নাম)", "noun"),
    "rahim": ("Rahim", "Rahim (first name)", "রহিম (নাম)", "noun"),
    "fahim": ("Fahim", "Fahim (first name)", "ফাহিম (নাম)", "noun"),
    "samir": ("Samir", "Samir (first name)", "সমীর (নাম)", "noun"),
    "pierre": ("Pierre", "Pierre (first name)", "পিয়ের (ফরাসি নাম)", "noun"),
    "laurent": ("Laurent", "Laurent (surname/name)", "লরেন্ট (নাম)", "noun"),
    "paris": ("Paris", "Paris (city)", "প্যারিস", "noun"),
    "france": ("France", "France (country)", "ফ্রান্স", "noun"),
    "châtelet": ("Châtelet", "Châtelet (metro station)", "শাতলে (মেট্রো স্টেশন)", "noun"),
    "clignancourt": ("Clignancourt", "Clignancourt (place in Paris)", "ক্লিনিয়াঁকুর", "noun"),

    # Grammatical Words & Pronouns
    "le": ("le", "the (masculine)", "টি / টা", "article"),
    "la": ("le", "the (feminine)", "টি / টা", "article"),
    "les": ("le", "the (plural)", "গুলি / গুলো", "article"),
    "l": ("le", "the (elision)", "টি / টা", "article"),
    "un": ("un", "a / an (masculine)", "একটি", "article"),
    "une": ("un", "a / an (feminine)", "একটি", "article"),
    "des": ("un", "some / of the", "কিছু / গুলির", "article"),
    "du": ("de + le", "of the / some", "এর / কিছু", "article"),
    "de": ("de", "of / from", "এর / থেকে", "preposition"),
    "d": ("de", "of / from (elision)", "এর / থেকে", "preposition"),
    "à": ("à", "to / at", "তে / প্রতি", "preposition"),
    "au": ("à + le", "at the / to the", "তে / দিকে", "preposition"),
    "aux": ("à + les", "to the / at the (plural)", "তে / প্রতি", "preposition"),
    "en": ("en", "in / by / while", "মধ্যে / দিয়ে", "preposition"),
    "dans": ("dans", "in / inside", "মধ্যে", "preposition"),
    "sur": ("sur", "on / upon", "উপরে", "preposition"),
    "sous": ("sous", "under", "নিচে", "preposition"),
    "avec": ("avec", "with", "সাথে", "preposition"),
    "sans": ("sans", "without", "ছাড়া", "preposition"),
    "pour": ("pour", "for / in order to", "জন্য / উদ্দেশ্যে", "preposition"),
    "chez": ("chez", "at the place of", "কাছে / বাসায় / চেম্বারে", "preposition"),
    "par": ("par", "by / per", "দ্বারা / মাধ্যমে", "preposition"),
    "vers": ("vers", "towards / around", "দিকে / কাছাকাছি", "preposition"),
    "devant": ("devant", "in front of", "সামনে", "preposition"),
    "derrière": ("derrière", "behind", "পেছনে", "preposition"),
    "entre": ("entre", "between", "মাঝে", "preposition"),
    "pendant": ("pendant", "during", "সময়ে / চলাকালীন", "preposition"),
    "depuis": ("depuis", "since / for", "থেকে / ধরে", "preposition"),
    "avant": ("avant", "before", "আগে / পূর্বে", "preposition"),
    "après": ("après", "after", "পরে", "preposition"),
    "près": ("près", "near / close", "কাছে", "preposition"),
    "contre": ("contre", "against", "বিরুদ্ধে / বিপরীতে", "preposition"),

    # Pronouns
    "je": ("je", "I", "আমি", "pronoun"),
    "j": ("je", "I (elision)", "আমি", "pronoun"),
    "tu": ("tu", "you (informal)", "তুমি", "pronoun"),
    "il": ("il", "he / it", "সে", "pronoun"),
    "elle": ("elle", "she / it", "সে (মহিলা)", "pronoun"),
    "on": ("on", "we / one", "আমরা / মানুষ", "pronoun"),
    "nous": ("nous", "we / us", "আমরা / আমাদের", "pronoun"),
    "vous": ("vous", "you (formal/plural)", "আপনি / আপনারা", "pronoun"),
    "ils": ("il", "they (masculine)", "তারা", "pronoun"),
    "elles": ("elle", "they (feminine)", "তারা (মহিলা)", "pronoun"),
    "me": ("me", "me / myself", "আমাকে / নিজেকে", "pronoun"),
    "m": ("me", "me (elision)", "আমাকে", "pronoun"),
    "te": ("te", "you (object)", "তোমাকে", "pronoun"),
    "t": ("te", "you (elision)", "তোমাকে", "pronoun"),
    "se": ("se", "himself / herself / themselves", "নিজেকে / নিজেরা", "pronoun"),
    "s": ("se", "himself / herself (elision)", "নিজেকে", "pronoun"),
    "moi": ("moi", "me (stressed)", "আমাকে / আমি", "pronoun"),
    "toi": ("toi", "you (stressed)", "তোমাকে / তুমি", "pronoun"),
    "lui": ("lui", "to him / to her", "তাকে", "pronoun"),
    "leur": ("leur", "to them / their", "তাদের", "pronoun"),
    "leurs": ("leur", "their (plural)", "তাদের (বহুবচন)", "pronoun"),
    "y": ("y", "there / to it", "সেখানে / এতে", "pronoun"),
    "qui": ("qui", "who / which", "যে / কে", "pronoun"),
    "que": ("que", "that / which / what", "যা / যে / কী", "pronoun"),
    "qu": ("que", "that / what (elision)", "যা / কী", "pronoun"),
    "ce": ("ce", "this / that / it", "এই / এটা", "pronoun"),
    "c": ("ce", "it / this (before est)", "এটা", "pronoun"),
    "cet": ("ce", "this (masculine vowel)", "এই", "adjective"),
    "cette": ("ce", "this (feminine)", "এই", "adjective"),
    "ces": ("ce", "these / those", "এইগুলি", "adjective"),
    "cela": ("cela", "that / this", "এটা / ওটা", "pronoun"),
    "ça": ("cela", "that / it (informal)", "এটা", "pronoun"),
    "mon": ("son", "my (masculine)", "আমার", "pronoun"),
    "ma": ("son", "my (feminine)", "আমার", "pronoun"),
    "mes": ("son", "my (plural)", "আমার (বহুবচন)", "pronoun"),
    "ton": ("son", "your (masculine)", "তোমার", "pronoun"),
    "ta": ("son", "your (feminine)", "তোমার", "pronoun"),
    "tes": ("son", "your (plural)", "তোমার (বহুবচন)", "pronoun"),
    "son": ("son", "his / her / its (masculine)", "তার", "pronoun"),
    "sa": ("son", "his / her / its (feminine)", "তার", "pronoun"),
    "ses": ("son", "his / her / its (plural)", "তার (বহুবচন)", "pronoun"),
    "notre": ("notre", "our", "আমাদের", "pronoun"),
    "nos": ("notre", "our (plural)", "আমাদের (বহুবচন)", "pronoun"),
    "votre": ("votre", "your (formal)", "আপনার", "pronoun"),
    "vos": ("votre", "your (formal plural)", "আপনার (বহুবচন)", "pronoun"),
    "tout": ("tout", "all / everything", "সব / পুরো", "adjective"),
    "tous": ("tout", "all (masculine plural)", "সবাই / সব", "adjective"),
    "toute": ("tout", "all (feminine singular)", "সমস্ত / পুরো", "adjective"),
    "toutes": ("tout", "all (feminine plural)", "সবগুলি", "adjective"),
    "chaque": ("chaque", "each / every", "প্রতিটি", "adjective"),
    "chacun": ("chacun", "each one", "প্রত্যেকে", "pronoun"),

    # Conjunctions
    "et": ("et", "and", "এবং", "conjunction"),
    "ou": ("ou", "or", "অথবা", "conjunction"),
    "où": ("où", "where", "কোথায় / যেখানে", "adverb"),
    "mais": ("mais", "but", "কিন্তু", "conjunction"),
    "donc": ("donc", "so / therefore", "তাই / সুতরাং", "conjunction"),
    "car": ("car", "because / for", "কারণ", "conjunction"),
    "si": ("si", "if / so", "যদি", "conjunction"),
    "quand": ("quand", "when", "যখন / কখন", "conjunction"),
    "comme": ("comme", "as / like", "যেমন / মতো", "conjunction"),
    "alors": ("alors", "then / so", "তখন / তাহলে", "conjunction"),
    "parce": ("parce que", "because (part)", "কারণ", "conjunction"),
    "parceque": ("parce que", "because", "কারণ", "conjunction"),

    # Adverbs & Particles
    "ne": ("ne", "not (part 1)", "না", "adverb"),
    "n": ("ne", "not (elision)", "না", "adverb"),
    "pas": ("pas", "not", "না", "adverb"),
    "plus": ("plus", "more / no more", "আরও / আর না", "adverb"),
    "jamais": ("jamais", "never", "কখনো না", "adverb"),
    "rien": ("rien", "nothing", "কিছু না", "pronoun"),
    "très": ("très", "very", "খুব", "adverb"),
    "trop": ("trop", "too / too much", "অতিরিক্ত / বেশি", "adverb"),
    "bien": ("bien", "well / good", "ভালো / বেশ", "adverb"),
    "mal": ("mal", "badly / ill", "খারাপভাবে / ব্যথা", "adverb"),
    "aussi": ("aussi", "also / too", "ও / আরও", "adverb"),
    "toujours": ("toujours", "always / still", "সবসময় / এখনও", "adverb"),
    "souvent": ("souvent", "often", "প্রায়ই", "adverb"),
    "parfois": ("parfois", "sometimes", "মাঝে মাঝে", "adverb"),
    "maintenant": ("maintenant", "now", "এখন", "adverb"),
    "aujourdhui": ("aujourd'hui", "today", "আজ", "adverb"),
    "hier": ("hier", "yesterday", "গতকাল", "adverb"),
    "demain": ("demain", "tomorrow", "আগামীকাল", "adverb"),
    "ici": ("ici", "here", "এখানে", "adverb"),
    "là": ("là", "there", "সেখানে", "adverb"),
    "beaucoup": ("beaucoup", "a lot / much", "অনেক / প্রচুর", "adverb"),
    "peu": ("peu", "little / few", "অল্প / কম", "adverb"),
    "unpeu": ("un peu", "a little bit", "একটু", "adverb"),
    "assez": ("assez", "enough / quite", "যথেষ্ট / বেশ", "adverb"),
    "encore": ("encore", "again / still", "আবার / এখনও", "adverb"),
    "déjà": ("déjà", "already", "ইতিমধ্যে", "adverb"),
    "ensuite": ("ensuite", "then / next", "তারপর", "adverb"),
    "puis": ("puis", "then", "তারপর", "adverb"),
    "enfin": ("enfin", "finally", "অবশেষে", "adverb"),
    "surtout": ("surtout", "especially", "বিশেষ করে", "adverb"),
    "vite": ("vite", "fast / quickly", "দ্রুত", "adverb"),
    "lentement": ("lentement", "slowly", "ধীরে", "adverb"),
    "calmement": ("calmement", "calmly", "শান্তভাবে", "adverb"),
    "poliment": ("poliment", "politely", "ভদ্রভাবে", "adverb"),
    "gentiment": ("gentiment", "kindly", "দয়ার সাথে", "adverb"),
    "directement": ("directement", "directly", "সরাসরি", "adverb"),
    "parfaitement": ("parfaitement", "perfectly", "নিখুঁতভাবে", "adverb"),
    "exactement": ("exactement", "exactly", "ঠিক / নিখুঁতভাবে", "adverb"),
    "attentivement": ("attentivement", "carefully / attentively", "মনোযোগ সহকারে", "adverb"),
    "chaleureusement": ("chaleureusement", "warmly", "উষ্ণভাবে", "adverb"),
    "confortablement": ("confortablement", "comfortably", "আরামদায়কভাবে", "adverb"),
    "facilement": ("facilement", "easily", "সহজে", "adverb"),
    "régulièrement": ("régulièrement", "regularly", "নিয়মিতভাবে", "adverb"),
    "seulement": ("seulement", "only", "শুধুমাত্র", "adverb"),
    "juste": ("juste", "just / right", "ঠিক / মাত্র", "adverb"),
    "ensemble": ("ensemble", "together", "একসাথে", "adverb"),

    # Numbers
    "zéro": ("zéro", "zero", "শূন্য", "noun"),
    "un": ("un", "one", "এক", "adjective"),
    "deux": ("deux", "two", "দুই", "adjective"),
    "trois": ("trois", "three", "তিন", "adjective"),
    "quatre": ("quatre", "four", "চার", "adjective"),
    "cinq": ("cinq", "five", "পাঁচ", "adjective"),
    "six": ("six", "six", "ছয়", "adjective"),
    "sept": ("sept", "seven", "সাত", "adjective"),
    "huit": ("huit", "eight", "আট", "adjective"),
    "neuf": ("neuf", "nine / new", "নয় / নতুন", "adjective"),
    "dix": ("dix", "ten", "দশ", "adjective"),
    "quinze": ("quinze", "fifteen", "পনেরো", "adjective"),
    "vingt": ("vingt", "twenty", "বিশ / কুড়ি", "adjective"),
    "trente": ("trente", "thirty", "ত্রিশ", "adjective"),
    "quarante": ("quarante", "forty", "চল্লিশ", "adjective"),
    "cinquante": ("cinquante", "fifty", "পঞ্চাশ", "adjective"),
    "soixante": ("soixante", "sixty", "ষাট", "adjective"),
    "cent": ("cent", "hundred", "একশত", "adjective"),
    "mille": ("mille", "thousand", "হাজার", "adjective"),
    "premier": ("premier", "first (masculine)", "প্রথম", "adjective"),
    "première": ("premier", "first (feminine)", "প্রথম", "adjective"),
    "deuxième": ("deuxième", "second", "দ্বিতীয়", "adjective"),
    "troisième": ("troisième", "third", "তৃতীয়", "adjective"),
    "quatrième": ("quatrième", "fourth", "চতুর্থ", "adjective"),
}

print("Base lexicon size:", len(LEXICON))
