# -*- coding: utf-8 -*-
"""
Lexicon Part 3: M through R
"""

LEXICON_M_R = {
    # M
    "machine": {"lemma": "machine", "en": "machine", "bn": "যন্ত্র / মেশিন", "pos": "noun"},
    "main": {"lemma": "main", "en": "hand", "bn": "হাত", "pos": "noun"},
    "mains": {"lemma": "main", "en": "hands", "bn": "হাতগুলো", "pos": "noun"},
    "mairie": {"lemma": "mairie", "en": "town hall / mayor's office", "bn": "পৌরসভা / টাউন হল", "pos": "noun"},
    "maintien": {"lemma": "maintien", "en": "maintenance / retention", "bn": "বজায় রাখা", "pos": "noun"},
    "maintenance": {"lemma": "maintenance", "en": "maintenance (IT)", "bn": "রক্ষণাবেক্ষণ", "pos": "noun"},
    "maison": {"lemma": "maison", "en": "house / home", "bn": "বাড়ি", "pos": "noun"},
    "manger": {"lemma": "manger", "en": "to eat", "bn": "খাওয়া", "pos": "verb"},
    "manuscrite": {"lemma": "manuscrit", "en": "handwritten", "bn": "হাতে লেখা", "pos": "adjective"},
    "mardi": {"lemma": "mardi", "en": "Tuesday", "bn": "মঙ্গলবার", "pos": "noun"},
    "marchande": {"lemma": "marchand", "en": "commercial (mall)", "bn": "বাণিজ্যিক", "pos": "adjective"},
    "marcher": {"lemma": "marcher", "en": "to walk / work", "bn": "হাঁটা / কাজ করা", "pos": "verb"},
    "marches": {"lemma": "marche", "en": "steps / stairs", "bn": "সিঁড়ির ধাপ", "pos": "noun"},
    "marché": {"lemma": "marché", "en": "market (job market)", "bn": "বাজার (চাকরির বাজার)", "pos": "noun"},
    "matériel": {"lemma": "matériel", "en": "hardware / equipment", "bn": "হার্ডওয়্যার / যন্ত্রপাতি", "pos": "noun"},
    "matérielles": {"lemma": "matériel", "en": "hardware (failures)", "bn": "হার্ডওয়্যার সংক্রান্ত", "pos": "adjective"},
    "matin": {"lemma": "matin", "en": "morning", "bn": "সকাল", "pos": "noun"},
    "matinée": {"lemma": "matinée", "en": "morning (duration)", "bn": "সকালবেলা", "pos": "noun"},
    "maximiser": {"lemma": "maximiser", "en": "to maximize", "bn": "সর্বোচ্চ করা", "pos": "verb"},
    "menu": {"lemma": "menu", "en": "menu", "bn": "খাবার তালিকা / মেনু", "pos": "noun"},
    "mer": {"lemma": "mer", "en": "sea", "bn": "সমুদ্র", "pos": "noun"},
    "message": {"lemma": "message", "en": "message", "bn": "বার্তা / মেসেজ", "pos": "noun"},
    "mettre": {"lemma": "mettre", "en": "to put / apply", "bn": "রাখা / প্রয়োগ করা", "pos": "verb"},
    "met": {"lemma": "mettre", "en": "puts", "bn": "রাখে", "pos": "verb"},
    "meuble": {"lemma": "meuble", "en": "piece of furniture", "bn": "আসবাবপত্র", "pos": "noun"},
    "meublé": {"lemma": "meublé", "en": "furnished (studio)", "bn": "আসবাবপত্র সজ্জিত", "pos": "adjective"},
    "meubles": {"lemma": "meuble", "en": "furniture", "bn": "আসবাবপত্র", "pos": "noun"},
    "midi": {"lemma": "midi", "en": "midday / noon", "bn": "দুপুর / মধ্যাহ্ন", "pos": "noun"},
    "minute": {"lemma": "minute", "en": "minute", "bn": "মিনিট", "pos": "noun"},
    "minutes": {"lemma": "minute", "en": "minutes", "bn": "মিনিট", "pos": "noun"},
    "mobile": {"lemma": "mobile", "en": "mobile (phone/network)", "bn": "মোবাইল", "pos": "adjective"},
    "mode": {"lemma": "mode", "en": "mode / fashion", "bn": "মোড / ধরন", "pos": "noun"},
    "moderne": {"lemma": "moderne", "en": "modern", "bn": "আধুনিক", "pos": "adjective"},
    "mois": {"lemma": "mois", "en": "month / months", "bn": "মাস", "pos": "noun"},
    "moment": {"lemma": "moment", "en": "moment / time", "bn": "মুহূর্ত / সময়", "pos": "noun"},
    "monnaie": {"lemma": "monnaie", "en": "change / currency", "bn": "ভাঙতি টাকা / মুদ্রা", "pos": "noun"},
    "monsieur": {"lemma": "monsieur", "en": "sir / gentleman", "bn": "জনাব / মহাশয়", "pos": "noun"},
    "monter": {"lemma": "monter", "en": "to assemble / go up", "bn": "জোড়া লাগানো / ওঠা", "pos": "verb"},
    "montre": {"lemma": "montrer", "en": "shows / watch", "bn": "দেখায় / হাতঘড়ি", "pos": "verb"},
    "montrer": {"lemma": "montrer", "en": "to show", "bn": "দেখানো", "pos": "verb"},
    "mot": {"lemma": "mot", "en": "word", "bn": "শব্দ", "pos": "noun"},
    "mots": {"lemma": "mot", "en": "words", "bn": "শব্দসমূহ", "pos": "noun"},
    "passe": {"lemma": "mot de passe", "en": "password / passes", "bn": "পাসওয়ার্ড / অতিক্রম করে", "pos": "noun"},
    "motivation": {"lemma": "motivation", "en": "motivation", "bn": "প্রেরণা / উৎসাহ", "pos": "noun"},
    "moyen": {"lemma": "moyen", "en": "means / method", "bn": "মাধ্যম / উপায়", "pos": "noun"},
    "musique": {"lemma": "musique", "en": "music", "bn": "সঙ্গীত / গান", "pos": "noun"},
    "mètre": {"lemma": "mètre", "en": "metre", "bn": "মিটার", "pos": "noun"},
    "mètres": {"lemma": "mètre", "en": "metres", "bn": "মিটার", "pos": "noun"},
    "médecin": {"lemma": "médecin", "en": "doctor / physician", "bn": "চিকিৎসক / ডাক্তার", "pos": "noun"},
    "médecine": {"lemma": "médecine", "en": "medicine (field)", "bn": "চিকিৎসাবিজ্ঞান", "pos": "noun"},
    "médicament": {"lemma": "médicament", "en": "medicine / drug", "bn": "ওষুধ", "pos": "noun"},
    "médicaments": {"lemma": "médicament", "en": "medicines", "bn": "ওষুধসমূহ", "pos": "noun"},
    "médical": {"lemma": "médical", "en": "medical", "bn": "চিকিৎসা সংক্রান্ত", "pos": "adjective"},
    "médicale": {"lemma": "médical", "en": "medical (feminine)", "bn": "চিকিৎসা সংক্রান্ত", "pos": "adjective"},
    "métier": {"lemma": "métier", "en": "profession / occupation", "bn": "পেশা / কাজ", "pos": "noun"},
    "métro": {"lemma": "métro", "en": "subway / underground train", "bn": "পাতালরেল / মেট্রো", "pos": "noun"},
    "métallique": {"lemma": "métallique", "en": "metallic / metal", "bn": "ধাতব", "pos": "adjective"},
    "métalliques": {"lemma": "métallique", "en": "metallic (plural)", "bn": "ধাতব", "pos": "adjective"},
    "métal": {"lemma": "métal", "en": "metal", "bn": "ধাতু", "pos": "noun"},

    # N
    "naissance": {"lemma": "naissance", "en": "birth", "bn": "জন্ম", "pos": "noun"},
    "nano-sim": {"lemma": "nano-SIM", "en": "nano-SIM card", "bn": "ন্যানো সিম", "pos": "noun"},
    "nanosim": {"lemma": "nano-SIM", "en": "nano-SIM card", "bn": "ন্যানো সিম", "pos": "noun"},
    "national": {"lemma": "national", "en": "national", "bn": "জাতীয়", "pos": "adjective"},
    "nationalités": {"lemma": "nationalité", "en": "nationalities", "bn": "জাতীয়তাসমূহ", "pos": "noun"},
    "natation": {"lemma": "natation", "en": "swimming", "bn": "সাঁতার", "pos": "noun"},
    "naturel": {"lemma": "naturel", "en": "natural", "bn": "প্রাকৃতিক / স্বাভাবিক", "pos": "adjective"},
    "naturelle": {"lemma": "naturel", "en": "natural (feminine)", "bn": "স্বাভাবিক", "pos": "adjective"},
    "nettoyer": {"lemma": "nettoyer", "en": "to clean", "bn": "পরিষ্কার করা", "pos": "verb"},
    "neuf": {"lemma": "neuf", "en": "brand new / nine", "bn": "নতুন / নয়", "pos": "adjective"},
    "neufs": {"lemma": "neuf", "en": "brand new (plural)", "bn": "একেবারে নতুন", "pos": "adjective"},
    "niveau": {"lemma": "niveau", "en": "level", "bn": "স্তর / লেভেল", "pos": "noun"},
    "nom": {"lemma": "nom", "en": "name / noun", "bn": "নাম", "pos": "noun"},
    "nombreux": {"lemma": "nombreux", "en": "numerous / many", "bn": "অনেক / প্রচুর", "pos": "adjective"},
    "normes": {"lemma": "norme", "en": "standards / norms", "bn": "মান / নিয়মাবলী", "pos": "noun"},
    "notes": {"lemma": "note", "en": "grades / transcripts / notes", "bn": "নম্বর / মার্কশিট", "pos": "noun"},
    "nouveau": {"lemma": "nouveau", "en": "new (masculine)", "bn": "নতুন", "pos": "adjective"},
    "nouvel": {"lemma": "nouveau", "en": "new (before vowel)", "bn": "নতুন", "pos": "adjective"},
    "nouvelle": {"lemma": "nouveau", "en": "new (feminine) / news", "bn": "নতুন", "pos": "adjective"},
    "nuit": {"lemma": "nuit", "en": "night", "bn": "রাত", "pos": "noun"},
    "numéro": {"lemma": "numéro", "en": "number / ticket number", "bn": "নম্বর", "pos": "noun"},
    "numérique": {"lemma": "numérique", "en": "digital", "bn": "ডিজিটাল", "pos": "adjective"},
    "numériques": {"lemma": "numérique", "en": "digital (services)", "bn": "ডিজিটাল", "pos": "adjective"},
    "n'hésitez": {"lemma": "hésiter", "en": "do not hesitate", "bn": "দ্বিধা করবেন না", "pos": "verb"},
    "hésitez": {"lemma": "hésiter", "en": "hesitate", "bn": "দ্বিধা করা", "pos": "verb"},

    # O
    "objet": {"lemma": "objet", "en": "object / purpose", "bn": "উদ্দেশ্য / বিষয়", "pos": "noun"},
    "obligatoire": {"lemma": "obligatoire", "en": "mandatory / compulsory", "bn": "বাধ্যতামূলক", "pos": "adjective"},
    "observe": {"lemma": "observer", "en": "observes / inspects", "bn": "পর্যবেক্ষণ করে", "pos": "verb"},
    "obtenir": {"lemma": "obtenir", "en": "to obtain / get", "bn": "পাওয়া / অর্জন করা", "pos": "verb"},
    "obtenu": {"lemma": "obtenir", "en": "obtained / completed", "bn": "অর্জন করেছে / পেয়েছে", "pos": "verb"},
    "odeur": {"lemma": "odeur", "en": "smell / aroma", "bn": "গন্ধ / সুবাস", "pos": "noun"},
    "officiel": {"lemma": "officiel", "en": "official", "bn": "সরকারি / দাপ্তরিক", "pos": "adjective"},
    "officielle": {"lemma": "officiel", "en": "official (feminine)", "bn": "দাপ্তরিক", "pos": "adjective"},
    "officiels": {"lemma": "officiel", "en": "official (plural)", "bn": "দাপ্তরিক / অফিসিয়াল", "pos": "adjective"},
    "officiellement": {"lemma": "officiellement", "en": "officially", "bn": "আনুষ্ঠানিকভাবে", "pos": "adverb"},
    "officine": {"lemma": "officine", "en": "dispensary / pharmacy premises", "bn": "ফার্মেসি দোকান / ডিসপেনসারি", "pos": "noun"},
    "offre": {"lemma": "offre", "en": "offer / job offer", "bn": "অফার / চাকরির সুযোগ", "pos": "noun"},
    "offres": {"lemma": "offre", "en": "offers / job listings", "bn": "চাকরির বিজ্ঞাপনসমূহ", "pos": "noun"},
    "opérateur": {"lemma": "opérateur", "en": "telecom operator", "bn": "টেলিকম অপারেটর", "pos": "noun"},
    "optique": {"lemma": "optique", "en": "optical (scanner)", "bn": "অপটিক্যাল / স্ক্যানার", "pos": "adjective"},
    "option": {"lemma": "option", "en": "option", "bn": "বিকল্প / অপশন", "pos": "noun"},
    "options": {"lemma": "option", "en": "options", "bn": "বিকল্পসমূহ", "pos": "noun"},
    "oral": {"lemma": "oral", "en": "oral / spoken", "bn": "মৌখিক", "pos": "adjective"},
    "oraux": {"lemma": "oral", "en": "oral (interviews plural)", "bn": "মৌখিক", "pos": "adjective"},
    "ordinateur": {"lemma": "ordinateur", "en": "computer", "bn": "কম্পিউটার", "pos": "noun"},
    "ordinateurs": {"lemma": "ordinateur", "en": "computers", "bn": "কম্পিউটারসমূহ", "pos": "noun"},
    "ordonnance": {"lemma": "ordonnance", "en": "prescription", "bn": "প্রেসক্রিপশন / ব্যবস্থাপত্র", "pos": "noun"},
    "ordre": {"lemma": "ordre", "en": "order / in order", "bn": "ক্রম / শৃঙ্খলা", "pos": "noun"},
    "organiser": {"lemma": "organiser", "en": "to arrange / organize", "bn": "আয়োজন করা / ব্যবস্থা করা", "pos": "verb"},
    "orienter": {"lemma": "orienter", "en": "to find one's way / navigate", "bn": "দিক ঠিক করা / পথ খোঁজা", "pos": "verb"},
    "original": {"lemma": "original", "en": "original", "bn": "আসল / মূল", "pos": "adjective"},
    "outil": {"lemma": "outil", "en": "tool", "bn": "টুলস / হাতিয়ার", "pos": "noun"},
    "ouvert": {"lemma": "ouvert", "en": "open", "bn": "খোলা", "pos": "adjective"},
    "ouverte": {"lemma": "ouvert", "en": "open (feminine)", "bn": "খোলা", "pos": "adjective"},
    "ouverture": {"lemma": "ouverture", "en": "opening (account)", "bn": "উদ্বোধন / খোলা", "pos": "noun"},
    "ouvrir": {"lemma": "ouvrir", "en": "to open", "bn": "খোলা", "pos": "verb"},
    "ouvre": {"lemma": "ouvrir", "en": "opens", "bn": "খোলে", "pos": "verb"},
    "ouvrent": {"lemma": "ouvrir", "en": "open (plural)", "bn": "খোলে", "pos": "verb"},
    "œufs": {"lemma": "œuf", "en": "eggs", "bn": "ডিম", "pos": "noun"},
    "oeufs": {"lemma": "œuf", "en": "eggs", "bn": "ডিম", "pos": "noun"},

    # P
    "paie": {"lemma": "payer", "en": "pays / pay slip", "bn": "অর্থ প্রদান করে / বেতন", "pos": "verb"},
    "panier": {"lemma": "panier", "en": "shopping basket", "bn": "কেনাকাটার ঝুড়ি", "pos": "noun"},
    "panique": {"lemma": "paniquer", "en": "panics", "bn": "আতঙ্কিত হয়", "pos": "verb"},
    "panne": {"lemma": "panne", "en": "breakdown / failure", "bn": "ত্রুটি / নষ্ট হওয়া", "pos": "noun"},
    "pannes": {"lemma": "panne", "en": "breakdowns / hardware failures", "bn": "হার্ডওয়্যার ত্রুটিসমূহ", "pos": "noun"},
    "panneau": {"lemma": "panneau", "en": "sign / board", "bn": "সাইনবোর্ড / নির্দেশক", "pos": "noun"},
    "panneaux": {"lemma": "panneau", "en": "signs / boards", "bn": "সাইনবোর্ডসমূহ", "pos": "noun"},
    "pantalon": {"lemma": "pantalon", "en": "trousers / pants", "bn": "প্যান্ট", "pos": "noun"},
    "paquet": {"lemma": "paquet", "en": "packet / package", "bn": "প্যাকেট", "pos": "noun"},
    "paracétamol": {"lemma": "paracétamol", "en": "paracetamol", "bn": "প্যারাসিটামল", "pos": "noun"},
    "parc": {"lemma": "parc", "en": "park / computer workstation pool", "bn": "পার্ক / আইটি সিস্টেম পুল", "pos": "noun"},
    "parcourir": {"lemma": "parcourir", "en": "to browse / review", "bn": "ঘুরে দেখা / পর্যালোচনা", "pos": "verb"},
    "parcours": {"lemma": "parcours", "en": "career path / background", "bn": "অভিজ্ঞতার পথ / ক্যারিয়ার", "pos": "noun"},
    "parfait": {"lemma": "parfait", "en": "perfect", "bn": "নিখুঁত / চমৎকার", "pos": "adjective"},
    "parfaite": {"lemma": "parfait", "en": "perfect (feminine)", "bn": "নিখুঁত", "pos": "adjective"},
    "parfumé": {"lemma": "parfumer", "en": "fragrant / scented", "bn": "সুগন্ধযুক্ত", "pos": "adjective"},
    "parler": {"lemma": "parler", "en": "to speak / talk", "bn": "কথা বলা", "pos": "verb"},
    "parlez": {"lemma": "parler", "en": "speak / tell (parlez-moi)", "bn": "বলুন", "pos": "verb"},
    "parlez-moi": {"lemma": "parler", "en": "tell me", "bn": "আমাকে বলুন", "pos": "verb"},
    "paroles": {"lemma": "parole", "en": "words / lyrics", "bn": "কথা / বাণী", "pos": "noun"},
    "partir": {"lemma": "partir", "en": "to leave / depart", "bn": "চলে যাওয়া / রওনা দেওয়া", "pos": "verb"},
    "parties": {"lemma": "partie", "en": "parts / common areas", "bn": "অংশসমূহ", "pos": "noun"},
    "pas": {"lemma": "pas", "en": "step / footsteps / not", "bn": "পদক্ষেপ / পায়ের আওয়াজ / না", "pos": "noun"},
    "passeport": {"lemma": "passeport", "en": "passport", "bn": "পাসপোর্ট", "pos": "noun"},
    "passer": {"lemma": "passer", "en": "to pass / spend time", "bn": "অতিক্রম করা / কাটানো", "pos": "verb"},
    "passe": {"lemma": "passer", "en": "passes / goes through", "bn": "যায় / অতিক্রম করে", "pos": "verb"},
    "passez": {"lemma": "passer", "en": "spend / have (passez une bonne journée)", "bn": "কাটান", "pos": "verb"},
    "passionnant": {"lemma": "passionnant", "en": "exciting / fascinating", "bn": "উত্তেজনাপূর্ণ / চিত্তাকর্ষক", "pos": "adjective"},
    "pastilles": {"lemma": "pastille", "en": "lozenges / throat sweets", "bn": "গলার লজেন্স / প্যাস্টিল", "pos": "noun"},
    "patience": {"lemma": "patience", "en": "patience", "bn": "ধৈর্য", "pos": "noun"},
    "patient": {"lemma": "patient", "en": "patient / customer", "bn": "ধৈর্যশীল / রোগী", "pos": "noun"},
    "patiemment": {"lemma": "patiemment", "en": "patiently", "bn": "ধৈর্য সহকারে", "pos": "adverb"},
    "payer": {"lemma": "payer", "en": "to pay", "bn": "টাকা দেওয়া / পরিশোধ করা", "pos": "verb"},
    "paiement": {"lemma": "paiement", "en": "payment", "bn": "অর্থ পরিশোধ / পেমেন্ট", "pos": "noun"},
    "paisible": {"lemma": "paisible", "en": "peaceful", "bn": "শান্তিপূর্ণ / নিরিবিলি", "pos": "adjective"},
    "percevoir": {"lemma": "percevoir", "en": "to receive / collect (salary)", "bn": "গ্রহণ করা (বেতন)", "pos": "verb"},
    "permis": {"lemma": "permis", "en": "permit / driving licence", "bn": "অনুমতিপত্র / ড্রাইভিং লাইসেন্স", "pos": "noun"},
    "personnel": {"lemma": "personnel", "en": "personal / staff", "bn": "ব্যক্তিগত / কর্মী", "pos": "adjective"},
    "personnalisé": {"lemma": "personnaliser", "en": "personalized / tailored", "bn": "ব্যক্তিমাফিক / নিজস্বকৃত", "pos": "adjective"},
    "personnalisée": {"lemma": "personnaliser", "en": "personalized (feminine)", "bn": "ব্যক্তিমাফিক", "pos": "adjective"},
    "peser": {"lemma": "peser", "en": "to weigh", "bn": "ওজন করা", "pos": "verb"},
    "pèse": {"lemma": "peser", "en": "weighs", "bn": "ওজন করে", "pos": "verb"},
    "petit": {"lemma": "petit", "en": "small / short", "bn": "ছোট", "pos": "adjective"},
    "petite": {"lemma": "petit", "en": "small (feminine)", "bn": "ছোট", "pos": "adjective"},
    "pharmacie": {"lemma": "pharmacie", "en": "pharmacy / chemist", "bn": "ফার্মেসি / ওষুধের দোকান", "pos": "noun"},
    "pharmacien": {"lemma": "pharmacien", "en": "pharmacist", "bn": "ফার্মাসিস্ট", "pos": "noun"},
    "pharmaciens": {"lemma": "pharmacien", "en": "pharmacists", "bn": "ফার্মাসিস্টগণ", "pos": "noun"},
    "pharmacienne": {"lemma": "pharmacien", "en": "pharmacist (female)", "bn": "ফার্মাসিস্ট (মহিলা)", "pos": "noun"},
    "photocopies": {"lemma": "photocopie", "en": "photocopies", "bn": "ফটোকপি", "pos": "noun"},
    "photos": {"lemma": "photo", "en": "photos", "bn": "ছবি", "pos": "noun"},
    "phrase": {"lemma": "phrase", "en": "sentence", "bn": "বাক্য", "pos": "noun"},
    "physique": {"lemma": "physique", "en": "physical (card)", "bn": "বাস্তব / দৃশ্যমান কার্ড", "pos": "adjective"},
    "pile": {"lemma": "pile", "en": "sharp / right on time", "bn": "কাটায় কাটায়", "pos": "adverb"},
    "plaques": {"lemma": "plaque", "en": "hobs / hotplates", "bn": "চুলা / কুকিং হব", "pos": "noun"},
    "plat": {"lemma": "plat", "en": "dish / main course", "bn": "খাবারের পদ / ডিশ", "pos": "noun"},
    "plats": {"lemma": "plat", "en": "dishes", "bn": "খাবারের পদসমূহ", "pos": "noun"},
    "plein": {"lemma": "plein", "en": "full", "bn": "পূর্ণ / ভরা", "pos": "adjective"},
    "pliée": {"lemma": "plier", "en": "folded", "bn": "ভাঁজ করা", "pos": "adjective"},
    "poche": {"lemma": "poche", "en": "pocket", "bn": "পকেট", "pos": "noun"},
    "point": {"lemma": "point", "en": "point / assessment (faire le point)", "bn": "পর্যালোচনা / বিন্দু", "pos": "noun"},
    "pointue": {"lemma": "pointu", "en": "advanced / sharp (training)", "bn": "উন্নত / বিশেষায়িত", "pos": "adjective"},
    "poignée": {"lemma": "poignée", "en": "handshake / handle", "bn": "করমর্দন / হাতল", "pos": "noun"},
    "politesse": {"lemma": "politesse", "en": "courtesy / politeness", "bn": "ভদ্রতা / শিষ্টাচার", "pos": "noun"},
    "pommes": {"lemma": "pomme", "en": "apples / potatoes (pommes de terre)", "bn": "আলু / আপেল", "pos": "noun"},
    "portail": {"lemma": "portail", "en": "web portal / gate", "bn": "ওয়েব পোর্টাল / গেট", "pos": "noun"},
    "portillon": {"lemma": "portillon", "en": "turnstile / subway barrier", "bn": "মেট্রো গেট / ব্যারিয়ার", "pos": "noun"},
    "posologie": {"lemma": "posologie", "en": "dosage / medicine instructions", "bn": "ওষুধ সেবনের নিয়ম ও মাত্রা", "pos": "noun"},
    "posément": {"lemma": "posément", "en": "composedly / calmly", "bn": "ধীরস্থিরভাবে", "pos": "adverb"},
    "poste": {"lemma": "poste", "en": "job position / workstation / mail", "bn": "পদ / ওয়ার্কস্টেশন / ডাক", "pos": "noun"},
    "postale": {"lemma": "postal", "en": "postal", "bn": "ডাক সংক্রান্ত", "pos": "adjective"},
    "poulet": {"lemma": "poulet", "en": "chicken", "bn": "মুরগির মাংস", "pos": "noun"},
    "poubelle": {"lemma": "poubelle", "en": "dustbin / trash can", "bn": "ময়লার পাত্র", "pos": "noun"},
    "poubelles": {"lemma": "poubelle", "en": "trash bins", "bn": "ময়লার পাত্রগুলো", "pos": "noun"},
    "pourboire": {"lemma": "pourboire", "en": "tip / gratuity", "bn": "বকশিশ / টিপস", "pos": "noun"},
    "poursuivre": {"lemma": "poursuivre", "en": "to pursue / continue", "bn": "অব্যাহত রাখা / চালিয়ে যাওয়া", "pos": "verb"},
    "pouvoir": {"lemma": "pouvoir", "en": "can / to be able to", "bn": "পারা", "pos": "verb"},
    "peux": {"lemma": "pouvoir", "en": "can (je)", "bn": "পারি", "pos": "verb"},
    "peut": {"lemma": "pouvoir", "en": "can (il/elle)", "bn": "পারে", "pos": "verb"},
    "pourrez": {"lemma": "pouvoir", "en": "will be able to (vous)", "bn": "পারবেন", "pos": "verb"},
    "praticien": {"lemma": "praticien", "en": "medical practitioner / doctor", "bn": "চিকিৎসক", "pos": "noun"},
    "pratique": {"lemma": "pratique", "en": "practical / practice", "bn": "বাস্তবমুখী / ব্যবহারিক", "pos": "adjective"},
    "pratiques": {"lemma": "pratique", "en": "practical (plural)", "bn": "ব্যবহারিক", "pos": "adjective"},
    "premier": {"lemma": "premier", "en": "first", "bn": "প্রথম", "pos": "adjective"},
    "première": {"lemma": "premier", "en": "first (feminine)", "bn": "প্রথম", "pos": "adjective"},
    "prendre": {"lemma": "prendre", "en": "to take", "bn": "নেওয়া", "pos": "verb"},
    "prend": {"lemma": "prendre", "en": "takes", "bn": "নেয়", "pos": "verb"},
    "prennent": {"lemma": "prendre", "en": "take (plural)", "bn": "নেয়", "pos": "verb"},
    "prenez": {"lemma": "prendre", "en": "take (imperative/formal)", "bn": "নিন / গ্রহণ করুন", "pos": "verb"},
    "pris": {"lemma": "prendre", "en": "taken / scheduled", "bn": "নিয়েছে / করেছে", "pos": "verb"},
    "pression": {"lemma": "pression", "en": "pressure (water)", "bn": "চাপ (পানির চাপ)", "pos": "noun"},
    "prescription": {"lemma": "prescription", "en": "medical prescription", "bn": "প্রেসক্রিপশন / নির্দেশপত্র", "pos": "noun"},
    "prescrit": {"lemma": "prescrire", "en": "prescribes", "bn": "প্রেসক্রিপশন দেয়", "pos": "verb"},
    "priorité": {"lemma": "priorité", "en": "priority", "bn": "অগ্রাধিকার", "pos": "noun"},
    "problème": {"lemma": "problème", "en": "problem / issue", "bn": "সমস্যা", "pos": "noun"},
    "problèmes": {"lemma": "problème", "en": "problems / issues", "bn": "সমস্যাসমূহ", "pos": "noun"},
    "prochain": {"lemma": "prochain", "en": "next", "bn": "পরবর্তী", "pos": "adjective"},
    "prochaine": {"lemma": "prochain", "en": "next (feminine)", "bn": "পরবর্তী", "pos": "adjective"},
    "prochainement": {"lemma": "prochainement", "en": "very soon", "bn": "খুব শীঘ্রই", "pos": "adverb"},
    "professionnel": {"lemma": "professionnel", "en": "professional", "bn": "পেশাদার", "pos": "adjective"},
    "professionnelle": {"lemma": "professionnel", "en": "professional (feminine)", "bn": "পেশাদার", "pos": "adjective"},
    "profil": {"lemma": "profil", "en": "profile / background", "bn": "প্রোফাইল / যোগ্যতা", "pos": "noun"},
    "projet": {"lemma": "projet", "en": "project / professional plan", "bn": "প্রকল্প / পরিকল্পনা", "pos": "noun"},
    "projets": {"lemma": "projet", "en": "projects", "bn": "প্রকল্পগুলো", "pos": "noun"},
    "promet": {"lemma": "promettre", "en": "promises", "bn": "প্রতিশ্রুতি দেয়", "pos": "verb"},
    "propose": {"lemma": "proposer", "en": "offers / suggests", "bn": "প্রস্তাব দেয় / প্রদান করে", "pos": "verb"},
    "proposé": {"lemma": "proposer", "en": "offered / proposed", "bn": "প্রস্তাবিত", "pos": "adjective"},
    "proposer": {"lemma": "proposer", "en": "to offer / propose", "bn": "প্রস্তাব দেওয়া", "pos": "verb"},
    "propre": {"lemma": "propre", "en": "clean / own", "bn": "পরিষ্কার / নিজস্ব", "pos": "adjective"},
    "propriétaire": {"lemma": "propriétaire", "en": "landlord / owner", "bn": "বাড়িওয়ালা / মালিক", "pos": "noun"},
    "propriétaires": {"lemma": "propriétaire", "en": "landlords / owners", "bn": "বাড়িওয়ালাগণ", "pos": "noun"},
    "provisoire": {"lemma": "provisoire", "en": "provisional / temporary", "bn": "সাময়িক / অস্থায়ী", "pos": "adjective"},
    "précipiter": {"lemma": "précipiter", "en": "to rush", "bn": "তাড়াহুড়ো করা", "pos": "verb"},
    "précipitation": {"lemma": "précipitation", "en": "haste / rushing", "bn": "তাড়াহুড়ো", "pos": "noun"},
    "précis": {"lemma": "précis", "en": "precise", "bn": "সুনির্দিষ্ট / সঠিক", "pos": "adjective"},
    "précise": {"lemma": "préciser", "en": "specifies / exact (feminine)", "bn": "স্পষ্ট করে বলে / সঠিক", "pos": "verb"},
    "préciser": {"lemma": "préciser", "en": "to clarify / specify", "bn": "স্পষ্ট করা", "pos": "verb"},
    "préparatrice": {"lemma": "préparateur", "en": "pharmacy technician / assistant", "bn": "ফার্মেসি সহকারী", "pos": "noun"},
    "préparatrices": {"lemma": "préparateur", "en": "pharmacy assistants", "bn": "ফার্মেসি সহকারীগণ", "pos": "noun"},
    "préparer": {"lemma": "préparer", "en": "to prepare", "bn": "প্রস্তুত করা", "pos": "verb"},
    "prépare": {"lemma": "préparer", "en": "prepares", "bn": "প্রস্তুত করে", "pos": "verb"},
    "préparé": {"lemma": "préparer", "en": "prepared", "bn": "প্রস্তুত করেছে", "pos": "verb"},
    "prépayée": {"lemma": "prépayé", "en": "prepaid", "bn": "প্রিপেইড", "pos": "adjective"},
    "prévient": {"lemma": "prévenir", "en": "notifies / informs", "bn": "জানায় / অবহিত করে", "pos": "verb"},
    "prévoit": {"lemma": "prévoir", "en": "plans / provides for", "bn": "পরিকল্পনা করে / রাখে", "pos": "verb"},
    "préalable": {"lemma": "préalable", "en": "preliminary / prior", "bn": "প্রাথমিক / পূর্ববর্তী", "pos": "adjective"},
    "précieux": {"lemma": "précieux", "en": "precious / valuable", "bn": "মূল্যবান", "pos": "adjective"},
    "prêt": {"lemma": "prêt", "en": "ready / loan", "bn": "প্রস্তুত / ঋণ", "pos": "adjective"},
    "prêter": {"lemma": "prêter", "en": "to lend / loan", "bn": "ধার দেওয়া", "pos": "verb"},
    "public": {"lemma": "public", "en": "public", "bn": "সরকারি / গণ", "pos": "adjective"},
    "publique": {"lemma": "public", "en": "public (feminine)", "bn": "সরকারি", "pos": "adjective"},
    "puce": {"lemma": "puce", "en": "SIM chip / microchip", "bn": "সিম চিপ", "pos": "noun"},
    "pâte": {"lemma": "pâte", "en": "pasta / dough", "bn": "পাস্তা", "pos": "noun"},
    "pâtes": {"lemma": "pâte", "en": "pasta", "bn": "পাস্তা", "pos": "noun"},

    # Q & R
    "quantité": {"lemma": "quantité", "en": "quantity / amount", "bn": "পরিমাণ", "pos": "noun"},
    "quartier": {"lemma": "quartier", "en": "neighbourhood / district", "bn": "মহল্লা / এলাকা", "pos": "noun"},
    "quatorze": {"lemma": "quatorze", "en": "fourteen", "bn": "চৌদ্দ", "pos": "adjective"},
    "quitter": {"lemma": "quitter", "en": "to leave", "bn": "ছেড়ে যাওয়া", "pos": "verb"},
    "quitte": {"lemma": "quitter", "en": "leaves / exits", "bn": "বের হয় / ছেড়ে যায়", "pos": "verb"},
    "quotidien": {"lemma": "quotidien", "en": "daily", "bn": "দৈনন্দিন", "pos": "adjective"},
    "radiateur": {"lemma": "radiateur", "en": "heating radiator", "bn": "রেডিয়েটর / হিটার", "pos": "noun"},
    "radiateurs": {"lemma": "radiateur", "en": "radiators", "bn": "হিটারগুলো", "pos": "noun"},
    "ramasser": {"lemma": "ramasser", "en": "to pick up / collect", "bn": "সংগ্রহ করা", "pos": "verb"},
    "ramassent": {"lemma": "ramasser", "en": "collect (garbage)", "bn": "সংগ্রহ করে", "pos": "verb"},
    "rangements": {"lemma": "rangement", "en": "storage cupboards", "bn": "আলমারি / স্টোরেজ", "pos": "noun"},
    "rangée": {"lemma": "ranger", "en": "tidy / organized", "bn": "পরিপাটি / সাজানো", "pos": "adjective"},
    "ranger": {"lemma": "ranger", "en": "to put away / pack", "bn": "গোছানো / রাখা", "pos": "verb"},
    "range": {"lemma": "ranger", "en": "packs / puts away", "bn": "গুছিয়ে রাখে", "pos": "verb"},
    "rapide": {"lemma": "rapide", "en": "fast / quick", "bn": "দ্রুত", "pos": "adjective"},
    "rapidement": {"lemma": "rapidement", "en": "promptly / quickly", "bn": "দ্রুততার সাথে", "pos": "adverb"},
    "rapprocher": {"lemma": "rapprocher", "en": "to get closer to", "bn": "কাছে আসা / কাছাকাছি হওয়া", "pos": "verb"},
    "rassurer": {"lemma": "rassurer", "en": "to reassure", "bn": "আশ্বস্ত করা / সাহস দেওয়া", "pos": "verb"},
    "ravi": {"lemma": "ravi", "en": "delighted / thrilled", "bn": "আনন্দিত / সন্তুষ্ট", "pos": "adjective"},
    "rayon": {"lemma": "rayon", "en": "supermarket section / aisle", "bn": "বিভাগ / সেকশন", "pos": "noun"},
    "recherche": {"lemma": "recherche", "en": "search / job hunting", "bn": "অনুসন্ধান / খোঁজা", "pos": "noun"},
    "recommencer": {"lemma": "recommencer", "en": "to start over", "bn": "পুনরায় শুরু করা", "pos": "verb"},
    "recruteur": {"lemma": "recruteur", "en": "recruiter / hiring manager", "bn": "নিয়োগকারী", "pos": "noun"},
    "recruteurs": {"lemma": "recruteur", "en": "recruiters", "bn": "নিয়োগকারীগণ", "pos": "noun"},
    "recrutement": {"lemma": "recrutement", "en": "recruitment", "bn": "নিয়োগ প্রক্রিয়া", "pos": "noun"},
    "recyclage": {"lemma": "recyclage", "en": "recycling", "bn": "পুনর্ব্যবহার / রিসাইক্লিং", "pos": "noun"},
    "redémarrer": {"lemma": "redémarrer", "en": "to restart / reboot", "bn": "রিস্টার্ট করা", "pos": "verb"},
    "regard": {"lemma": "regard", "en": "look / gaze", "bn": "দৃষ্টি / দৃষ্টিপাত", "pos": "noun"},
    "regarder": {"lemma": "regarder", "en": "to look at / watch", "bn": "তাকানো / দেখা", "pos": "verb"},
    "relever": {"lemma": "relever", "en": "to collect (mail)", "bn": "তুলে নেওয়া / সংগ্রহ করা", "pos": "verb"},
    "relève": {"lemma": "relever", "en": "collects (mail)", "bn": "সংগ্রহ করে", "pos": "verb"},
    "relevé": {"lemma": "relevé", "en": "statement (RIB / bank / grades)", "bn": "বিবরণী / স্টেটমেন্ট", "pos": "noun"},
    "relevés": {"lemma": "relevé", "en": "statements / transcripts", "bn": "বিবরণীসমূহ", "pos": "noun"},
    "remarquable": {"lemma": "remarquable", "en": "remarkable / outstanding", "bn": "অসাধারণ / প্রশংসনীয়", "pos": "adjective"},
    "remercier": {"lemma": "remercier", "en": "to thank", "bn": "ধন্যবাদ জানানো", "pos": "verb"},
    "remercie": {"lemma": "remercier", "en": "thanks", "bn": "ধন্যবাদ জানায়", "pos": "verb"},
    "remet": {"lemma": "remettre", "en": "hands over / gives", "bn": "হস্তান্তর করে / দেয়", "pos": "verb"},
    "remplace": {"lemma": "remplacer", "en": "replaces", "bn": "প্রতিস্থাপন করে", "pos": "verb"},
    "remplacement": {"lemma": "remplacement", "en": "replacement (loan machine)", "bn": "প্রতিস্থাপন / বিকল্প", "pos": "noun"},
    "remonte": {"lemma": "remonter", "en": "goes back up", "bn": "উপরে উঠে যায়", "pos": "verb"},
    "rencontre": {"lemma": "rencontre", "en": "meeting / encounter", "bn": "সাক্ষাৎ", "pos": "noun"},
    "renouveler": {"lemma": "renouveler", "en": "to renew (passport/visa)", "bn": "নবায়ন করা", "pos": "verb"},
    "repas": {"lemma": "repas", "en": "meal", "bn": "খাবার", "pos": "noun"},
    "reposer": {"lemma": "reposer", "en": "to rest", "bn": "বিশ্রাম নেওয়া", "pos": "verb"},
    "reprendre": {"lemma": "reprendre", "en": "to resume (studies)", "bn": "পুনরায় শুরু করা", "pos": "verb"},
    "responsable": {"lemma": "responsable", "en": "manager / coordinator / responsible", "bn": "প্রধান কর্মকর্তা / দায়িত্বপ্রাপ্ত", "pos": "noun"},
    "ressemble": {"lemma": "ressembler", "en": "resembles", "bn": "সদৃশ হওয়া", "pos": "verb"},
    "restaurant": {"lemma": "restaurant", "en": "restaurant", "bn": "রেস্তোরাঁ", "pos": "noun"},
    "restaurer": {"lemma": "restaurer", "en": "to restore", "bn": "পুনরুদ্ধার করা", "pos": "verb"},
    "reste": {"lemma": "reste", "en": "remainder / balance / stays", "bn": "অবশিষ্টাংশ / থাকে", "pos": "noun"},
    "rester": {"lemma": "rester", "en": "to stay / remain", "bn": "থাকা", "pos": "verb"},
    "retenue": {"lemma": "retenir", "en": "accepted / selected (candidacy)", "bn": "মনোনীত / গৃহীত", "pos": "adjective"},
    "retourne": {"lemma": "retourner", "en": "turns around / returns", "bn": "ঘোরে / ফেরে", "pos": "verb"},
    "retourner": {"lemma": "retourner", "en": "to return / go back", "bn": "ফিরে যাওয়া", "pos": "verb"},
    "retrouve": {"lemma": "retrouver", "en": "finds again", "bn": "আবার পায়", "pos": "verb"},
    "reçu": {"lemma": "reçu", "en": "receipt / received", "bn": "রসিদ / পেয়েছে", "pos": "noun"},
    "reçoit": {"lemma": "recevoir", "en": "receives / welcomes", "bn": "গ্রহণ করে / স্বাগত জানায়", "pos": "verb"},
    "reçoive": {"lemma": "recevoir", "en": "receives (subjunctive)", "bn": "পায়", "pos": "verb"},
    "rez-de-chaussée": {"lemma": "rez-de-chaussée", "en": "ground floor", "bn": "নিচতলা", "pos": "noun"},
    "rezdechaussée": {"lemma": "rez-de-chaussée", "en": "ground floor", "bn": "নিচতলা", "pos": "noun"},
    "rib": {"lemma": "RIB", "en": "bank account details statement", "bn": "আরআইবি (ব্যাংক বিবরণী)", "pos": "noun", "ttsText": "Relevé d'identité bancaire"},
    "riz": {"lemma": "riz", "en": "rice", "bn": "চাল / ভাত", "pos": "noun"},
    "rouge": {"lemma": "rouge", "en": "red", "bn": "লাল", "pos": "adjective"},
    "rouges": {"lemma": "rouge", "en": "red (plural)", "bn": "লাল", "pos": "adjective"},
    "règles": {"lemma": "règle", "en": "rules / settles (pays)", "bn": "নিয়মাবলী / পরিশোধ করে", "pos": "noun"},
    "règle": {"lemma": "régler", "en": "pays / settles / adjusts", "bn": "পরিশোধ করে / মেটায়", "pos": "verb"},
    "régler": {"lemma": "régler", "en": "to settle / pay / adjust", "bn": "পরিশোধ করা", "pos": "verb"},
    "réglementaires": {"lemma": "réglementaire", "en": "regulatory / legal", "bn": "আইনসম্মত / নিয়ন্ত্রণমূলক", "pos": "adjective"},
    "répondre": {"lemma": "répondre", "en": "to answer / reply", "bn": "উত্তর দেওয়া", "pos": "verb"},
    "répondu": {"lemma": "répondre", "en": "answered / applied", "bn": "উত্তর দিয়েছে / আবেদন করেছে", "pos": "verb"},
    "réponse": {"lemma": "réponse", "en": "answer / reply / decision", "bn": "উত্তর / সিদ্ধান্ত", "pos": "noun"},
    "réaction": {"lemma": "réaction", "en": "reaction", "bn": "প্রতিক্রিয়া", "pos": "noun"},
    "réagissez": {"lemma": "réagir", "en": "react (vous)", "bn": "প্রতিক্রিয়া জানান", "pos": "verb"},
    "récent": {"lemma": "récent", "en": "recent", "bn": "সাম্প্রতিক", "pos": "adjective"},
    "récépissé": {"lemma": "récépissé", "en": "official filing receipt / temporary permit", "bn": "প্রাপ্তিস্বীকার রসিদ / সাময়িক সনদ", "pos": "noun"},
    "rédige": {"lemma": "rédiger", "en": "writes / drafts (prescription)", "bn": "লেখে / প্রস্তুত করে", "pos": "verb"},
    "rédigée": {"lemma": "rédiger", "en": "written / drafted", "bn": "লিখিত", "pos": "adjective"},
    "réfrigérateur": {"lemma": "réfrigérateur", "en": "refrigerator / fridge", "bn": "রেফ্রিজারেটর / ফ্রিজ", "pos": "noun"},
    "résidence": {"lemma": "résidence", "en": "residence / housing building", "bn": "আবাসন ভবন / বাসভবন", "pos": "noun"},
    "résidentiel": {"lemma": "résidentiel", "en": "residential", "bn": "আবাসিক", "pos": "adjective"},
    "résout": {"lemma": "résoudre", "en": "resolves / solves", "bn": "সমাধান করে", "pos": "verb"},
    "réseau": {"lemma": "réseau", "en": "network", "bn": "নেটওয়ার্ক", "pos": "noun"},
    "réseaux": {"lemma": "réseau", "en": "networks", "bn": "নেটওয়ার্কসমূহ", "pos": "noun"},
    "réserver": {"lemma": "réserver", "en": "to book / reserve", "bn": "বুকিং করা / সময় নেওয়া", "pos": "verb"},
    "réunion": {"lemma": "réunion", "en": "meeting", "bn": "সভা / মিটিং", "pos": "noun"},
    "réussir": {"lemma": "réussir", "en": "to succeed", "bn": "সফল হওয়া", "pos": "verb"},
    "réutilisable": {"lemma": "réutilisable", "en": "reusable", "bn": "পুনর্ব্যবহারযোগ্য", "pos": "adjective"},
    "rôti": {"lemma": "rôtir", "en": "roasted", "bn": "রোস্ট করা", "pos": "adjective"},
    "rétablir": {"lemma": "rétablir", "en": "to recover", "bn": "আরোগ্য লাভ করা", "pos": "verb"},
    "rétablissement": {"lemma": "rétablissement", "en": "recovery (bon rétablissement)", "bn": "আরোগ্য / সুস্থতা", "pos": "noun"},
    "réelles": {"lemma": "réel", "en": "real / live (systems)", "bn": "বাস্তব", "pos": "adjective"},
}

print(f"Loaded Lexicon M-R: {len(LEXICON_M_R)} entries.")
