# -*- coding: utf-8 -*-
"""
Final Batch of Lexicon Words to achieve 100% token coverage
"""

LEXICON_FINAL = {
    "alors": {"lemma": "alors", "en": "then / so", "bn": "তখন / তাহলে", "pos": "conjunction"},
    "appréciée": {"lemma": "apprécier", "en": "appreciated / valued", "bn": "প্রশংসিত / সমাদৃত", "pos": "adjective"},
    "appréciées": {"lemma": "apprécier", "en": "appreciated (plural)", "bn": "সমাদৃত", "pos": "adjective"},
    "après": {"lemma": "après", "en": "after", "bn": "পরে", "pos": "preposition"},
    "arrivée": {"lemma": "arrivée", "en": "arrival", "bn": "আগমন", "pos": "noun"},
    "article": {"lemma": "article", "en": "item / article", "bn": "পণ্য / জিনিস", "pos": "noun"},
    "assermentée": {"lemma": "assermenter", "en": "sworn / certified (translation)", "bn": "অনুমোদিত / শপথবদ্ধ (অনুবাদ)", "pos": "adjective"},
    "asseyez": {"lemma": "asseoir", "en": "sit (asseyez-vous)", "bn": "বসুন", "pos": "verb"},
    "attend": {"lemma": "attendre", "en": "waits for", "bn": "অপেক্ষা করে", "pos": "verb"},
    "attentivement": {"lemma": "attentivement", "en": "attentively / carefully", "bn": "মনোযোগ সহকারে", "pos": "adverb"},
    "attestant": {"lemma": "attester", "en": "attesting / certifying", "bn": "প্রত্যয়নকারী / প্রমাণকারী", "pos": "verb"},
    "autour": {"lemma": "autour", "en": "around", "bn": "চারপাশে / ঘিরে", "pos": "preposition"},
    "autres": {"lemma": "autre", "en": "other / others", "bn": "অন্যান্য / অন্যরা", "pos": "adjective"},
    "aux": {"lemma": "à + les", "en": "to the / at the (plural)", "bn": "তে / প্রতি", "pos": "preposition"},
    "avoir": {"lemma": "avoir", "en": "to have", "bn": "থাকা / পাওয়া", "pos": "verb"},
    "bancaires": {"lemma": "bancaire", "en": "banking (plural)", "bn": "ব্যাংক সংক্রান্ত", "pos": "adjective"},
    "barres": {"lemma": "barre", "en": "bars (code-barres)", "bn": "বারকোড", "pos": "noun"},
    "bienvenu": {"lemma": "bienvenu", "en": "welcome", "bn": "স্বাগত", "pos": "adjective"},
    "bip": {"lemma": "bip", "en": "beep sound", "bn": "বিপ আওয়াজ", "pos": "expression"},
    "briques": {"lemma": "brique", "en": "cartons (of milk)", "bn": "দুধের প্যাকেট / কার্টন", "pos": "noun"},
    "carnet": {"lemma": "carnet", "en": "notebook / notepad", "bn": "নোটবুক / খাতা", "pos": "noun"},
    "carrière": {"lemma": "carrière", "en": "career", "bn": "কর্মজীবন / ক্যারিয়ার", "pos": "noun"},
    "cartonné": {"lemma": "cartonné", "en": "cardboard / paper-based", "bn": "কার্ডবোর্ডের", "pos": "adjective"},
    "cent": {"lemma": "cent", "en": "hundred", "bn": "একশত", "pos": "adjective"},
    "centre": {"lemma": "centre", "en": "center", "bn": "কেন্দ্র", "pos": "noun"},
    "cependant": {"lemma": "cependant", "en": "however / nevertheless", "bn": "তবে / তা সত্ত্বেও", "pos": "conjunction"},
    "ces": {"lemma": "ce", "en": "these / those", "bn": "এইসব", "pos": "adjective"},
    "cet": {"lemma": "ce", "en": "this (masculine vowel)", "bn": "এই", "pos": "adjective"},
    "cette": {"lemma": "ce", "en": "this (feminine)", "bn": "এই", "pos": "adjective"},
    "chaleureusement": {"lemma": "chaleureusement", "en": "warmly", "bn": "উষ্ণভাবে / আন্তরিকভাবে", "pos": "adverb"},
    "ciblées": {"lemma": "cibler", "en": "targeted (alerts)", "bn": "লক্ষ্যভিত্তিক / সুনির্দিষ্ট", "pos": "adjective"},
    "cinquante": {"lemma": "cinquante", "en": "fifty", "bn": "পঞ্চাশ", "pos": "adjective"},
    "clairement": {"lemma": "clairement", "en": "clearly", "bn": "পরিষ্কারভাবে / স্পষ্টভাবে", "pos": "adverb"},
    "conditions": {"lemma": "condition", "en": "terms / conditions", "bn": "শর্তাবলী / অবস্থা", "pos": "noun"},
    "confortable": {"lemma": "confortable", "en": "comfortable", "bn": "আরামদায়ক", "pos": "adjective"},
    "confortablement": {"lemma": "confortablement", "en": "comfortably", "bn": "আরামদায়কভাবে", "pos": "adverb"},
    "connexion": {"lemma": "connexion", "en": "internet connection", "bn": "সংযোগ / কানেকশন", "pos": "noun"},
    "contacte": {"lemma": "contacter", "en": "contacts", "bn": "যোগাযোগ করে", "pos": "verb"},
    "convenu": {"lemma": "convenir", "en": "agreed / scheduled (time)", "bn": "নির্ধারিত / সম্মত", "pos": "adjective"},
    "coordinatrice": {"lemma": "coordinateur", "en": "program coordinator (female)", "bn": "সমন্বয়কারী (মহিলা)", "pos": "noun"},
    "cordialement": {"lemma": "cordialement", "en": "cordially / warmly", "bn": "আন্তরিকভাবে", "pos": "adverb"},
    "coulissantes": {"lemma": "coulissant", "en": "sliding (doors)", "bn": "স্লাইডিং (দরজা)", "pos": "adjective"},
    "crédits": {"lemma": "crédit", "en": "academic credits / credit", "bn": "ক্রেডিট / পয়েন্ট", "pos": "noun"},
    "cv": {"lemma": "CV", "en": "curriculum vitae / resume", "bn": "জীবনবৃত্তান্ত / সিভি", "pos": "noun", "ttsText": "cé vé"},
    "derniers": {"lemma": "dernier", "en": "last / recent (plural)", "bn": "শেষ / সাম্প্রতিক", "pos": "adjective"},
    "derrière": {"lemma": "derrière", "en": "behind", "bn": "পেছনে", "pos": "preposition"},
    "des": {"lemma": "un", "en": "some / of the", "bn": "কিছু / গুলির", "pos": "article"},
    "deuxième": {"lemma": "deuxième", "en": "second", "bn": "দ্বিতীয়", "pos": "adjective"},
    "devez": {"lemma": "devoir", "en": "must / have to (vous)", "bn": "আপনাকে অবশ্যই হবে", "pos": "verb"},
    "devons": {"lemma": "devoir", "en": "must / have to (nous)", "bn": "আমাদের অবশ্যই হবে", "pos": "verb"},
    "dirige": {"lemma": "diriger", "en": "heads towards / directs", "bn": "অগ্রসর হয় / যায়", "pos": "verb"},
    "dos": {"lemma": "dos", "en": "back (backpack)", "bn": "পিঠ / কাঁধ", "pos": "noun"},
    "double": {"lemma": "double", "en": "double (glazing)", "bn": "দ্বিগুণ / ডাবল", "pos": "adjective"},
    "déjà": {"lemma": "déjà", "en": "already", "bn": "ইতিমধ্যে", "pos": "adverb"},
    "enchanté": {"lemma": "enchanté", "en": "pleased to meet you", "bn": "পরিচিত হয়ে আনন্দিত", "pos": "expression"},
    "ensemble": {"lemma": "ensemble", "en": "together", "bn": "একসাথে", "pos": "adverb"},
    "entraîner": {"lemma": "entraîner", "en": "to practice / train", "bn": "অনুশীলন করা", "pos": "verb"},
    "entrer": {"lemma": "entrer", "en": "to enter / come in", "bn": "প্রবেশ করা", "pos": "verb"},
    "entrez": {"lemma": "entrer", "en": "come in / enter (formal)", "bn": "আসুন / ভেতরে আসুন", "pos": "verb"},
    "espère": {"lemma": "espérer", "en": "hopes", "bn": "আশা করে", "pos": "verb"},
    "essentiel": {"lemma": "essentiel", "en": "essential / vital", "bn": "অত্যাবশ্যকীয় / মূল", "pos": "adjective"},
    "euro": {"lemma": "euro", "en": "euro (currency)", "bn": "ইউরো", "pos": "noun"},
    "exact": {"lemma": "exact", "en": "exact / accurate", "bn": "সঠিক / নির্ভুল", "pos": "adjective"},
    "exacte": {"lemma": "exact", "en": "exact (feminine)", "bn": "সঠিক", "pos": "adjective"},
    "exactement": {"lemma": "exactement", "en": "exactly", "bn": "ঠিক / নিখুঁতভাবে", "pos": "adverb"},
    "excusez": {"lemma": "excuser", "en": "excuse (excusez-moi)", "bn": "ক্ষমা করবেন", "pos": "verb"},
    "exploitation": {"lemma": "système d'exploitation", "en": "operating system", "bn": "অপারেটিং সিস্টেম", "pos": "noun"},
    "exprime": {"lemma": "exprimer", "en": "expresses oneself", "bn": "ব্যক্ত করে / প্রকাশ করে", "pos": "verb"},
    "face": {"lemma": "face", "en": "in front of / across", "bn": "মুখোমুখি", "pos": "noun"},
    "facilement": {"lemma": "facilement", "en": "easily", "bn": "সহজে", "pos": "adverb"},
    "fassions": {"lemma": "faire", "en": "make / do (subjunctive: que nous fassions)", "bn": "করি", "pos": "verb"},
    "fois": {"lemma": "fois", "en": "time / times (trois fois)", "bn": "বার (তিন বার)", "pos": "noun"},
    "fraîche": {"lemma": "frais", "en": "fresh / cool (feminine)", "bn": "তাজা / ঠান্ডা", "pos": "adjective"},
    "hier": {"lemma": "hier", "en": "yesterday", "bn": "গতকাল", "pos": "adverb"},
    "huit": {"lemma": "huit", "en": "eight", "bn": "আট", "pos": "adjective"},
    "illimité": {"lemma": "illimité", "en": "unlimited", "bn": "সীমাহীন / আনলিমিটেড", "pos": "adjective"},
    "ils": {"lemma": "il", "en": "they (masculine)", "bn": "তারা", "pos": "pronoun"},
    "informatiques": {"lemma": "informatique", "en": "computer / IT (plural)", "bn": "কম্পিউটার সংক্রান্ত", "pos": "adjective"},
    "inscris": {"lemma": "inscrire", "en": "enroll / sign up (j'inscris)", "bn": "নিবন্ধন করি / যুক্ত করি", "pos": "verb"},
    "inscrivant": {"lemma": "inscrire", "en": "enrolling (by enrolling)", "bn": "ভর্তি হয়ে / নিবন্ধন করে", "pos": "verb"},
    "intéresse": {"lemma": "intéresser", "en": "interests", "bn": "আগ্রহী করে", "pos": "verb"},
    "journées": {"lemma": "journée", "en": "days (demi-journées)", "bn": "দিনসমূহ", "pos": "noun"},
    "jusqu": {"lemma": "jusque", "en": "until / up to", "bn": "পর্যন্ত", "pos": "preposition"},
    "juste": {"lemma": "juste", "en": "just / right", "bn": "ঠিক / মাত্র", "pos": "adverb"},
    "justificative": {"lemma": "justificatif", "en": "supporting (piece justificative)", "bn": "প্রমাণপত্রমূলক", "pos": "adjective"},
    "justificatives": {"lemma": "justificatif", "en": "supporting (plural)", "bn": "প্রমাণপত্রমূলক", "pos": "adjective"},
    "lentement": {"lemma": "lentement", "en": "slowly", "bn": "ধীরে ধীরে", "pos": "adverb"},
    "locale": {"lemma": "local", "en": "local (feminine)", "bn": "স্থানীয়", "pos": "adjective"},
    "lorsqu": {"lemma": "lorsque", "en": "when / whenever (before vowel)", "bn": "যখন", "pos": "conjunction"},
    "légal": {"lemma": "légal", "en": "legal / lawful", "bn": "আইনসম্মত / বৈধ", "pos": "adjective"},
    "ma": {"lemma": "son", "en": "my (feminine)", "bn": "আমার", "pos": "pronoun"},
    "mal": {"lemma": "mal", "en": "pain / difficulty / bad", "bn": "ব্যথা / কষ্ট", "pos": "noun"},
    "manteau": {"lemma": "manteau", "en": "coat / overcoat", "bn": "কোট / ওভারকোট", "pos": "noun"},
    "me": {"lemma": "me", "en": "me / to me", "bn": "আমাকে", "pos": "pronoun"},
    "mensuel": {"lemma": "mensuel", "en": "monthly", "bn": "মাসিক", "pos": "adjective"},
    "menthe": {"lemma": "menthe", "en": "mint", "bn": "পুদিনা", "pos": "noun"},
    "mille": {"lemma": "mille", "en": "thousand (merci mille fois)", "bn": "হাজার", "pos": "adjective"},
    "moi": {"lemma": "moi", "en": "me", "bn": "আমাকে / আমি", "pos": "pronoun"},
    "mon": {"lemma": "son", "en": "my (masculine)", "bn": "আমার", "pos": "pronoun"},
    "murale": {"lemma": "mural", "en": "wall-mounted / on the wall", "bn": "দেয়ালে ঝুলানো", "pos": "adjective"},
    "méthode": {"lemma": "méthode", "en": "method / structured way", "bn": "পদ্ধতি / নিয়ম", "pos": "noun"},
    "ne": {"lemma": "ne", "en": "not (part 1)", "bn": "না", "pos": "adverb"},
    "noir": {"lemma": "noir", "en": "black", "bn": "কালো", "pos": "adjective"},
    "nos": {"lemma": "notre", "en": "our (plural)", "bn": "আমাদের", "pos": "pronoun"},
    "notre": {"lemma": "notre", "en": "our", "bn": "আমাদের", "pos": "pronoun"},
    "nous": {"lemma": "nous", "en": "we / us", "bn": "আমরা / আমাদের", "pos": "pronoun"},
    "nécessaire": {"lemma": "nécessaire", "en": "necessary", "bn": "প্রয়োজনীয়", "pos": "adjective"},
    "on": {"lemma": "on", "en": "one / we / people", "bn": "আমরা / মানুষ", "pos": "pronoun"},
    "opportunité": {"lemma": "opportunité", "en": "opportunity / job opening", "bn": "সুযোগ", "pos": "noun"},
    "ou": {"lemma": "ou", "en": "or", "bn": "অথবা", "pos": "conjunction"},
    "oublier": {"lemma": "oublier", "en": "to forget", "bn": "ভুলে যাওয়া", "pos": "verb"},
    "où": {"lemma": "où", "en": "where", "bn": "কোথায় / যেখানে", "pos": "adverb"},
    "paramètre": {"lemma": "paramétrer", "en": "sets up / configures", "bn": "সেটআপ করে / কনফিগার করে", "pos": "verb"},
    "parfaitement": {"lemma": "parfaitement", "en": "perfectly", "bn": "নিখুঁতভাবে", "pos": "adverb"},
    "parfois": {"lemma": "parfois", "en": "sometimes", "bn": "মাঝে মাঝে", "pos": "adverb"},
    "parmi": {"lemma": "parmi", "en": "among / amidst", "bn": "মাঝে / মধ্যে", "pos": "preposition"},
    "peine": {"lemma": "peine", "en": "scarcely / barely (à peine)", "bn": "মাত্র / সবেমাত্র", "pos": "noun"},
    "pendant": {"lemma": "pendant", "en": "during", "bn": "চলাকালীন / সময়ে", "pos": "preposition"},
    "peu": {"lemma": "peu", "en": "little / slight", "bn": "একটু / অল্প", "pos": "adverb"},
    "pièces": {"lemma": "pièce", "en": "documents / coins / rooms", "bn": "নথিপত্র / মুদ্রা / কক্ষ", "pos": "noun"},
    "porte": {"lemma": "porte", "en": "door", "bn": "দরজা", "pos": "noun"},
    "pose": {"lemma": "poser", "en": "places / puts / asks", "bn": "রাখে / জিজ্ঞেস করে", "pos": "verb"},
    "possible": {"lemma": "possible", "en": "possible", "bn": "সম্ভব", "pos": "adjective"},
    "possède": {"lemma": "posséder", "en": "features / owns", "bn": "রয়েছে / আছে", "pos": "verb"},
    "prie": {"lemma": "prier", "en": "please (je vous en prie)", "bn": "দয়া করে আসুন / অনুরোধ", "pos": "verb"},
    "principale": {"lemma": "principal", "en": "main / principal", "bn": "প্রধান", "pos": "adjective"},
    "proches": {"lemma": "proche", "en": "close relatives / family", "bn": "নিকটাত্মীয় / পরিবার", "pos": "noun"},
    "proposons": {"lemma": "proposer", "en": "offer (nous)", "bn": "অফার করি / দিই", "pos": "verb"},
    "proximité": {"lemma": "proximité", "en": "proximity / on-site (support de proximité)", "bn": "নিকটবর্তী / অন-সাইট", "pos": "noun"},
    "près": {"lemma": "près", "en": "near / close to", "bn": "কাছে / নিকটে", "pos": "preposition"},
    "présente": {"lemma": "présenter", "en": "presents / introduces", "bn": "উপস্থাপন করে", "pos": "verb"},
    "puis": {"lemma": "puis", "en": "then", "bn": "তারপর", "pos": "adverb"},
    "pédagogique": {"lemma": "pédagogique", "en": "educational / academic", "bn": "শিক্ষাগত / পাঠদান সংক্রান্ত", "pos": "adjective"},
    "qualité": {"lemma": "qualité", "en": "quality", "bn": "মান / গুণগত মান", "pos": "noun"},
    "quand": {"lemma": "quand", "en": "when", "bn": "যখন", "pos": "conjunction"},
    "quarante": {"lemma": "quarante", "en": "forty", "bn": "চল্লিশ", "pos": "adjective"},
    "quatrième": {"lemma": "quatrième", "en": "fourth", "bn": "চতুর্থ", "pos": "adjective"},
    "quelques": {"lemma": "quelque", "en": "a few / some", "bn": "কয়েকটি / কিছু", "pos": "adjective"},
    "question": {"lemma": "question", "en": "question", "bn": "প্রশ্ন", "pos": "noun"},
    "questions": {"lemma": "question", "en": "questions", "bn": "প্রশ্নসমূহ", "pos": "noun"},
    "qui": {"lemma": "qui", "en": "who / which", "bn": "যে / কে", "pos": "pronoun"},
    "reconnaître": {"lemma": "reconnaître", "en": "to recognize officially", "bn": "স্বীকৃতি দেওয়া", "pos": "verb"},
    "relation": {"lemma": "relation", "en": "relationship / interaction", "bn": "সম্পর্ক / যোগাযোগ", "pos": "noun"},
    "rendez": {"lemma": "rendre", "en": "return / appointment (rendez-vous)", "bn": "সাক্ষাৎ / ফেরত দেওয়া", "pos": "noun"},
    "renforcée": {"lemma": "renforcer", "en": "reinforced / strengthened", "bn": "দৃঢ় / জোরদার", "pos": "adjective"},
    "repart": {"lemma": "repartir", "en": "leaves / goes away", "bn": "প্রস্থান করে / চলে যায়", "pos": "verb"},
    "requises": {"lemma": "requis", "en": "required (plural)", "bn": "প্রয়োজনীয় / আবশ্যকীয়", "pos": "adjective"},
    "retracer": {"lemma": "retracer", "en": "to recount / trace back", "bn": "তুলে ধরা / বর্ণনা করা", "pos": "verb"},
    "revient": {"lemma": "revenir", "en": "comes back / returns", "bn": "ফিরে আসে", "pos": "verb"},
    "rien": {"lemma": "rien", "en": "nothing", "bn": "কিছু না", "pos": "pronoun"},
    "route": {"lemma": "route", "en": "roadmap / road", "bn": "রোডম্যাপ / পথ", "pos": "noun"},
    "réel": {"lemma": "réel", "en": "real / live", "bn": "বাস্তব", "pos": "adjective"},
    "régulier": {"lemma": "régulier", "en": "steady / regular", "bn": "নিয়মিত / স্থির", "pos": "adjective"},
    "se": {"lemma": "se", "en": "himself / herself / oneself", "bn": "নিজেকে", "pos": "pronoun"},
    "ses": {"lemma": "son", "en": "his / her / its (plural)", "bn": "তার (বহুবচন)", "pos": "pronoun"},
    "si": {"lemma": "si", "en": "if", "bn": "যদি", "pos": "conjunction"},
    "siège": {"lemma": "siège", "en": "headquarters / seat", "bn": "প্রধান কার্যালয় / হেডকোয়ার্টার", "pos": "noun"},
    "soin": {"lemma": "soin", "en": "care / diligence", "bn": "যত্ন / মনোযোগ", "pos": "noun"},
    "sol": {"lemma": "sol", "en": "ground / floor", "bn": "মেঝে / মাটি", "pos": "noun"},
    "sortie": {"lemma": "sortie", "en": "exit", "bn": "বের হওয়ার পথ / প্রস্থান", "pos": "noun"},
    "souriante": {"lemma": "souriant", "en": "smiling (feminine)", "bn": "হাস্যোজ্জ্বল", "pos": "adjective"},
    "sous": {"lemma": "sous", "en": "under / within (sous 48h)", "bn": "নিচে / এর মধ্যে", "pos": "preposition"},
    "stage": {"lemma": "stage", "en": "internship / practical training", "bn": "ইন্টার্নশিপ / বাস্তব প্রশিক্ষণ", "pos": "noun"},
    "standard": {"lemma": "standard", "en": "standard", "bn": "মানসম্মত / সাধারণ", "pos": "adjective"},
    "standards": {"lemma": "standard", "en": "standards / norms", "bn": "মানদণ্ড", "pos": "noun"},
    "suite": {"lemma": "suite", "en": "following / next steps", "bn": "পরবর্তী ধাপ / ধারাবাহিকতা", "pos": "noun"},
    "suivre": {"lemma": "suivre", "en": "to follow / track", "bn": "অনুসরণ করা / পর্যবেক্ষণ", "pos": "verb"},
    "supérieures": {"lemma": "supérieur", "en": "higher (education)", "bn": "উচ্চ (শিক্ষা)", "pos": "adjective"},
    "surtout": {"lemma": "surtout", "en": "above all / especially", "bn": "বিশেষ করে", "pos": "adverb"},
    "ta": {"lemma": "son", "en": "your (feminine)", "bn": "তোমার", "pos": "pronoun"},
    "tant": {"lemma": "tant", "en": "as (en tant que)", "bn": "হিসেবে", "pos": "adverb"},
    "te": {"lemma": "te", "en": "you (to you)", "bn": "তোমাকে", "pos": "pronoun"},
    "temporairement": {"lemma": "temporairement", "en": "temporarily", "bn": "সাময়িকভাবে", "pos": "adverb"},
    "terre": {"lemma": "terre", "en": "earth / potatoes (pommes de terre)", "bn": "মাটি / আলু", "pos": "noun"},
    "thermomètre": {"lemma": "thermomètre", "en": "thermometer", "bn": "থার্মোমিটার", "pos": "noun"},
    "théoriques": {"lemma": "théorique", "en": "theoretical (classes)", "bn": "তাত্ত্বিক", "pos": "adjective"},
    "toute": {"lemma": "tout", "en": "all / entire (feminine)", "bn": "পুরো / সমস্ত", "pos": "adjective"},
    "toutes": {"lemma": "tout", "en": "all (feminine plural)", "bn": "সবগুলো", "pos": "adjective"},
    "trois": {"lemma": "trois", "en": "three", "bn": "তিন", "pos": "adjective"},
    "troisième": {"lemma": "troisième", "en": "third", "bn": "তৃতীয়", "pos": "adjective"},
    "ufs": {"lemma": "œuf", "en": "eggs (oeufs)", "bn": "ডিম", "pos": "noun"},
    "ur": {"lemma": "heure", "en": "hour", "bn": "ঘণ্টা", "pos": "noun"},
    "vitae": {"lemma": "curriculum vitae", "en": "vitae (CV)", "bn": "জীবনবৃত্তান্ত", "pos": "noun"},
    "vos": {"lemma": "votre", "en": "your (plural)", "bn": "আপনার", "pos": "pronoun"},
    "vraiment": {"lemma": "vraiment", "en": "truly / really", "bn": "সত্যিই / প্রকৃতপক্ষে", "pos": "adverb"},
    "vêtues": {"lemma": "vêtir", "en": "dressed (feminine plural)", "bn": "পরিহিত / পোশাক পরিধানকারী", "pos": "adjective"},
    "y": {"lemma": "y", "en": "there", "bn": "সেখানে", "pos": "pronoun"},
    "écrémé": {"lemma": "écrémé", "en": "semi-skimmed (milk)", "bn": "সেমি-স্কিমড (দুধ)", "pos": "adjective"},
    "électriques": {"lemma": "électrique", "en": "electric", "bn": "বৈদ্যুতিক", "pos": "adjective"},
    "électronique": {"lemma": "électronique", "en": "electronic", "bn": "ইলেকট্রনিক", "pos": "adjective"},
    "électroniquement": {"lemma": "électroniquement", "en": "electronically", "bn": "ইলেকট্রনিকভাবে", "pos": "adverb"},
    "élégamment": {"lemma": "élégamment", "en": "elegantly", "bn": "মার্জিতভাবে", "pos": "adverb"},
    "élégant": {"lemma": "élégant", "en": "smart / elegant", "bn": "মার্জিত", "pos": "adjective"},
    "être": {"lemma": "être", "en": "to be", "bn": "হওয়া", "pos": "verb"},
}

print(f"Loaded Lexicon Final: {len(LEXICON_FINAL)} entries.")
