# -*- coding: utf-8 -*-
"""
Lexicon Part 1: Numbers, A, B, C
"""

LEXICON_A_C = {
    # Numbers & Special
    "4g": {"lemma": "4G", "en": "4G mobile network", "bn": "৪জি মোবাইল নেটওয়ার্ক", "pos": "noun"},
    "5g": {"lemma": "5G", "en": "5G mobile network", "bn": "৫জি মোবাইল নেটওয়ার্ক", "pos": "noun"},
    "a-42": {"lemma": "A-42", "en": "ticket number A-42", "bn": "টিকেট নম্বর এ-৪২", "pos": "noun", "ttsText": "Ticket A quarante-deux"},

    # A
    "a": {"lemma": "avoir", "en": "has", "bn": "আছে", "pos": "verb"},
    "ai": {"lemma": "avoir", "en": "have (first person: j'ai)", "bn": "আছে (আমার আছে)", "pos": "verb"},
    "ont": {"lemma": "avoir", "en": "have (plural)", "bn": "আছে (তাদের আছে)", "pos": "verb"},
    "avons": {"lemma": "avoir", "en": "have (we have)", "bn": "আছে (আমাদের আছে)", "pos": "verb"},
    "avez": {"lemma": "avoir", "en": "have (you have)", "bn": "আছে (আপনার আছে)", "pos": "verb"},
    "avait": {"lemma": "avoir", "en": "had (imparfait)", "bn": "ছিল", "pos": "verb"},
    "aura": {"lemma": "avoir", "en": "will have", "bn": "থাকবে", "pos": "verb"},
    "auront": {"lemma": "avoir", "en": "will have (plural)", "bn": "থাকবে", "pos": "verb"},
    "eu": {"lemma": "avoir", "en": "had (past participle)", "bn": "পেয়েছে / হয়েছে", "pos": "verb"},
    "abord": {"lemma": "d'abord", "en": "first of all", "bn": "প্রথমে / শুরুতে", "pos": "adverb"},
    "académiques": {"lemma": "académique", "en": "academic", "bn": "একাডেমিক / শিক্ষাগত", "pos": "adjective"},
    "accompagnement": {"lemma": "accompagnement", "en": "guidance / support / coaching", "bn": "দিকনির্দেশনা / সহায়তা", "pos": "noun"},
    "accompagnée": {"lemma": "accompagner", "en": "accompanied", "bn": "সাথে থাকা", "pos": "adjective"},
    "accompagnées": {"lemma": "accompagner", "en": "accompanied (feminine plural)", "bn": "সংযুক্ত / সাথে থাকা", "pos": "adjective"},
    "accord": {"lemma": "accord", "en": "agreement / OK", "bn": "সম্মত / চুক্তি", "pos": "noun"},
    "accueil": {"lemma": "accueil", "en": "reception / welcome", "bn": "অভ্যর্থনা / স্বাগত", "pos": "noun"},
    "accueillant": {"lemma": "accueillant", "en": "welcoming / friendly", "bn": "উষ্ণ অভ্যর্থনাকারী", "pos": "adjective"},
    "accueillants": {"lemma": "accueillant", "en": "welcoming (plural)", "bn": "আন্তরিক / বন্ধুবৎসল", "pos": "adjective"},
    "accueille": {"lemma": "accueillir", "en": "welcomes / receives", "bn": "স্বাগত জানায়", "pos": "verb"},
    "accueillent": {"lemma": "accueillir", "en": "welcome (plural)", "bn": "স্বাগত জানায়", "pos": "verb"},
    "accès": {"lemma": "accès", "en": "access / entrance", "bn": "প্রবেশাধিকার / অ্যাক্সেস", "pos": "noun"},
    "accélérer": {"lemma": "accélérer", "en": "to accelerate / speed up", "bn": "গতিশীল করা / ত্বরান্বিত করা", "pos": "verb"},
    "achats": {"lemma": "achat", "en": "purchases / shopping", "bn": "কেনাকাটা / পণ্য", "pos": "noun"},
    "acheter": {"lemma": "acheter", "en": "to buy", "bn": "কেনা", "pos": "verb"},
    "active": {"lemma": "activer", "en": "activates", "bn": "সক্রিয় করে", "pos": "verb"},
    "activement": {"lemma": "activement", "en": "actively", "bn": "সক্রিয়ভাবে", "pos": "adverb"},
    "actuels": {"lemma": "actuel", "en": "current / present", "bn": "বর্তমান / চলমান", "pos": "adjective"},
    "adapter": {"lemma": "adapter", "en": "to adapt / tailor", "bn": "উপযোগী করা / মানিয়ে নেওয়া", "pos": "verb"},
    "adaptée": {"lemma": "adapter", "en": "adapted / suited", "bn": "উপযোগী / উপযুক্ত", "pos": "adjective"},
    "addition": {"lemma": "addition", "en": "restaurant bill", "bn": "খাবারের বিল", "pos": "noun"},
    "adhésive": {"lemma": "adhésif", "en": "adhesive / sticky", "bn": "আঠালো", "pos": "adjective"},
    "administratif": {"lemma": "administratif", "en": "administrative", "bn": "প্রশাসনিক", "pos": "adjective"},
    "administration": {"lemma": "administration", "en": "administration / public office", "bn": "প্রশাসন / ব্যবস্থাপনা", "pos": "noun"},
    "admission": {"lemma": "admission", "en": "admission / enrollment", "bn": "ভর্তি / অন্তর্ভুক্তি", "pos": "noun"},
    "adresse": {"lemma": "adresse", "en": "address", "bn": "ঠিকানা", "pos": "noun"},
    "agence": {"lemma": "agence", "en": "agency / branch", "bn": "সংস্থা / এজেন্সি / শাখা", "pos": "noun"},
    "agencé": {"lemma": "agencer", "en": "laid out / organized", "bn": "সাজানো / বিন্যস্ত", "pos": "adjective"},
    "aident": {"lemma": "aider", "en": "help (plural)", "bn": "সাহায্য করে", "pos": "verb"},
    "aider": {"lemma": "aider", "en": "to help / assist", "bn": "সাহায্য করা", "pos": "verb"},
    "aimable": {"lemma": "aimable", "en": "kind / amiable", "bn": "দয়ালু / অমায়িক", "pos": "adjective"},
    "aimablement": {"lemma": "aimablement", "en": "kindly / pleasantly", "bn": "অমায়িকতার সাথে", "pos": "adverb"},
    "aimerais": {"lemma": "aimer", "en": "would like", "bn": "চাই / পছন্দ করব", "pos": "verb"},
    "ainsi": {"lemma": "ainsi", "en": "thus / in this way", "bn": "এভাবে / সুতরাং", "pos": "adverb"},
    "alertes": {"lemma": "alerte", "en": "alerts / notifications", "bn": "সতর্কবার্তা / নোটিফিকেশন", "pos": "noun"},
    "allez": {"lemma": "aller", "en": "go / are going (vous)", "bn": "যাচ্ছেন", "pos": "verb"},
    "allons": {"lemma": "aller", "en": "are going (nous)", "bn": "যাচ্ছি", "pos": "verb"},
    "allées": {"lemma": "allée", "en": "aisles / walkways", "bn": "সারি / করিডোর", "pos": "noun"},
    "ambiance": {"lemma": "ambiance", "en": "atmosphere / mood", "bn": "পরিবেশ / আবহ", "pos": "noun"},
    "amical": {"lemma": "amical", "en": "friendly", "bn": "বন্ধুত্বপূর্ণ", "pos": "adjective"},
    "amicale": {"lemma": "amical", "en": "friendly (feminine)", "bn": "বন্ধুত্বপূর্ণ", "pos": "adjective"},
    "amicalement": {"lemma": "amicalement", "en": "in a friendly manner", "bn": "বন্ধুত্বপূর্ণভাবে", "pos": "adverb"},
    "an": {"lemma": "an", "en": "year", "bn": "বছর", "pos": "noun"},
    "analyse": {"lemma": "analyse", "en": "analysis / review", "bn": "বিশ্লেষণ", "pos": "noun"},
    "angine": {"lemma": "angine", "en": "throat infection / angina", "bn": "গলার ইনফেকশন / টনসিল", "pos": "noun"},
    "animé": {"lemma": "animer", "en": "lively / buzzing", "bn": "প্রাণবন্ত / মুখরিত", "pos": "adjective"},
    "annonces": {"lemma": "annonce", "en": "listings / advertisements", "bn": "বিজ্ঞাপন / তালিকা", "pos": "noun"},
    "année": {"lemma": "année", "en": "year (duration)", "bn": "বছর", "pos": "noun"},
    "années": {"lemma": "année", "en": "years", "bn": "বছরগুলো", "pos": "noun"},
    "ans": {"lemma": "an", "en": "years", "bn": "বছর", "pos": "noun"},
    "aperçoit": {"lemma": "apercevoir", "en": "spots / notices / catches sight of", "bn": "দেখতে পায় / চোখে পড়ে", "pos": "verb"},
    "appareil": {"lemma": "appareil", "en": "device / appliance", "bn": "যন্ত্র / ডিভাইস", "pos": "noun"},
    "appartement": {"lemma": "appartement", "en": "apartment / flat", "bn": "অ্যাপার্টমেন্ট / ফ্ল্যাট", "pos": "noun"},
    "appelle": {"lemma": "appeler", "en": "calls / names", "bn": "ডাকে / নাম", "pos": "verb"},
    "appels": {"lemma": "appel", "en": "phone calls", "bn": "ফোন কল", "pos": "noun"},
    "appelé": {"lemma": "appeler", "en": "called (past participle)", "bn": "ডেকেছিল / কল করেছিল", "pos": "verb"},
    "application": {"lemma": "application", "en": "app / application", "bn": "অ্যাপ্লিকেশন / অ্যাপ", "pos": "noun"},
    "appliquées": {"lemma": "appliquer", "en": "applied (sciences)", "bn": "ফলিত (বিজ্ঞান)", "pos": "adjective"},
    "apportées": {"lemma": "apporter", "en": "brought (feminine plural)", "bn": "আনা / নিয়ে আসা", "pos": "adjective"},
    "apporte": {"lemma": "apporter", "en": "brings", "bn": "নিয়ে আসে", "pos": "verb"},
    "appris": {"lemma": "apprendre", "en": "learned", "bn": "শিখেছে", "pos": "verb"},
    "appuie": {"lemma": "appuyer", "en": "presses (a button)", "bn": "চাপ দেয়", "pos": "verb"},
    "ardoise": {"lemma": "ardoise", "en": "chalkboard / slate menu", "bn": "কালো স্লেট বোর্ড / মেন্যু বোর্ড", "pos": "noun"},
    "arriver": {"lemma": "arriver", "en": "to arrive", "bn": "পৌঁছানো", "pos": "verb"},
    "arriveront": {"lemma": "arriver", "en": "will arrive", "bn": "পৌঁছাবে", "pos": "verb"},
    "ascenseur": {"lemma": "ascenseur", "en": "elevator / lift", "bn": "লিফট / এলিভেটর", "pos": "noun"},
    "asseoir": {"lemma": "asseoir", "en": "to sit down", "bn": "বসা", "pos": "verb"},
    "asseyez-vous": {"lemma": "asseoir", "en": "sit down (formal)", "bn": "বসুন", "pos": "verb"},
    "asseyezvous": {"lemma": "asseoir", "en": "sit down (formal)", "bn": "বসুন", "pos": "verb"},
    "assistance": {"lemma": "assistance", "en": "support / assistance", "bn": "সহায়তা / সাপোর্ট", "pos": "noun"},
    "assurance": {"lemma": "assurance", "en": "confidence / insurance", "bn": "আত্মবিশ্বাস / নিশ্চয়তা", "pos": "noun"},
    "atelier": {"lemma": "atelier", "en": "workshop", "bn": "কর্মশালা / ওয়ার্কশপ", "pos": "noun"},
    "attente": {"lemma": "attente", "en": "waiting", "bn": "অপেক্ষা", "pos": "noun"},
    "attention": {"lemma": "attention", "en": "attention / care", "bn": "মনোযোগ", "pos": "noun"},
    "attestation": {"lemma": "attestation", "en": "certificate / formal proof", "bn": "প্রত্যয়নপত্র / সনদ", "pos": "noun"},
    "attitude": {"lemma": "attitude", "en": "attitude / mindset", "bn": "মনোভাব / আচরণ", "pos": "noun"},
    "ausculte": {"lemma": "ausculter", "en": "examines / listens with stethoscope", "bn": "স্টেথোস্কোপ দিয়ে পরীক্ষা করে", "pos": "verb"},
    "automatique": {"lemma": "automatique", "en": "automatic", "bn": "স্বয়ংক্রিয়", "pos": "adjective"},
    "avance": {"lemma": "avance", "en": "ahead / early", "bn": "আগে", "pos": "noun"},
    "avenir": {"lemma": "avenir", "en": "future", "bn": "ভবিষ্যত", "pos": "noun"},
    "avenue": {"lemma": "avenue", "en": "avenue / wide street", "bn": "প্রধান প্রশস্ত রাস্তা", "pos": "noun"},
    "aventure": {"lemma": "aventure", "en": "adventure / journey", "bn": "অভিযান / রোমাঞ্চকর যাত্রা", "pos": "noun"},

    # B
    "bac": {"lemma": "bac", "en": "recycling bin / container", "bn": "ময়লার বিন / পাত্র", "pos": "noun"},
    "bain": {"lemma": "bain", "en": "bath", "bn": "গোসল", "pos": "noun"},
    "bancaire": {"lemma": "bancaire", "en": "banking / bank-related", "bn": "ব্যাংক সংক্রান্ত", "pos": "adjective"},
    "banque": {"lemma": "banque", "en": "bank", "bn": "ব্যাংক", "pos": "noun"},
    "base": {"lemma": "base", "en": "base / basis / foundation", "bn": "ভিত্তি / মৌলিক", "pos": "noun"},
    "bases": {"lemma": "base", "en": "foundations / basics", "bn": "মৌলিক বিষয়সমূহ", "pos": "noun"},
    "besoin": {"lemma": "besoin", "en": "need", "bn": "প্রয়োজন", "pos": "noun"},
    "besoins": {"lemma": "besoin", "en": "needs / requirements", "bn": "প্রয়োজনীয়তা", "pos": "noun"},
    "bienveillante": {"lemma": "bienveillant", "en": "benevolent / kind / caring", "bn": "সহানুভূতিশীল / অমায়িক", "pos": "adjective"},
    "billet": {"lemma": "billet", "en": "banknote / ticket", "bn": "টাকার নোট / টিকিট", "pos": "noun"},
    "blanc": {"lemma": "blanc", "en": "white (masculine)", "bn": "সাদা", "pos": "adjective"},
    "blanche": {"lemma": "blanc", "en": "white (feminine)", "bn": "সাদা", "pos": "adjective"},
    "bloquer": {"lemma": "bloquer", "en": "to block / freeze (card)", "bn": "ব্লক করা / সাময়িক বন্ধ করা", "pos": "verb"},
    "bloqué": {"lemma": "bloquer", "en": "blocked / frozen / stuck", "bn": "আটকে যাওয়া / বন্ধ", "pos": "adjective"},
    "blouse": {"lemma": "blouse", "en": "lab coat / medical coat", "bn": "মেডিকেল কোট / অ্যাপ্রোন", "pos": "noun"},
    "boire": {"lemma": "boire", "en": "to drink", "bn": "পান করা", "pos": "verb"},
    "boisson": {"lemma": "boisson", "en": "drink / beverage", "bn": "পানীয়", "pos": "noun"},
    "boîte": {"lemma": "boîte", "en": "box", "bn": "বাক্স", "pos": "noun"},
    "boîtes": {"lemma": "boîte", "en": "boxes / mailboxes", "bn": "বাক্সগুলো / চিঠির বাক্স", "pos": "noun"},
    "bois": {"lemma": "bois", "en": "wood", "bn": "কাঠ", "pos": "noun"},
    "boutique": {"lemma": "boutique", "en": "store / boutique", "bn": "দোকান", "pos": "noun"},
    "bouton": {"lemma": "bouton", "en": "button", "bn": "বোতাম / বাটন", "pos": "noun"},
    "brasserie": {"lemma": "brasserie", "en": "brasserie / casual French restaurant", "bn": "ফরাসি রেস্তোরাঁ", "pos": "noun"},
    "budget": {"lemma": "budget", "en": "budget", "bn": "বাজেট", "pos": "noun"},
    "bulletins": {"lemma": "bulletin", "en": "pay slips / report cards", "bn": "বেতন স্লিপ / বিবরণী", "pos": "noun"},
    "bureau": {"lemma": "bureau", "en": "office / desk", "bn": "অফিস / পড়ার টেবিল", "pos": "noun"},
    "bureaux": {"lemma": "bureau", "en": "offices", "bn": "অফিসসমূহ", "pos": "noun"},
    "bâtiment": {"lemma": "bâtiment", "en": "building", "bn": "ভবন / বিল্ডিং", "pos": "noun"},
    "bénéficier": {"lemma": "bénéficier", "en": "to benefit / receive", "bn": "সুবিধা পাওয়া / লাভ করা", "pos": "verb"},

    # C
    "cabinet": {"lemma": "cabinet", "en": "doctor's surgery / practice", "bn": "ডাক্তারখানা / চেম্বার", "pos": "noun"},
    "caisse": {"lemma": "caisse", "en": "checkout / cash register", "bn": "ক্যাশ কাউন্টার", "pos": "noun"},
    "caisses": {"lemma": "caisse", "en": "checkouts", "bn": "ক্যাশ কাউন্টারগুলো", "pos": "noun"},
    "calme": {"lemma": "calme", "en": "calm / quiet", "bn": "শান্ত", "pos": "adjective"},
    "calmer": {"lemma": "calmer", "en": "to soothe / calm down", "bn": "উপশম করা / শান্ত করা", "pos": "verb"},
    "camion": {"lemma": "camion", "en": "truck / garbage truck", "bn": "ট্রাক", "pos": "noun"},
    "campus": {"lemma": "campus", "en": "university campus", "bn": "ক্যাম্পাস", "pos": "noun"},
    "candidature": {"lemma": "candidature", "en": "application / candidacy", "bn": "আবেদন / প্রার্থিতা", "pos": "noun"},
    "carafe": {"lemma": "carafe", "en": "pitcher / water jug", "bn": "পানির জগ", "pos": "noun"},
    "card": {"lemma": "carte", "en": "card", "bn": "কার্ড", "pos": "noun"},
    "carrés": {"lemma": "carré", "en": "square (metres)", "bn": "বর্গ (মিটার)", "pos": "adjective"},
    "carte": {"lemma": "carte", "en": "card / menu", "bn": "কার্ড / মেনু", "pos": "noun"},
    "carton": {"lemma": "carton", "en": "cardboard box", "bn": "কার্ডবোর্ড / শক্ত কাগজ", "pos": "noun"},
    "cartonnée": {"lemma": "cartonné", "en": "made of cardboard / stiff paper", "bn": "কার্ডবোর্ডের তৈরি", "pos": "adjective"},
    "cause": {"lemma": "cause", "en": "cause / reason", "bn": "কারণ", "pos": "noun"},
    "centaines": {"lemma": "centaine", "en": "hundreds", "bn": "শত শত", "pos": "noun"},
    "centre-ville": {"lemma": "centre-ville", "en": "city centre / downtown", "bn": "শহরের কেন্দ্রস্থল", "pos": "noun"},
    "centreville": {"lemma": "centre-ville", "en": "city centre", "bn": "শহরের কেন্দ্রস্থল", "pos": "noun"},
    "certifiée": {"lemma": "certifier", "en": "certified", "bn": "সত্যায়িত", "pos": "adjective"},
    "certifiées": {"lemma": "certifier", "en": "certified (plural)", "bn": "সত্যায়িত", "pos": "adjective"},
    "certitude": {"lemma": "certitude", "en": "certainty", "bn": "নিশ্চয়তা", "pos": "noun"},
    "chaleureux": {"lemma": "chaleureux", "en": "warm / cordial", "bn": "উষ্ণ / আন্তরিক", "pos": "adjective"},
    "chaleureuse": {"lemma": "chaleureux", "en": "warm (feminine)", "bn": "উষ্ণ", "pos": "adjective"},
    "chambre": {"lemma": "chambre", "en": "bedroom / room", "bn": "শোবার ঘর / রুম", "pos": "noun"},
    "chances": {"lemma": "chance", "en": "chances / luck", "bn": "সুযোগ / সম্ভাবনা", "pos": "noun"},
    "changer": {"lemma": "changer", "en": "to change / reset", "bn": "পরিবর্তন করা / বদলানো", "pos": "verb"},
    "charges": {"lemma": "charge", "en": "utility charges / maintenance fees", "bn": "ইউটিলিটি চার্জ / সার্ভিস চার্জ", "pos": "noun"},
    "chauffage": {"lemma": "chauffage", "en": "heating", "bn": "হিটিং ব্যবস্থা", "pos": "noun"},
    "chef": {"lemma": "chef", "en": "chef / boss", "bn": "প্রধান বাবুর্চি / প্রধান", "pos": "noun"},
    "chemin": {"lemma": "chemin", "en": "path / way", "bn": "পথ / রাস্তা", "pos": "noun"},
    "chemise": {"lemma": "chemise", "en": "shirt / paper folder", "bn": "শার্ট / ফাইল ফোল্ডার", "pos": "noun"},
    "chercher": {"lemma": "chercher", "en": "to look for / fetch", "bn": "খোঁজা / নিয়ে আসা", "pos": "verb"},
    "chiffres": {"lemma": "chiffre", "en": "digits / figures", "bn": "সংখ্যা / ডিজিট", "pos": "noun"},
    "choisi": {"lemma": "choisir", "en": "chosen", "bn": "পছন্দ করেছে", "pos": "verb"},
    "choisir": {"lemma": "choisir", "en": "to choose", "bn": "পছন্দ করা", "pos": "verb"},
    "choisissez": {"lemma": "choisir", "en": "choose (formal)", "bn": "পছন্দ করুন", "pos": "verb"},
    "choisit": {"lemma": "choisir", "en": "chooses", "bn": "পছন্দ করে", "pos": "verb"},
    "cinquantaine": {"lemma": "cinquantaine", "en": "about fifty years old", "bn": "পঞ্চাশোর্ধ্ব / প্রায় পঞ্চাশ", "pos": "noun"},
    "circonscription": {"lemma": "circonscription", "en": "district / area", "bn": "এলাকা / প্রশাসনিক এলাকা", "pos": "noun"},
    "clair": {"lemma": "clair", "en": "clear / bright", "bn": "পরিষ্কার / উজ্জ্বল", "pos": "adjective"},
    "claire": {"lemma": "clair", "en": "clear (feminine)", "bn": "পরিষ্কার / সুস্পষ্ট", "pos": "adjective"},
    "claires": {"lemma": "clair", "en": "clear (plural)", "bn": "সুস্পষ্ট", "pos": "adjective"},
    "clarté": {"lemma": "clarté", "en": "clarity", "bn": "স্পষ্টতা", "pos": "noun"},
    "client": {"lemma": "client", "en": "customer / client", "bn": "গ্রাহক", "pos": "noun"},
    "clientèle": {"lemma": "clientèle", "en": "clientele / customers", "bn": "গ্রাহকবৃন্দ", "pos": "noun"},
    "clients": {"lemma": "client", "en": "customers", "bn": "গ্রাহকগণ", "pos": "noun"},
    "clé": {"lemma": "clé", "en": "key", "bn": "চাবি", "pos": "noun"},
    "code": {"lemma": "code", "en": "PIN code / rule", "bn": "কোড / পিন নম্বর", "pos": "noun"},
    "codes": {"lemma": "code", "en": "codes / social norms", "bn": "নিয়মাবলী / অলিখিত নিয়ম", "pos": "noun"},
    "code-barres": {"lemma": "code-barres", "en": "barcode", "bn": "বারকোড", "pos": "noun"},
    "codebarres": {"lemma": "code-barres", "en": "barcode", "bn": "বারকোড", "pos": "noun"},
    "cœur": {"lemma": "cœur", "en": "heart", "bn": "হৃদয় / মন", "pos": "noun"},
    "coeur": {"lemma": "cœur", "en": "heart", "bn": "হৃদয় / মন", "pos": "noun"},
    "collègue": {"lemma": "collègue", "en": "colleague", "bn": "সহকর্মী", "pos": "noun"},
    "collègues": {"lemma": "collègue", "en": "colleagues", "bn": "সহকর্মীবৃন্দ", "pos": "noun"},
    "collectif": {"lemma": "collectif", "en": "collective / communal", "bn": "সম্মিলিত / কেন্দ্রীয়", "pos": "adjective"},
    "commander": {"lemma": "commander", "en": "to order (food)", "bn": "অর্ডার করা", "pos": "verb"},
    "commence": {"lemma": "commencer", "en": "starts / begins", "bn": "শুরু হয়", "pos": "verb"},
    "commencer": {"lemma": "commencer", "en": "to start / begin", "bn": "শুরু করা", "pos": "verb"},
    "commercial": {"lemma": "commercial", "en": "sales / commercial", "bn": "বাণিজ্যিক / বিক্রয় প্রতিনিধি", "pos": "adjective"},
    "communes": {"lemma": "commun", "en": "shared / common (parts)", "bn": "সাধারণ / সবার ব্যবহার্য", "pos": "adjective"},
    "communication": {"lemma": "communication", "en": "communication", "bn": "যোগাযোগ", "pos": "noun"},
    "comparabilité": {"lemma": "comparabilité", "en": "comparability (diploma recognition)", "bn": "সমতাকরণ / সমমান", "pos": "noun"},
    "compare": {"lemma": "comparer", "en": "compares", "bn": "তুলনা করে", "pos": "verb"},
    "compose": {"lemma": "composer", "en": "dials (a phone number)", "bn": "ডায়াল করে", "pos": "verb"},
    "complet": {"lemma": "complet", "en": "complete / full", "bn": "সম্পূর্ণ", "pos": "adjective"},
    "complète": {"lemma": "complet", "en": "complete (feminine)", "bn": "সম্পূর্ণ", "pos": "adjective"},
    "comportement": {"lemma": "comportement", "en": "behaviour", "bn": "আচরণ", "pos": "noun"},
    "comprendre": {"lemma": "comprendre", "en": "to understand", "bn": "বোঝা", "pos": "verb"},
    "comprend": {"lemma": "comprendre", "en": "includes / understands", "bn": "অন্তর্ভুক্ত করে / বোঝে", "pos": "verb"},
    "comprises": {"lemma": "comprendre", "en": "included (charges comprises)", "bn": "অন্তর্ভুক্ত", "pos": "adjective"},
    "comprimé": {"lemma": "comprimé", "en": "tablet / pill", "bn": "ট্যাবলেট / বড়ি", "pos": "noun"},
    "compte": {"lemma": "compte", "en": "bank account / count", "bn": "অ্যাকাউন্ট / হিসাব", "pos": "noun"},
    "comptoir": {"lemma": "comptoir", "en": "counter", "bn": "কাউন্টার", "pos": "noun"},
    "compétences": {"lemma": "compétence", "en": "skills / competencies", "bn": "দক্ষতা", "pos": "noun"},
    "conduit": {"lemma": "conduire", "en": "leads / guides", "bn": "নিয়ে যায় / পরিচালনা করে", "pos": "verb"},
    "confidentiel": {"lemma": "confidentiel", "en": "confidential", "bn": "গোপনীয়", "pos": "adjective"},
    "configurer": {"lemma": "configurer", "en": "to configure / set up", "bn": "কনফিগার করা / সেটআপ করা", "pos": "verb"},
    "confiance": {"lemma": "confiance", "en": "confidence / trust", "bn": "আত্মবিশ্বাস / ভরসা", "pos": "noun"},
    "conforme": {"lemma": "conforme", "en": "compliant / conforming", "bn": "যথাযথ / মানসম্মত", "pos": "adjective"},
    "conformes": {"lemma": "conforme", "en": "compliant (plural)", "bn": "যথাযথ", "pos": "adjective"},
    "connaissance": {"lemma": "connaissance", "en": "acquaintance / knowledge", "bn": "পরিচয় / জ্ঞান", "pos": "noun"},
    "connaissances": {"lemma": "connaissance", "en": "knowledge / expertise", "bn": "জ্ঞান / অভিজ্ঞতা", "pos": "noun"},
    "conquis": {"lemma": "conquérir", "en": "won over / impressed", "bn": "মুগ্ধ / সন্তুষ্ট", "pos": "adjective"},
    "conseil": {"lemma": "conseil", "en": "advice / tip", "bn": "পরামর্শ / উপদেশ", "pos": "noun"},
    "conseille": {"lemma": "conseiller", "en": "advises / recommends", "bn": "পরামর্শ দেয়", "pos": "verb"},
    "conseiller": {"lemma": "conseiller", "en": "advisor / counselor", "bn": "পরামর্শক / কর্মকর্তা", "pos": "noun"},
    "conseillère": {"lemma": "conseiller", "en": "advisor (female)", "bn": "পরামর্শক (মহিলা)", "pos": "noun"},
    "conseils": {"lemma": "conseil", "en": "advice / tips", "bn": "পরামর্শসমূহ", "pos": "noun"},
    "consulte": {"lemma": "consulter", "en": "checks / consults", "bn": "দেখে / পরামর্শ নেয়", "pos": "verb"},
    "consultation": {"lemma": "consultation", "en": "medical consultation / visit", "bn": "চিকিৎসা পরামর্শ / ভিজিট", "pos": "noun"},
    "contact": {"lemma": "contact", "en": "contact", "bn": "যোগাযোগ", "pos": "noun"},
    "contacter": {"lemma": "contacter", "en": "to contact", "bn": "যোগাযোগ করা", "pos": "verb"},
    "contacterons": {"lemma": "contacter", "en": "will contact (future)", "bn": "যোগাযোগ করব", "pos": "verb"},
    "contient": {"lemma": "contenir", "en": "contains", "bn": "ধারণ করে / রয়েছে", "pos": "verb"},
    "contrat": {"lemma": "contrat", "en": "contract / agreement", "bn": "চুক্তিপত্র", "pos": "noun"},
    "contrôle": {"lemma": "contrôler", "en": "checks / inspects", "bn": "পরীক্ষা করে", "pos": "verb"},
    "convention": {"lemma": "convention", "en": "agreement / convention", "bn": "চুক্তি / সনদ", "pos": "noun"},
    "convivial": {"lemma": "convivial", "en": "convivial / friendly", "bn": "আন্তরিক / প্রফুল্ল", "pos": "adjective"},
    "conviviale": {"lemma": "convivial", "en": "friendly / cozy (feminine)", "bn": "আন্তরিক ও প্রফুল্ল", "pos": "adjective"},
    "convoqué": {"lemma": "convoquer", "en": "summoned / invited", "bn": "আমন্ত্রিত / তলব করা", "pos": "adjective"},
    "copies": {"lemma": "copie", "en": "photocopies / copies", "bn": "ফটোকপি / অনুলিপি", "pos": "noun"},
    "corps": {"lemma": "corps", "en": "body", "bn": "শরীর / দেহ", "pos": "noun"},
    "correspond": {"lemma": "correspondre", "en": "matches / corresponds", "bn": "মিলে যায় / মানানসই হয়", "pos": "verb"},
    "coule": {"lemma": "couler", "en": "pours / flows", "bn": "পড়ে / প্রবাহিত হয়", "pos": "verb"},
    "couloir": {"lemma": "couloir", "en": "corridor / hallway", "bn": "করিডোর / বারান্দা", "pos": "noun"},
    "cour": {"lemma": "cour", "en": "courtyard", "bn": "আঙিনা / উঠান", "pos": "noun"},
    "courant": {"lemma": "courant", "en": "current (account) / everyday", "bn": "চলতি (হিসাব) / সাধারণ", "pos": "adjective"},
    "couramment": {"lemma": "couramment", "en": "commonly / fluently", "bn": "সাধারণভাবে / সাবলীলভাবে", "pos": "adverb"},
    "cours": {"lemma": "cours", "en": "class / course / in progress", "bn": "ক্লাস / কোর্স / চলমান", "pos": "noun"},
    "courrier": {"lemma": "courrier", "en": "mail / letters", "bn": "চিঠিপত্র / ডাক", "pos": "noun"},
    "croix": {"lemma": "croix", "en": "cross", "bn": "ক্রস চিহ্ন", "pos": "noun"},
    "cuillère": {"lemma": "cuillère", "en": "spoon / spoonful", "bn": "চামচ / এক চামচ", "pos": "noun"},
    "cuisine": {"lemma": "cuisine", "en": "kitchen", "bn": "রান্নাঘর", "pos": "noun"},
    "cuisson": {"lemma": "cuisson", "en": "cooking", "bn": "রান্না", "pos": "noun"},
    "cursus": {"lemma": "cursus", "en": "degree program / curriculum", "bn": "শিক্ষাক্রম / পাঠ্যক্রম", "pos": "noun"},
    "curriculum": {"lemma": "curriculum vitae", "en": "curriculum (CV)", "bn": "সিভি / জীবনবৃত্তান্ত", "pos": "noun"},
}

print(f"Loaded Lexicon A-C: {len(LEXICON_A_C)} entries.")
