# -*- coding: utf-8 -*-
"""
Lexicon Part 4: S through Z
"""

LEXICON_S_Z = {
    # S
    "sachet": {"lemma": "sachet", "en": "bag / pouch", "bn": "ছোট ব্যাগ / প্যাকেট", "pos": "noun"},
    "sac": {"lemma": "sac", "en": "bag / backpack", "bn": "ব্যাগ / থলে", "pos": "noun"},
    "sacs": {"lemma": "sac", "en": "bags", "bn": "ব্যাগগুলো", "pos": "noun"},
    "saison": {"lemma": "saison", "en": "season", "bn": "ঋতু / মৌসুম", "pos": "noun"},
    "salaire": {"lemma": "salaire", "en": "salary / wages", "bn": "বেতন", "pos": "noun"},
    "salle": {"lemma": "salle", "en": "room / hall", "bn": "কক্ষ / রুম", "pos": "noun"},
    "salutations": {"lemma": "salutation", "en": "greetings", "bn": "অভিবাদন / সম্ভাষণ", "pos": "noun"},
    "samedi": {"lemma": "samedi", "en": "Saturday", "bn": "শনিবার", "pos": "noun"},
    "sandwich": {"lemma": "sandwich", "en": "sandwich", "bn": "স্যান্ডউইচ", "pos": "noun"},
    "sandwichs": {"lemma": "sandwich", "en": "sandwiches", "bn": "স্যান্ডউইচসমূহ", "pos": "noun"},
    "santé": {"lemma": "santé", "en": "health", "bn": "স্বাস্থ্য", "pos": "noun"},
    "savoureuse": {"lemma": "savoureux", "en": "tasty / flavourful", "bn": "সুস্বাদু", "pos": "adjective"},
    "scolaire": {"lemma": "scolaire", "en": "school / academic", "bn": "বিদ্যালয় সংক্রান্ত", "pos": "adjective"},
    "sciences": {"lemma": "science", "en": "sciences", "bn": "বিজ্ঞান", "pos": "noun"},
    "scrupuleusement": {"lemma": "scrupuleusement", "en": "scrupulously / thoroughly", "bn": "পুঙ্খানুপুঙ্খভাবে", "pos": "adverb"},
    "second": {"lemma": "second", "en": "second", "bn": "দ্বিতীয়", "pos": "adjective"},
    "secrétariat": {"lemma": "secrétariat", "en": "secretariat / administration office", "bn": "সেক্রেটারিয়েট / প্রশাসনিক দপ্তর", "pos": "noun"},
    "secteur": {"lemma": "secteur", "en": "sector / industry", "bn": "খাত / সেক্টর", "pos": "noun"},
    "semaine": {"lemma": "semaine", "en": "week", "bn": "সপ্তাহ", "pos": "noun"},
    "semaines": {"lemma": "semaine", "en": "weeks", "bn": "সপ্তাহসমূহ", "pos": "noun"},
    "semestre": {"lemma": "semestre", "en": "semester / term", "bn": "সেমিস্টার", "pos": "noun"},
    "sentiment": {"lemma": "sentiment", "en": "feeling / sense", "bn": "অনুভূতি / বোধ", "pos": "noun"},
    "sentir": {"lemma": "sentir", "en": "to feel", "bn": "অনুভব করা", "pos": "verb"},
    "sent": {"lemma": "sentir", "en": "feels", "bn": "অনুভব করে", "pos": "verb"},
    "serre": {"lemma": "serrer", "en": "shakes (hand)", "bn": "হাতে হাত মেলায়", "pos": "verb"},
    "serveur": {"lemma": "serveur", "en": "waiter / server", "bn": "ওয়েটার / পরিবেশক", "pos": "noun"},
    "services": {"lemma": "service", "en": "services", "bn": "সেবাসমূহ", "pos": "noun"},
    "seul": {"lemma": "seul", "en": "alone / single", "bn": "একা", "pos": "adjective"},
    "signe": {"lemma": "signe", "en": "sign / signal", "bn": "ইশারা / সংকেত", "pos": "noun"},
    "signer": {"lemma": "signer", "en": "to sign", "bn": "স্বাক্ষর করা", "pos": "verb"},
    "signé": {"lemma": "signer", "en": "signed", "bn": "স্বাক্ষর করেছে", "pos": "verb"},
    "silence": {"lemma": "silence", "en": "silence", "bn": "নীরবতা", "pos": "noun"},
    "silencieusement": {"lemma": "silencieusement", "en": "silently", "bn": "নীরবে", "pos": "adverb"},
    "sim": {"lemma": "SIM", "en": "SIM card", "bn": "সিম কার্ড", "pos": "noun"},
    "simple": {"lemma": "simple", "en": "simple / easy", "bn": "সহজ / সাধারণ", "pos": "adjective"},
    "simples": {"lemma": "simple", "en": "simple (plural)", "bn": "সহজ", "pos": "adjective"},
    "simplicité": {"lemma": "simplicité", "en": "simplicity", "bn": "সরলতা / অনাড়ম্বর", "pos": "noun"},
    "sincèrement": {"lemma": "sincèrement", "en": "sincerely", "bn": "আন্তরিকভাবে", "pos": "adverb"},
    "sirop": {"lemma": "sirop", "en": "cough syrup", "bn": "কাশির সিরাপ", "pos": "noun"},
    "site": {"lemma": "site", "en": "website / site", "bn": "ওয়েবসাইট", "pos": "noun"},
    "situation": {"lemma": "situation", "en": "situation / circumstances", "bn": "পরিস্থিতি / অবস্থা", "pos": "noun"},
    "située": {"lemma": "situer", "en": "located / situated", "bn": "অবস্থিত", "pos": "adjective"},
    "smartphone": {"lemma": "smartphone", "en": "smartphone", "bn": "স্মার্টফোন", "pos": "noun"},
    "société": {"lemma": "société", "en": "company / society", "bn": "কোম্পানি / সমাজ", "pos": "noun"},
    "soignée": {"lemma": "soigner", "en": "neat / tidy (folder)", "bn": "পরিপাটি / যত্নসহকারে তৈরি", "pos": "adjective"},
    "soignez": {"lemma": "soigner", "en": "take care / get well (soignez-vous)", "bn": "নিজের যত্ন নিন", "pos": "verb"},
    "soignez-vous": {"lemma": "soigner", "en": "take care / get well", "bn": "নিজের যত্ন নিন", "pos": "verb"},
    "soir": {"lemma": "soir", "en": "evening", "bn": "সন্ধ্যা / রাত", "pos": "noun"},
    "soirs": {"lemma": "soir", "en": "evenings", "bn": "সন্ধ্যাগুলো", "pos": "noun"},
    "solide": {"lemma": "solide", "en": "solid / sturdy", "bn": "শক্তিশালী / মজবুত", "pos": "adjective"},
    "solides": {"lemma": "solide", "en": "solid (plural)", "bn": "মজবুত", "pos": "adjective"},
    "solution": {"lemma": "solution", "en": "solution", "bn": "সমাধান", "pos": "noun"},
    "somnifères": {"lemma": "somnifère", "en": "sleeping pills", "bn": "ঘুমের ওষুধ", "pos": "noun"},
    "sonne": {"lemma": "sonner", "en": "rings / sounds", "bn": "বেজে ওঠে", "pos": "verb"},
    "souhaiter": {"lemma": "souhaiter", "en": "to wish", "bn": "কামনা করা / শুভেচ্ছা জানানো", "pos": "verb"},
    "souhaite": {"lemma": "souhaiter", "en": "wishes / desires", "bn": "কামনা করে / চায়", "pos": "verb"},
    "sourd": {"lemma": "sourd", "en": "deep (rumble) / deaf", "bn": "গম্ভীর (আওয়াজ) / বধির", "pos": "adjective"},
    "souffre": {"lemma": "souffrir", "en": "suffers", "bn": "কষ্ট পাচ্ছে / ভুগছে", "pos": "verb"},
    "sous-préfecture": {"lemma": "sous-préfecture", "en": "sub-prefecture", "bn": "সাব-প্রিফেকচার (প্রশাসনিক কার্যালয়)", "pos": "noun"},
    "souspréfecture": {"lemma": "sous-préfecture", "en": "sub-prefecture", "bn": "সাব-প্রিফেকচার", "pos": "noun"},
    "sous-sol": {"lemma": "sous-sol", "en": "basement", "bn": "বেজমেন্ট / ভূগর্ভস্থ তলা", "pos": "noun"},
    "soussol": {"lemma": "sous-sol", "en": "basement", "bn": "বেজমেন্ট", "pos": "noun"},
    "soutien": {"lemma": "soutien", "en": "support", "bn": "সমর্থন / সহায়তা", "pos": "noun"},
    "spontanée": {"lemma": "spontané", "en": "spontaneous", "bn": "স্বতঃস্ফূর্ত", "pos": "adjective"},
    "sport": {"lemma": "sport", "en": "sport / exercise", "bn": "খেলাধুলা / ব্যায়াম", "pos": "noun"},
    "spécialisé": {"lemma": "spécialiser", "en": "specialized", "bn": "বিশেষায়িত", "pos": "adjective"},
    "stéthoscope": {"lemma": "stéthoscope", "en": "stethoscope", "bn": "স্টেথোস্কোপ", "pos": "noun"},
    "studio": {"lemma": "studio", "en": "studio flat", "bn": "স্টুডিও অ্যাপার্টমেন্ট", "pos": "noun"},
    "sucre": {"lemma": "sucre", "en": "sugar", "bn": "চিনি", "pos": "noun"},
    "sucré": {"lemma": "sucré", "en": "sweet / sugary", "bn": "মিষ্টি", "pos": "adjective"},
    "supermarché": {"lemma": "supermarché", "en": "supermarket", "bn": "সুপারমার্কেট", "pos": "noun"},
    "support": {"lemma": "support", "en": "support (IT)", "bn": "আইটি সহায়তা / সাপোর্ট", "pos": "noun"},
    "système": {"lemma": "système", "en": "system / operating system", "bn": "সিস্টেম / অপারেটিং সিস্টেম", "pos": "noun"},
    "systèmes": {"lemma": "système", "en": "systems", "bn": "সিস্টেমসমূহ", "pos": "noun"},
    "sécurité": {"lemma": "sécurité", "en": "security", "bn": "নিরাপত্তা", "pos": "noun"},
    "sécurisé": {"lemma": "sécuriser", "en": "secure", "bn": "সুরক্ষিত", "pos": "adjective"},
    "sécurisée": {"lemma": "sécuriser", "en": "secured / secure (feminine)", "bn": "সুরক্ষিত", "pos": "adjective"},
    "séjour": {"lemma": "séjour", "en": "residence / stay (permit)", "bn": "বসবাস / অবস্থান (পারমিট)", "pos": "noun"},
    "sélectif": {"lemma": "sélectif", "en": "selective (recycling)", "bn": "বাছাইকরণ (রিসাইক্লিং)", "pos": "adjective"},
    "sérieux": {"lemma": "sérieux", "en": "seriousness / reliability", "bn": "দায়িত্বশীলতা / আন্তরিকতা", "pos": "noun"},
    "sérénité": {"lemma": "sérénité", "en": "serenity", "bn": "প্রশান্তি", "pos": "noun"},
    "serein": {"lemma": "serein", "en": "serene / confident", "bn": "নিশ্চিন্ত / প্রশান্ত", "pos": "adjective"},

    # T
    "t+": {"lemma": "t+", "en": "metro ticket t+", "bn": "মেট্রো টিকেট টি প্লাস", "pos": "noun", "ttsText": "Ticket té plus"},
    "table": {"lemma": "table", "en": "table", "bn": "টেবিল", "pos": "noun"},
    "tables": {"lemma": "table", "en": "tables", "bn": "টেবিলগুলো", "pos": "noun"},
    "tablette": {"lemma": "tablette", "en": "tablet computer", "bn": "ট্যাবলেট কম্পিউটার", "pos": "noun"},
    "tactile": {"lemma": "tactile", "en": "touch (screen)", "bn": "স্পর্শকাতর / টাচস্ক্রিন", "pos": "adjective"},
    "tamponne": {"lemma": "tamponner", "en": "stamps (seal)", "bn": "সিলমোহর মারে", "pos": "verb"},
    "tape": {"lemma": "taper", "en": "types / keys in", "bn": "টাইপ করে", "pos": "verb"},
    "technicien": {"lemma": "technicien", "en": "technician", "bn": "টেকনিশিয়ান / কারিগরি কর্মী", "pos": "noun"},
    "technique": {"lemma": "technique", "en": "technical / technique", "bn": "কারিগরি / টেকনিক্যাল", "pos": "adjective"},
    "techniques": {"lemma": "technique", "en": "technical (plural)", "bn": "কারিগরি", "pos": "adjective"},
    "technologique": {"lemma": "technologique", "en": "technological", "bn": "প্রযুক্তিগত", "pos": "adjective"},
    "technologiques": {"lemma": "technologique", "en": "technology (companies)", "bn": "প্রযুক্তিগত", "pos": "adjective"},
    "technologie": {"lemma": "technologie", "en": "technology", "bn": "প্রযুক্তি", "pos": "noun"},
    "température": {"lemma": "température", "en": "temperature", "bn": "তাপমাত্রা", "pos": "noun"},
    "temps": {"lemma": "temps", "en": "time / weather / real-time", "bn": "সময় / আবহাওয়া", "pos": "noun"},
    "tend": {"lemma": "tendre", "en": "hands over / extends", "bn": "বাড়িয়ে দেয় / এগিয়ে দেয়", "pos": "verb"},
    "tendre": {"lemma": "tendre", "en": "tender / soft", "bn": "নরম / কোমল", "pos": "adjective"},
    "terminal": {"lemma": "terminal", "en": "payment terminal / terminal", "bn": "পেমেন্ট টার্মিনাল / যন্ত্র", "pos": "noun"},
    "terminer": {"lemma": "terminer", "en": "to finish", "bn": "শেষ করা", "pos": "verb"},
    "terminons": {"lemma": "terminer", "en": "finish (nous)", "bn": "শেষ করছি", "pos": "verb"},
    "territoire": {"lemma": "territoire", "en": "territory / jurisdiction", "bn": "এলাকা", "pos": "noun"},
    "test": {"lemma": "test", "en": "test / trial", "bn": "পরীক্ষা", "pos": "noun"},
    "thé": {"lemma": "thé", "en": "tea", "bn": "চা", "pos": "noun"},
    "ticket": {"lemma": "ticket", "en": "ticket / token", "bn": "টিকিট / টোকেন", "pos": "noun"},
    "tiède": {"lemma": "tiède", "en": "lukewarm / warm", "bn": "কুসুম গরম", "pos": "adjective"},
    "tiroirs": {"lemma": "tiroir", "en": "drawers", "bn": "ড্রয়ারসমূহ", "pos": "noun"},
    "titre": {"lemma": "titre", "en": "transport ticket / title / permit", "bn": "টিকিট / কার্ড / শিরোনাম", "pos": "noun"},
    "toile": {"lemma": "toile", "en": "canvas / fabric", "bn": "ক্যানভাস কাপড়ের তৈরি", "pos": "noun"},
    "toit": {"lemma": "toit", "en": "roof", "bn": "ছাদ", "pos": "noun"},
    "tonalité": {"lemma": "tonalité", "en": "dial tone / ringtone", "bn": "রিংটোন / ডায়াল টোন", "pos": "noun"},
    "torréfié": {"lemma": "torréfier", "en": "roasted (coffee)", "bn": "রোস্ট করা (কফির সুবাস)", "pos": "adjective"},
    "torréfiée": {"lemma": "torréfier", "en": "roasted (feminine)", "bn": "রোস্ট করা", "pos": "adjective"},
    "touché": {"lemma": "toucher", "en": "touched / moved emotionally", "bn": "অভিভূত / আবেগাপ্লুত", "pos": "adjective"},
    "tour": {"lemma": "tour", "en": "turn (waiting turn)", "bn": "পালা / সিরিয়াল", "pos": "noun"},
    "tousse": {"lemma": "tousser", "en": "coughs", "bn": "কাশি দেয়", "pos": "verb"},
    "toux": {"lemma": "toux", "en": "cough", "bn": "কাশি", "pos": "noun"},
    "traduction": {"lemma": "traduction", "en": "translation", "bn": "অনুবাদ", "pos": "noun"},
    "train": {"lemma": "train", "en": "train", "bn": "ট্রেন", "pos": "noun"},
    "traitant": {"lemma": "traitant", "en": "attending / family doctor (médecin traitant)", "bn": "পারিবারিক নিয়মিত চিকিৎসক", "pos": "adjective"},
    "trajet": {"lemma": "trajet", "en": "journey / route", "bn": "যাত্রা / পথ", "pos": "noun"},
    "transparent": {"lemma": "transparent", "en": "transparent / clear", "bn": "স্বচ্ছ", "pos": "adjective"},
    "transmettre": {"lemma": "transmettre", "en": "to transmit / hand over", "bn": "জমা দেওয়া / পাঠানো", "pos": "verb"},
    "transport": {"lemma": "transport", "en": "transportation", "bn": "যাতায়াত / পরিবহন", "pos": "noun"},
    "transports": {"lemma": "transport", "en": "public transportation", "bn": "গণপরিবহন", "pos": "noun"},
    "travail": {"lemma": "travail", "en": "work / job", "bn": "কাজ / চাকরি", "pos": "noun"},
    "travailler": {"lemma": "travailler", "en": "to work", "bn": "কাজ করা", "pos": "verb"},
    "travaille": {"lemma": "travailler", "en": "works", "bn": "কাজ করে", "pos": "verb"},
    "travaux": {"lemma": "travail", "en": "lab work / hands-on sessions (TP)", "bn": "বাস্তব কাজ / ল্যাব প্র্যাকটিক্যাল", "pos": "noun"},
    "tri": {"lemma": "tri", "en": "sorting / recycling", "bn": "বাছাইকরণ / রিসাইক্লিং", "pos": "noun"},
    "trouver": {"lemma": "trouver", "en": "to find", "bn": "খুঁজে পাওয়া", "pos": "verb"},
    "trouve": {"lemma": "trouver", "en": "finds", "bn": "পায়", "pos": "verb"},
    "trouvé": {"lemma": "trouver", "en": "found", "bn": "পেয়েছে", "pos": "verb"},
    "téléphone": {"lemma": "téléphone", "en": "telephone / mobile phone", "bn": "টেলিফোন / ফোন", "pos": "noun"},
    "téléphonie": {"lemma": "téléphonie", "en": "telephony / mobile telecoms", "bn": "টেলিযোগাযোগ", "pos": "noun"},
    "téléphonique": {"lemma": "téléphonique", "en": "telephone (line)", "bn": "টেলিফোন সংক্রান্ত", "pos": "adjective"},
    "tête": {"lemma": "tête", "en": "head / headache", "bn": "মাথা / মাথা ব্যথা", "pos": "noun"},

    # U & V & W
    "urgente": {"lemma": "urgent", "en": "urgent (feminine)", "bn": "জরুরি", "pos": "adjective"},
    "usagers": {"lemma": "usager", "en": "service users / citizens", "bn": "সেবাগ্রহীতা / নাগরিক", "pos": "noun"},
    "usage": {"lemma": "usage", "en": "customary / usage (d'usage)", "bn": "প্রচলিত রীতি / ব্যবহার", "pos": "noun"},
    "utilisateur": {"lemma": "utilisateur", "en": "user (IT user)", "bn": "ব্যবহারকারী", "pos": "noun"},
    "utilisateurs": {"lemma": "utilisateur", "en": "users", "bn": "ব্যবহারকারীগণ", "pos": "noun"},
    "utilise": {"lemma": "utiliser", "en": "uses", "bn": "ব্যবহার করে", "pos": "verb"},
    "utile": {"lemma": "utile", "en": "useful", "bn": "দরকারী / উপকারী", "pos": "adjective"},
    "utiles": {"lemma": "utile", "en": "useful (plural)", "bn": "দরকারী", "pos": "adjective"},
    "universitaire": {"lemma": "universitaire", "en": "university (campus/studies)", "bn": "বিশ্ববিদ্যালয় সংক্রান্ত", "pos": "adjective"},
    "vacances": {"lemma": "vacances", "en": "holidays / vacation", "bn": "ছুটি", "pos": "noun"},
    "valable": {"lemma": "valable", "en": "valid", "bn": "বৈধ / মেয়াদযুক্ত", "pos": "adjective"},
    "valide": {"lemma": "valider", "en": "validates / valid", "bn": "অনুমোদন করে / বৈধ", "pos": "verb"},
    "valider": {"lemma": "valider", "en": "to validate / confirm", "bn": "অনুমোদন করা / নিশ্চিত করা", "pos": "verb"},
    "validité": {"lemma": "validité", "en": "validity", "bn": "বৈধতা / মেয়াদ", "pos": "noun"},
    "valoriser": {"lemma": "valoriser", "en": "to enhance / showcase (skills)", "bn": "মর্যাদা বৃদ্ধি করা / কাজে লাগানো", "pos": "verb"},
    "vaste": {"lemma": "vaste", "en": "vast / spacious", "bn": "বিশাল / প্রশস্ত", "pos": "adjective"},
    "vendeur": {"lemma": "vendeur", "en": "salesperson / clerk", "bn": "বিক্রেতা", "pos": "noun"},
    "venir": {"lemma": "venir", "en": "to come", "bn": "আসা", "pos": "verb"},
    "viens": {"lemma": "venir", "en": "come / have just (vient de)", "bn": "আসি / এইমাত্র", "pos": "verb"},
    "vient": {"lemma": "venir", "en": "comes / has just (vient de)", "bn": "আসে / এইমাত্র", "pos": "verb"},
    "venez": {"lemma": "venir", "en": "come (imperative/formal)", "bn": "আসুন", "pos": "verb"},
    "vent": {"lemma": "vent", "en": "wind", "bn": "বাতাস", "pos": "noun"},
    "verdoyant": {"lemma": "verdoyant", "en": "green / lush", "bn": "সবুজ ঘেরা", "pos": "adjective"},
    "verre": {"lemma": "verre", "en": "glass", "bn": "কাঁচ / গ্লাস", "pos": "noun"},
    "versement": {"lemma": "versement", "en": "payment / deposit (wages)", "bn": "টাকা জমা / বেতন প্রদান", "pos": "noun"},
    "vert": {"lemma": "vert", "en": "green", "bn": "সবুজ", "pos": "adjective"},
    "verte": {"lemma": "vert", "en": "green (feminine)", "bn": "সবুজ", "pos": "adjective"},
    "vertes": {"lemma": "vert", "en": "green (plural)", "bn": "সবুজ", "pos": "adjective"},
    "veste": {"lemma": "veste", "en": "jacket", "bn": "জ্যাকেট / কোট", "pos": "noun"},
    "viande": {"lemma": "viande", "en": "meat", "bn": "মাংস", "pos": "noun"},
    "vidéo": {"lemma": "vidéo", "en": "video", "bn": "ভিডিও", "pos": "noun"},
    "vie": {"lemma": "vie", "en": "life", "bn": "জীবন", "pos": "noun"},
    "ville": {"lemma": "ville", "en": "city / town", "bn": "শহর", "pos": "noun"},
    "virement": {"lemma": "virement", "en": "bank transfer", "bn": "ব্যাংক ট্রান্সফার", "pos": "noun"},
    "virements": {"lemma": "virement", "en": "bank transfers", "bn": "ব্যাংক ট্রান্সফারসমূহ", "pos": "noun"},
    "virale": {"lemma": "viral", "en": "viral (infection)", "bn": "ভাইরাল", "pos": "adjective"},
    "visa": {"lemma": "visa", "en": "visa / entry permit", "bn": "ভিসা", "pos": "noun"},
    "visiblement": {"lemma": "visiblement", "en": "visibly / clearly", "bn": "দৃশ্যমানভাবে / স্পষ্টতই", "pos": "adverb"},
    "visite": {"lemma": "visite", "en": "visit / property viewing", "bn": "পরিদর্শন / দেখা", "pos": "noun"},
    "visiter": {"lemma": "visiter", "en": "to visit", "bn": "পরিদর্শন করা", "pos": "verb"},
    "visuel": {"lemma": "visuel", "en": "visual", "bn": "দৃষ্টিগোচর / চাক্ষুষ", "pos": "adjective"},
    "vitale": {"lemma": "vital", "en": "vital (carte Vitale: French healthcare card)", "bn": "ফরাসি স্বাস্থ্যসেবা কার্ড", "pos": "adjective"},
    "vitrage": {"lemma": "vitrage", "en": "glazing (double vitrage)", "bn": "কাঁচের জানালা (ডাবল গ্লেজিং)", "pos": "noun"},
    "vitrée": {"lemma": "vitré", "en": "glass / glazed (office)", "bn": "কাঁচের তৈরি", "pos": "adjective"},
    "vitrées": {"lemma": "vitré", "en": "glass (doors)", "bn": "কাঁচের তৈরি", "pos": "adjective"},
    "vitré": {"lemma": "vitré", "en": "glass (counter)", "bn": "কাঁচের", "pos": "adjective"},
    "voisin": {"lemma": "voisin", "en": "neighbour (masculine)", "bn": "প্রতিবেশী", "pos": "noun"},
    "voisine": {"lemma": "voisin", "en": "neighbour (female) / neighbouring", "bn": "প্রতিবেশী", "pos": "noun"},
    "voiture": {"lemma": "voiture", "en": "car", "bn": "গাড়ি", "pos": "noun"},
    "voix": {"lemma": "voix", "en": "voice", "bn": "কণ্ঠ / আওয়াজ", "pos": "noun"},
    "volet": {"lemma": "volet", "en": "aspect / section / component", "bn": "দিক / অংশ", "pos": "noun"},
    "vouloir": {"lemma": "vouloir", "en": "to want", "bn": "চাওয়া", "pos": "verb"},
    "veut": {"lemma": "vouloir", "en": "wants", "bn": "চায়", "pos": "verb"},
    "veux": {"lemma": "vouloir", "en": "want (je/tu)", "bn": "চাই / চাও", "pos": "verb"},
    "voudrais": {"lemma": "vouloir", "en": "would like", "bn": "চাই / নিতে চাই", "pos": "verb"},
    "voulez": {"lemma": "vouloir", "en": "want (vous)", "bn": "চান", "pos": "verb"},
    "voyage": {"lemma": "voyage", "en": "journey / trip", "bn": "ভ্রমণ / যাত্রা", "pos": "noun"},
    "voyager": {"lemma": "voyager", "en": "to travel", "bn": "ভ্রমণ করা", "pos": "verb"},
    "vêtus": {"lemma": "vêtir", "en": "dressed / wearing", "bn": "পরিহিত / পোশাক পরা", "pos": "adjective"},
    "vêtu": {"lemma": "vêtir", "en": "dressed", "bn": "পোশাক পরিহিত", "pos": "adjective"},
    "vélos": {"lemma": "vélo", "en": "bicycles / bikes", "bn": "সাইকেলগুলো", "pos": "noun"},
    "vélo": {"lemma": "vélo", "en": "bicycle", "bn": "সাইকেল", "pos": "noun"},
    "vérifie": {"lemma": "vérifier", "en": "checks / verifies", "bn": "যাচাই করে", "pos": "verb"},
    "vérifier": {"lemma": "vérifier", "en": "to check / verify", "bn": "যাচাই করা", "pos": "verb"},
    "windows": {"lemma": "Windows", "en": "Microsoft Windows OS", "bn": "উইন্ডোজ অপারেটিং সিস্টেম", "pos": "noun"},
}

print(f"Loaded Lexicon S-Z: {len(LEXICON_S_Z)} entries.")
