# -*- coding: utf-8 -*-
"""
Lexicon Part 2: D through L
"""

LEXICON_D_L = {
    # D
    "dame": {"lemma": "dame", "en": "lady / woman", "bn": "ভদ্রমহিলা", "pos": "noun"},
    "demande": {"lemma": "demande", "en": "request / application", "bn": "অনুরোধ / আবেদন", "pos": "noun"},
    "demander": {"lemma": "demander", "en": "to ask", "bn": "জিজ্ঞেস করা / চাওয়া", "pos": "verb"},
    "demi": {"lemma": "demi", "en": "half", "bn": "অর্ধেক", "pos": "adjective"},
    "demie": {"lemma": "demi", "en": "half (hour)", "bn": "আধ / সাড়ে", "pos": "adjective"},
    "demi-journées": {"lemma": "demi-journée", "en": "half-days", "bn": "অর্ধ-দিবস", "pos": "noun"},
    "demijournées": {"lemma": "demi-journée", "en": "half-days", "bn": "অর্ধ-দিবস", "pos": "noun"},
    "dent": {"lemma": "dent", "en": "tooth", "bn": "দাঁত", "pos": "noun"},
    "dents": {"lemma": "dent", "en": "teeth", "bn": "দাঁত", "pos": "noun"},
    "descend": {"lemma": "descendre", "en": "goes down", "bn": "নেমে যায়", "pos": "verb"},
    "descendre": {"lemma": "descendre", "en": "to go down", "bn": "নামা", "pos": "verb"},
    "dessous": {"lemma": "dessous", "en": "below / underneath", "bn": "নিচে", "pos": "adverb"},
    "dessus": {"lemma": "dessus", "en": "above / on top", "bn": "উপরে", "pos": "adverb"},
    "diagnostic": {"lemma": "diagnostic", "en": "diagnosis", "bn": "রোগ নির্ণয় / ডায়াগনোসিস", "pos": "noun"},
    "diagnostiquer": {"lemma": "diagnostiquer", "en": "to troubleshoot / diagnose", "bn": "ত্রুটি চিহ্নিত করা / নির্ণয় করা", "pos": "verb"},
    "différentes": {"lemma": "différent", "en": "different (plural)", "bn": "বিভিন্ন / নানা ধরনের", "pos": "adjective"},
    "différents": {"lemma": "différent", "en": "different", "bn": "বিভিন্ন", "pos": "adjective"},
    "diplôme": {"lemma": "diplôme", "en": "diploma / degree", "bn": "সনদ / ডিপ্লোমা", "pos": "noun"},
    "diplômes": {"lemma": "diplôme", "en": "diplomas / degrees", "bn": "সনদসমূহ", "pos": "noun"},
    "dire": {"lemma": "dire", "en": "to say / tell", "bn": "বলা", "pos": "verb"},
    "direction": {"lemma": "direction", "en": "direction", "bn": "দিক / অভিমুখ", "pos": "noun"},
    "directeur": {"lemma": "directeur", "en": "director / manager", "bn": "পরিচালক", "pos": "noun"},
    "discret": {"lemma": "discret", "en": "discreet", "bn": "বিচক্ষণ / শান্ত", "pos": "adjective"},
    "discutent": {"lemma": "discuter", "en": "chat / discuss", "bn": "কথা বলে / আলোচনা করে", "pos": "verb"},
    "disponible": {"lemma": "disponible", "en": "available", "bn": "উপলব্ধ / পাওয়া যায় এমন", "pos": "adjective"},
    "disponibles": {"lemma": "disponible", "en": "available (plural)", "bn": "উপলব্ধ", "pos": "adjective"},
    "distance": {"lemma": "distance", "en": "distance", "bn": "দূরত্ব", "pos": "noun"},
    "débit": {"lemma": "débit", "en": "debit (immediate)", "bn": "ডেবিট", "pos": "noun"},
    "début": {"lemma": "début", "en": "beginning / start", "bn": "শুরু / আরম্ভ", "pos": "noun"},
    "débute": {"lemma": "débuter", "en": "begins / starts", "bn": "শুরু হয়", "pos": "verb"},
    "décaler": {"lemma": "décaler", "en": "to postpone / shift", "bn": "পেছানো / সময় পরিবর্তন", "pos": "verb"},
    "décidé": {"lemma": "décider", "en": "decided", "bn": "সিদ্ধান্ত নিয়েছে", "pos": "verb"},
    "décider": {"lemma": "décider", "en": "to decide", "bn": "সিদ্ধান্ত নেওয়া", "pos": "verb"},
    "découvrir": {"lemma": "découvrir", "en": "to discover / explore", "bn": "আবিষ্কার করা / দেখা", "pos": "verb"},
    "déjeuner": {"lemma": "déjeuner", "en": "lunch / to have lunch", "bn": "দুপুরের খাবার", "pos": "noun"},
    "délicieux": {"lemma": "délicieux", "en": "delicious", "bn": "সুস্বাদু / মজাদার", "pos": "adjective"},
    "département": {"lemma": "département", "en": "department (academic)", "bn": "বিভাগ (বিশ্ববিদ্যালয়)", "pos": "noun"},
    "dépenser": {"lemma": "dépenser", "en": "to spend", "bn": "খরচ করা", "pos": "verb"},
    "dépenses": {"lemma": "dépense", "en": "expenses", "bn": "খরচসমূহ", "pos": "noun"},
    "déposer": {"lemma": "déposer", "en": "to submit / lodge (file)", "bn": "জমা দেওয়া", "pos": "verb"},
    "dépôt": {"lemma": "dépôt", "en": "deposit (account)", "bn": "আমানত / সঞ্চয়", "pos": "noun"},
    "déroulement": {"lemma": "déroulement", "en": "process / sequence / course", "bn": "ধারাবাহিকতা / প্রক্রিয়া", "pos": "noun"},
    "détail": {"lemma": "détail", "en": "detail", "bn": "খুঁটিনাটি / বিশদ", "pos": "noun"},
    "détaillés": {"lemma": "détailler", "en": "detailed (transcripts)", "bn": "বিস্তারিত", "pos": "adjective"},
    "détente": {"lemma": "détente", "en": "relaxation / break", "bn": "বিশ্রাম", "pos": "noun"},
    "déterminé": {"lemma": "déterminer", "en": "determined", "bn": "দৃঢ়সংকল্পবদ্ধ", "pos": "adjective"},
    "détermination": {"lemma": "détermination", "en": "determination", "bn": "দৃঢ় সংকল্প", "pos": "noun"},
    "définitive": {"lemma": "définitif", "en": "final / definitive", "bn": "চূড়ান্ত", "pos": "adjective"},
    "docteur": {"lemma": "docteur", "en": "doctor", "bn": "ডাক্তার", "pos": "noun"},
    "document": {"lemma": "document", "en": "document", "bn": "নথি / দলিল", "pos": "noun"},
    "documents": {"lemma": "document", "en": "documents", "bn": "নথিপত্র", "pos": "noun"},
    "domicile": {"lemma": "domicile", "en": "home / residence", "bn": "বাসস্থান / ঠিকানা", "pos": "noun"},
    "donner": {"lemma": "donner", "en": "to give", "bn": "দেওয়া", "pos": "verb"},
    "donnent": {"lemma": "donner", "en": "overlook / give", "bn": "মুখোমুখি হওয়া / দেওয়া", "pos": "verb"},
    "donnée": {"lemma": "donnée", "en": "data", "bn": "উপাত্ত / ডেটা", "pos": "noun"},
    "données": {"lemma": "donnée", "en": "data (gigabytes)", "bn": "মোবাইল ডেটা / ইন্টারনেট", "pos": "noun"},
    "dormir": {"lemma": "dormir", "en": "to sleep", "bn": "ঘুমানো", "pos": "verb"},
    "dossier": {"lemma": "dossier", "en": "application file / folder", "bn": "ফাইল / আবেদনপত্র", "pos": "noun"},
    "douleur": {"lemma": "douleur", "en": "pain / ache", "bn": "ব্যথা / যন্ত্রণা", "pos": "noun"},
    "doux": {"lemma": "doux", "en": "gentle / sweet / mild", "bn": "মৃদু / মিষ্টি", "pos": "adjective"},
    "dressée": {"lemma": "dresser", "en": "set (table)", "bn": "সাজানো (টেবিল)", "pos": "adjective"},
    "dressées": {"lemma": "dresser", "en": "set (tables plural)", "bn": "সাজানো", "pos": "adjective"},
    "droit": {"lemma": "droit", "en": "straight / right / law", "bn": "সোজা / অধিকার / আইন", "pos": "noun"},
    "durée": {"lemma": "durée", "en": "duration / length", "bn": "মেয়াদ / সময়কাল", "pos": "noun"},
    "délivre": {"lemma": "délivrer", "en": "dispenses / issues", "bn": "প্রদান করে / বের করে", "pos": "verb"},
    "démarche": {"lemma": "démarche", "en": "formal procedure / step", "bn": "প্রশাসনিক প্রক্রিয়া / পদক্ষেপ", "pos": "noun"},
    "démarches": {"lemma": "démarche", "en": "procedures / steps", "bn": "প্রশাসনিক পদক্ষেপসমূহ", "pos": "noun"},

    # E
    "eau": {"lemma": "eau", "en": "water", "bn": "পানি", "pos": "noun"},
    "effet": {"lemma": "effet", "en": "effect / indeed", "bn": "প্রভাব / ফল", "pos": "noun"},
    "effectuer": {"lemma": "effectuer", "en": "to carry out / make (transfer)", "bn": "সম্পন্ন করা / পাঠানো", "pos": "verb"},
    "effectuerez": {"lemma": "effectuer", "en": "will carry out (future)", "bn": "সম্পন্ন করবেন", "pos": "verb"},
    "embauche": {"lemma": "embauche", "en": "hiring / employment", "bn": "চাকরি নিয়োগ / নিয়োগ", "pos": "noun"},
    "emménager": {"lemma": "emménager", "en": "to move in (housing)", "bn": "নতুন বাসায় ওঠা", "pos": "verb"},
    "emménagé": {"lemma": "emménager", "en": "moved in", "bn": "উঠেছে", "pos": "verb"},
    "employé": {"lemma": "employé", "en": "employee", "bn": "কর্মচারী", "pos": "noun"},
    "employeur": {"lemma": "employeur", "en": "employer", "bn": "নিয়োগকর্তা", "pos": "noun"},
    "emploi": {"lemma": "emploi", "en": "job / employment", "bn": "চাকরি / কর্মসংস্থান", "pos": "noun"},
    "encourager": {"lemma": "encourager", "en": "to encourage", "bn": "উৎসাহ দেওয়া", "pos": "verb"},
    "encourageant": {"lemma": "encourager", "en": "encouraging", "bn": "উৎসাহব্যঞ্জক", "pos": "adjective"},
    "engagement": {"lemma": "engagement", "en": "commitment / contract obligation", "bn": "চুক্তিবদ্ধতা / বাধ্যবাধকতা", "pos": "noun"},
    "entendre": {"lemma": "entendre", "en": "to hear", "bn": "শোনা", "pos": "verb"},
    "entend": {"lemma": "entendre", "en": "hears", "bn": "শোনে", "pos": "verb"},
    "enthousiasme": {"lemma": "enthousiasme", "en": "enthusiasm", "bn": "উদ্দীপনা / উৎসাহ", "pos": "noun"},
    "entier": {"lemma": "entier", "en": "whole / entire", "bn": "পুরো / সম্পূর্ণ", "pos": "adjective"},
    "entrent": {"lemma": "entrer", "en": "enter (plural)", "bn": "প্রবেশ করে", "pos": "verb"},
    "entrée": {"lemma": "entrée", "en": "entrance / starter", "bn": "প্রবেশদ্বার", "pos": "noun"},
    "entreprise": {"lemma": "entreprise", "en": "company / enterprise", "bn": "প্রতিষ্ঠান / কোম্পানি", "pos": "noun"},
    "entreprises": {"lemma": "entreprise", "en": "companies", "bn": "কোম্পানিসমূহ", "pos": "noun"},
    "entretien": {"lemma": "entretien", "en": "interview / maintenance", "bn": "ইন্টারভিউ / রক্ষণাবেক্ষণ", "pos": "noun"},
    "entretiens": {"lemma": "entretien", "en": "interviews", "bn": "ইন্টারভিউগুলো", "pos": "noun"},
    "environnement": {"lemma": "environnement", "en": "environment / surroundings", "bn": "পরিবেশ", "pos": "noun"},
    "envisager": {"lemma": "envisager", "en": "to consider", "bn": "বিবেচনা করা", "pos": "verb"},
    "envoyer": {"lemma": "envoyer", "en": "to send", "bn": "পাঠানো", "pos": "verb"},
    "envoie": {"lemma": "envoyer", "en": "sends", "bn": "পাঠায়", "pos": "verb"},
    "escalier": {"lemma": "escalier", "en": "staircase / stairs", "bn": "সিঁড়ি", "pos": "noun"},
    "escaliers": {"lemma": "escalier", "en": "stairs", "bn": "সিঁড়ি", "pos": "noun"},
    "espace": {"lemma": "espace", "en": "space / area / user dashboard", "bn": "জায়গা / ড্যাশবোর্ড", "pos": "noun"},
    "espèces": {"lemma": "espèce", "en": "cash (en espèces)", "bn": "নগদ টাকা", "pos": "noun"},
    "espoir": {"lemma": "espoir", "en": "hope", "bn": "আশা", "pos": "noun"},
    "essayer": {"lemma": "essayer", "en": "to try / test", "bn": "চেষ্টা করা / পরীক্ষা করা", "pos": "verb"},
    "est": {"lemma": "être", "en": "is", "bn": "হয় / আছে", "pos": "verb"},
    "sommes": {"lemma": "être", "en": "are (nous)", "bn": "হই / আছি", "pos": "verb"},
    "êtes": {"lemma": "être", "en": "are (vous)", "bn": "হন / আছেন", "pos": "verb"},
    "sont": {"lemma": "être", "en": "are (plural)", "bn": "হয় / আছেন", "pos": "verb"},
    "suis": {"lemma": "être", "en": "am (je suis)", "bn": "হই / আছি", "pos": "verb"},
    "étais": {"lemma": "être", "en": "was", "bn": "ছিলাম", "pos": "verb"},
    "était": {"lemma": "être", "en": "was", "bn": "ছিল", "pos": "verb"},
    "été": {"lemma": "être", "en": "been (past participle) / summer", "bn": "হয়েছে / গ্রীষ্ম", "pos": "verb"},
    "sera": {"lemma": "être", "en": "will be", "bn": "হবে", "pos": "verb"},
    "seront": {"lemma": "être", "en": "will be (plural)", "bn": "হবে", "pos": "verb"},
    "soyez": {"lemma": "être", "en": "be (subjunctive/imperative)", "bn": "হোন", "pos": "verb"},
    "explications": {"lemma": "explication", "en": "explanations", "bn": "ব্যাখ্যাসমূহ", "pos": "noun"},
    "explique": {"lemma": "expliquer", "en": "explains", "bn": "ব্যাখ্যা করে", "pos": "verb"},
    "expliquer": {"lemma": "expliquer", "en": "to explain", "bn": "ব্যাখ্যা করা", "pos": "verb"},
    "exposer": {"lemma": "exposer", "en": "to explain / lay out", "bn": "তুলে ধরা / উপস্থাপন করা", "pos": "verb"},
    "expose": {"lemma": "exposer", "en": "lays out / states", "bn": "তুলে ধরে", "pos": "verb"},
    "examiner": {"lemma": "examiner", "en": "to examine", "bn": "পরীক্ষা করা", "pos": "verb"},
    "examine": {"lemma": "examiner", "en": "examines / reviews", "bn": "পরীক্ষা করে", "pos": "verb"},
    "examiné": {"lemma": "examiner", "en": "reviewed / examined", "bn": "পর্যালোচনা করেছে", "pos": "verb"},
    "excellence": {"lemma": "excellence", "en": "excellence", "bn": "উৎকর্ষ", "pos": "noun"},
    "excellent": {"lemma": "excellent", "en": "excellent", "bn": "চমৎকার", "pos": "adjective"},
    "excellente": {"lemma": "excellent", "en": "excellent (feminine)", "bn": "চমৎকার", "pos": "adjective"},
    "extrêmement": {"lemma": "extrêmement", "en": "extremely", "bn": "অত্যন্ত / খুব", "pos": "adverb"},
    "exigences": {"lemma": "exigence", "en": "requirements", "bn": "শর্তাবলী / প্রয়োজনীয়তা", "pos": "noun"},
    "expérience": {"lemma": "expérience", "en": "experience", "bn": "অভিজ্ঞতা", "pos": "noun"},
    "exprimer": {"lemma": "exprimer", "en": "to express", "bn": "প্রকাশ করা", "pos": "verb"},
    "éboueurs": {"lemma": "éboueur", "en": "garbage collectors", "bn": "পরিচ্ছন্নতাকর্মী", "pos": "noun"},
    "écharpe": {"lemma": "écharpe", "en": "scarf", "bn": "স্কার্ফ / মাফলার", "pos": "noun"},
    "échange": {"lemma": "échange", "en": "exchange / discussion", "bn": "বিনিময় / আলোচনা", "pos": "noun"},
    "échanger": {"lemma": "échanger", "en": "to discuss / exchange", "bn": "আলোচনা করা", "pos": "verb"},
    "école": {"lemma": "école", "en": "school", "bn": "স্কুল", "pos": "noun"},
    "écran": {"lemma": "écran", "en": "screen / display", "bn": "পর্দা / স্ক্রিন", "pos": "noun"},
    "écrans": {"lemma": "écran", "en": "screens", "bn": "পর্দাগুলো", "pos": "noun"},
    "écrit": {"lemma": "écrire", "en": "writes / written", "bn": "লেখে / লিখিত", "pos": "verb"},
    "écrire": {"lemma": "écrire", "en": "to write", "bn": "লেখা", "pos": "verb"},
    "écoute": {"lemma": "écouter", "en": "listens / active listening", "bn": "শোনে / মনোযোগ দিয়ে শোনা", "pos": "verb"},
    "écouter": {"lemma": "écouter", "en": "to listen", "bn": "শোনা", "pos": "verb"},
    "éducation": {"lemma": "éducation", "en": "education", "bn": "শিক্ষা", "pos": "noun"},
    "également": {"lemma": "également", "en": "also / equally", "bn": "এছাড়াও", "pos": "adverb"},
    "élément": {"lemma": "élément", "en": "element", "bn": "উপাদান", "pos": "noun"},
    "équipé": {"lemma": "équiper", "en": "equipped", "bn": "সজ্জিত", "pos": "adjective"},
    "équipée": {"lemma": "équiper", "en": "equipped (feminine)", "bn": "সুসজ্জিত", "pos": "adjective"},
    "équivalence": {"lemma": "équivalence", "en": "equivalency", "bn": "সমমান / সমতাকরণ", "pos": "noun"},
    "étage": {"lemma": "étage", "en": "floor / storey", "bn": "তলা / ফ্লোর", "pos": "noun"},
    "état": {"lemma": "état", "en": "state / condition", "bn": "অবস্থা", "pos": "noun"},
    "étiquette": {"lemma": "étiquette", "en": "label / sticker", "bn": "লেবেল / স্টিকার", "pos": "noun"},
    "étranger": {"lemma": "étranger", "en": "foreign / abroad", "bn": "বিদেশি", "pos": "adjective"},
    "étrangère": {"lemma": "étranger", "en": "foreign (feminine)", "bn": "বিদেশি", "pos": "adjective"},
    "étudiant": {"lemma": "étudiant", "en": "student", "bn": "ছাত্র / শিক্ষার্থী", "pos": "noun"},
    "étudiants": {"lemma": "étudiant", "en": "students", "bn": "শিক্ষার্থীবৃন্দ", "pos": "noun"},
    "étudiante": {"lemma": "étudiant", "en": "student (female)", "bn": "ছাত্রী", "pos": "noun"},
    "étudie": {"lemma": "étudier", "en": "studies / reviews", "bn": "পড়ে / পর্যবেক্ষণ করে", "pos": "verb"},
    "études": {"lemma": "étude", "en": "studies / degree", "bn": "পড়াশোনা / উচ্চশিক্ষা", "pos": "noun"},

    # F
    "façon": {"lemma": "façon", "en": "way / manner", "bn": "উপায় / পদ্ধতি", "pos": "noun"},
    "facture": {"lemma": "facture", "en": "invoice / utility bill", "bn": "রসিদ / বিল", "pos": "noun"},
    "faim": {"lemma": "faim", "en": "hunger", "bn": "ক্ষুধা", "pos": "noun"},
    "faire": {"lemma": "faire", "en": "to do / make", "bn": "করা", "pos": "verb"},
    "faisons": {"lemma": "faire", "en": "make / do (nous)", "bn": "করি", "pos": "verb"},
    "fait": {"lemma": "faire", "en": "makes / does / fact", "bn": "করে / ঘটনা", "pos": "verb"},
    "faites": {"lemma": "faire", "en": "done / do (plural)", "bn": "করেন", "pos": "verb"},
    "font": {"lemma": "faire", "en": "do / make (plural)", "bn": "করে", "pos": "verb"},
    "ferait": {"lemma": "faire", "en": "would do / please (plaisir)", "bn": "করবে / পছন্দ হবে", "pos": "verb"},
    "famille": {"lemma": "famille", "en": "family", "bn": "পরিবার", "pos": "noun"},
    "fauteuil": {"lemma": "fauteuil", "en": "armchair", "bn": "আরামদায়ক চেয়ার", "pos": "noun"},
    "femme": {"lemma": "femme", "en": "woman / wife", "bn": "মহিলা / স্ত্রী", "pos": "noun"},
    "fenêtre": {"lemma": "fenêtre", "en": "window", "bn": "জানালা", "pos": "noun"},
    "ferme": {"lemma": "fermer", "en": "locks / closes", "bn": "বন্ধ করে", "pos": "verb"},
    "fermer": {"lemma": "fermer", "en": "to close / shut", "bn": "বন্ধ করা", "pos": "verb"},
    "feuille": {"lemma": "feuille", "en": "sheet (of paper) / roadmap", "bn": "কাগজ / রোডম্যাপ", "pos": "noun"},
    "feutre": {"lemma": "feutre", "en": "felt pen / marker", "bn": "মার্কার কলম", "pos": "noun"},
    "fiches": {"lemma": "fiche", "en": "sheets / slips (fiches de paie)", "bn": "স্লিপ / বিবরণী", "pos": "noun"},
    "fiévre": {"lemma": "fièvre", "en": "fever", "bn": "জ্বর", "pos": "noun"},
    "fièvre": {"lemma": "fièvre", "en": "fever", "bn": "জ্বর", "pos": "noun"},
    "fière": {"lemma": "fier", "en": "proud (feminine)", "bn": "গর্বিত", "pos": "adjective"},
    "fierté": {"lemma": "fierté", "en": "pride", "bn": "গর্ব / আত্মতৃপ্তি", "pos": "noun"},
    "fil": {"lemma": "fil", "en": "wire / thread", "bn": "তার", "pos": "noun"},
    "fin": {"lemma": "fin", "en": "end", "bn": "শেষ", "pos": "noun"},
    "finalement": {"lemma": "finalement", "en": "finally / eventually", "bn": "অবশেষে", "pos": "adverb"},
    "finaliser": {"lemma": "finaliser", "en": "to finalize", "bn": "চূড়ান্ত করা", "pos": "verb"},
    "financier": {"lemma": "financier", "en": "financial (masculine)", "bn": "আর্থিক", "pos": "adjective"},
    "financière": {"lemma": "financier", "en": "financial (feminine)", "bn": "আর্থিক", "pos": "adjective"},
    "financières": {"lemma": "financier", "en": "financial (plural)", "bn": "আর্থিক", "pos": "adjective"},
    "fixe": {"lemma": "fixer", "en": "sets / fixed", "bn": "নির্ধারিত / ল্যান্ডলাইন", "pos": "adjective"},
    "fixée": {"lemma": "fixer", "en": "scheduled / fixed (feminine)", "bn": "নির্ধারিত", "pos": "adjective"},
    "fonctionne": {"lemma": "fonctionner", "en": "works / operates", "bn": "কাজ করে / সচল থাকে", "pos": "verb"},
    "fonctionnement": {"lemma": "fonctionnement", "en": "operation / functioning", "bn": "কার্যক্ষমতা", "pos": "noun"},
    "forfait": {"lemma": "forfait", "en": "mobile plan / package", "bn": "মোবাইল প্যাকেজ", "pos": "noun"},
    "forfaits": {"lemma": "forfait", "en": "mobile plans", "bn": "মোবাইল প্যাকেজসমূহ", "pos": "noun"},
    "formateur": {"lemma": "formateur", "en": "trainer", "bn": "প্রশিক্ষক", "pos": "noun"},
    "formation": {"lemma": "formation", "en": "training course / studies", "bn": "প্রশিক্ষণ / কোর্স", "pos": "noun"},
    "formulaire": {"lemma": "formulaire", "en": "official form", "bn": "ফর্ম / আবেদনপত্র", "pos": "noun"},
    "formule": {"lemma": "formule", "en": "set deal / package", "bn": "প্যাকেজ / সেট মেনু", "pos": "noun"},
    "fort": {"lemma": "fort", "en": "strong", "bn": "শক্তিশালী", "pos": "adjective"},
    "forts": {"lemma": "fort", "en": "strong (plural)", "bn": "শক্তিশালী", "pos": "adjective"},
    "fournit": {"lemma": "fournir", "en": "supplies / provides", "bn": "সরবরাহ করে", "pos": "verb"},
    "frais": {"lemma": "frais", "en": "fresh / cool", "bn": "তাজা / ঠান্ডা", "pos": "adjective"},
    "frappe": {"lemma": "frapper", "en": "knocks", "bn": "কড়া নাড়ে", "pos": "verb"},
    "frapper": {"lemma": "frapper", "en": "to knock (on door)", "bn": "দরজায় কড়া নাড়া", "pos": "verb"},
    "frère": {"lemma": "frère", "en": "brother", "bn": "ভাই", "pos": "noun"},
    "froid": {"lemma": "froid", "en": "cold", "bn": "ঠান্ডা", "pos": "adjective"},
    "froide": {"lemma": "froid", "en": "cold (feminine)", "bn": "ঠান্ডা", "pos": "adjective"},
    "froides": {"lemma": "froid", "en": "cold (plural)", "bn": "ঠান্ডা", "pos": "adjective"},
    "frontal": {"lemma": "frontal", "en": "forehead (thermometer)", "bn": "কপালে ধরার (থার্মোমিটার)", "pos": "adjective"},
    "fruits": {"lemma": "fruit", "en": "fruits", "bn": "ফলমূল", "pos": "noun"},
    "fumant": {"lemma": "fumer", "en": "steaming hot", "bn": "ধোঁয়া ওঠা গরম", "pos": "adjective"},
    "félicite": {"lemma": "féliciter", "en": "compliments / congratulates", "bn": "প্রশংসা করে", "pos": "verb"},

    # G
    "galerie": {"lemma": "galerie", "en": "shopping mall / gallery", "bn": "মার্কেট / গ্যালারি", "pos": "noun"},
    "garant": {"lemma": "garant", "en": "rental guarantor", "bn": "জামিনদার / গ্যারান্টর", "pos": "noun"},
    "garde": {"lemma": "garde", "en": "duty (pharmacie de garde)", "bn": "ডিউটি / জরুরি সেবা", "pos": "noun"},
    "gare": {"lemma": "gare", "en": "train station", "bn": "রেলওয়ে স্টেশন", "pos": "noun"},
    "gauche": {"lemma": "gauche", "en": "left", "bn": "বাম", "pos": "noun"},
    "gazeuse": {"lemma": "gazeux", "en": "sparkling (water)", "bn": "গ্যাসযুক্ত", "pos": "adjective"},
    "gentillesse": {"lemma": "gentillesse", "en": "kindness", "bn": "সদয়তা / ভদ্রতা", "pos": "noun"},
    "geste": {"lemma": "geste", "en": "gesture / sign", "bn": "ইশারা / অঙ্গভঙ্গি", "pos": "noun"},
    "gigaoctets": {"lemma": "gigaoctet", "en": "gigabytes (GB)", "bn": "গিগাবাইট (জিবি)", "pos": "noun"},
    "glace": {"lemma": "glace", "en": "ice cream / mirror", "bn": "আইসক্রিম / বরফ", "pos": "noun"},
    "glaces": {"lemma": "glace", "en": "ice creams", "bn": "আইসক্রিম", "pos": "noun"},
    "glacé": {"lemma": "glacé", "en": "iced", "bn": "বরফশীতল", "pos": "adjective"},
    "gorge": {"lemma": "gorge", "en": "throat", "bn": "গলা", "pos": "noun"},
    "grand": {"lemma": "grand", "en": "large / big", "bn": "বড়", "pos": "adjective"},
    "grande": {"lemma": "grand", "en": "large (feminine)", "bn": "বড়", "pos": "adjective"},
    "grands": {"lemma": "grand", "en": "large (plural)", "bn": "বড়", "pos": "adjective"},
    "gratuitement": {"lemma": "gratuitement", "en": "free of charge", "bn": "বিনামূল্যে", "pos": "adverb"},
    "grave": {"lemma": "grave", "en": "serious / severe", "bn": "গুরুতর", "pos": "adjective"},
    "guichet": {"lemma": "guichet", "en": "counter / service window", "bn": "কাউন্টার / টিকিট জানালা", "pos": "noun"},
    "guérir": {"lemma": "guérir", "en": "to heal / recover", "bn": "সুস্থ হওয়া / রোগমুক্তি", "pos": "verb"},
    "gâteau": {"lemma": "gâteau", "en": "cake", "bn": "কেক", "pos": "noun"},

    # H & I & J
    "habiter": {"lemma": "habiter", "en": "to live / reside", "bn": "বাস করা", "pos": "verb"},
    "habite": {"lemma": "habiter", "en": "lives", "bn": "বাস করে", "pos": "verb"},
    "hall": {"lemma": "hall", "en": "entrance lobby / hall", "bn": "প্রবেশ লবি", "pos": "noun"},
    "haut": {"lemma": "haut", "en": "high / top", "bn": "উঁচু", "pos": "adjective"},
    "heure": {"lemma": "heure", "en": "hour / time", "bn": "ঘণ্টা / সময়", "pos": "noun"},
    "heures": {"lemma": "heure", "en": "hours / o'clock", "bn": "ঘণ্টা / টা", "pos": "noun"},
    "heureux": {"lemma": "heureux", "en": "happy / pleased", "bn": "খুশি / আনন্দিত", "pos": "adjective"},
    "hoche": {"lemma": "hocher", "en": "nods (head)", "bn": "মাথা নাড়ায়", "pos": "verb"},
    "homme": {"lemma": "homme", "en": "man", "bn": "পুরুষ / মানুষ", "pos": "noun"},
    "horloge": {"lemma": "horloge", "en": "clock", "bn": "ঘড়ি", "pos": "noun"},
    "hôtel": {"lemma": "hôtel", "en": "hotel", "bn": "হোটেল", "pos": "noun"},
    "hôtesse": {"lemma": "hôte", "en": "receptionist / hostess", "bn": "অভ্যর্থনাকারী", "pos": "noun"},
    "idée": {"lemma": "idée", "en": "idea", "bn": "ধারণা", "pos": "noun"},
    "idéal": {"lemma": "idéal", "en": "ideal", "bn": "আদর্শ", "pos": "adjective"},
    "idéale": {"lemma": "idéal", "en": "ideal (feminine)", "bn": "আদর্শ", "pos": "adjective"},
    "identifiant": {"lemma": "identifiant", "en": "user ID / login number", "bn": "ব্যবহারকারী নম্বর / আইডি", "pos": "noun"},
    "identifie": {"lemma": "identifier", "en": "identifies / detects", "bn": "চিহ্নিত করে", "pos": "verb"},
    "identité": {"lemma": "identité", "en": "identity", "bn": "পরিচয়", "pos": "noun"},
    "illimités": {"lemma": "illimité", "en": "unlimited", "bn": "সীমাহীন / আনলিমিটেড", "pos": "adjective"},
    "immeuble": {"lemma": "immeuble", "en": "apartment building", "bn": "বিল্ডিং / বহুতল ভবন", "pos": "noun"},
    "immédiatement": {"lemma": "immédiatement", "en": "immediately", "bn": "তাৎক্ষণিকভাবে", "pos": "adverb"},
    "immédiat": {"lemma": "immédiat", "en": "immediate", "bn": "তাৎক্ষণিক", "pos": "adjective"},
    "immense": {"lemma": "immense", "en": "immense / huge", "bn": "বিশাল / অগাধ", "pos": "adjective"},
    "immobilière": {"lemma": "immobilier", "en": "real estate (agency)", "bn": "রিয়েল এস্টেট / আবাসন", "pos": "adjective"},
    "immobilières": {"lemma": "immobilier", "en": "real estate (listings)", "bn": "আবাসন সংক্রান্ত", "pos": "adjective"},
    "immobilier": {"lemma": "immobilier", "en": "real estate agent", "bn": "রিয়েল এস্টেট এজেন্ট", "pos": "noun"},
    "impérativement": {"lemma": "impérativement", "en": "imperatively / urgently", "bn": "অবশ্যই / অত্যন্ত জরুরিভাবে", "pos": "adverb"},
    "impeccablement": {"lemma": "impeccablement", "en": "impeccably", "bn": "নিখুঁতভাবে", "pos": "adverb"},
    "important": {"lemma": "important", "en": "important", "bn": "গুরুত্বপূর্ণ", "pos": "adjective"},
    "imprime": {"lemma": "imprimer", "en": "prints", "bn": "প্রিন্ট করে", "pos": "verb"},
    "imprimé": {"lemma": "imprimer", "en": "printed", "bn": "মুদ্রিত / প্রিন্ট করা", "pos": "adjective"},
    "inclut": {"lemma": "inclure", "en": "includes", "bn": "অন্তর্ভুক্ত করে", "pos": "verb"},
    "indique": {"lemma": "indiquer", "en": "indicates / shows", "bn": "নির্দেশ করে", "pos": "verb"},
    "indispensable": {"lemma": "indispensable", "en": "indispensable / essential", "bn": "অপরিহার্য", "pos": "adjective"},
    "indispensables": {"lemma": "indispensable", "en": "indispensable (plural)", "bn": "অপরিহার্য", "pos": "adjective"},
    "indéterminée": {"lemma": "indéterminé", "en": "permanent (contract CDI)", "bn": "স্থায়ী (চাকরির চুক্তি)", "pos": "adjective"},
    "informaticien": {"lemma": "informaticien", "en": "IT professional / computer scientist", "bn": "কম্পিউটার বিশেষজ্ঞ / আইটি কর্মী", "pos": "noun"},
    "information": {"lemma": "information", "en": "information", "bn": "তথ্য", "pos": "noun"},
    "informations": {"lemma": "information", "en": "information / details", "bn": "তথ্যসমূহ", "pos": "noun"},
    "informatique": {"lemma": "informatique", "en": "IT / computing", "bn": "আইটি / কম্পিউটার বিজ্ঞান", "pos": "noun"},
    "infrastructures": {"lemma": "infrastructure", "en": "infrastructure / hardware systems", "bn": "অবকাঠামো / আইটি সিস্টেম", "pos": "noun"},
    "ingénierie": {"lemma": "ingénierie", "en": "engineering", "bn": "প্রকৌশল / ইঞ্জিনিয়ারিং", "pos": "noun"},
    "ingénieur": {"lemma": "ingénieur", "en": "engineer", "bn": "প্রকৌশলী / ইঞ্জিনিয়ার", "pos": "noun"},
    "ingénieurs": {"lemma": "ingénieur", "en": "engineers", "bn": "প্রকৌশলীবৃন্দ", "pos": "noun"},
    "inquiétez": {"lemma": "inquiéter", "en": "worry (ne vous inquiétez pas)", "bn": "চিন্তা করবেন না", "pos": "verb"},
    "insère": {"lemma": "insérer", "en": "inserts", "bn": "প্রবেশ করায় / ঢোকায়", "pos": "verb"},
    "inscription": {"lemma": "inscription", "en": "enrollment / registration", "bn": "ভর্তি / নিবন্ধন", "pos": "noun"},
    "inscriptions": {"lemma": "inscription", "en": "admissions", "bn": "ভর্তি কার্যক্রম", "pos": "noun"},
    "inscrire": {"lemma": "inscrire", "en": "to enroll / sign up", "bn": "ভর্তি হওয়া / নিবন্ধন করা", "pos": "verb"},
    "inscrit": {"lemma": "inscrire", "en": "enrolled / registered", "bn": "নিবন্ধিত করেছে", "pos": "verb"},
    "installe": {"lemma": "installer", "en": "settles in / installs", "bn": "বসে / ইনস্টল করে", "pos": "verb"},
    "installer": {"lemma": "installer", "en": "to install / deploy", "bn": "ইনস্টল করা", "pos": "verb"},
    "installé": {"lemma": "installer", "en": "settled in / installed", "bn": "বসবাস শুরু করেছে", "pos": "verb"},
    "instant": {"lemma": "instant", "en": "moment / instant", "bn": "মুহূর্ত", "pos": "noun"},
    "instants": {"lemma": "instant", "en": "moments", "bn": "মুহূর্তগুলো", "pos": "noun"},
    "instantanés": {"lemma": "instantané", "en": "instant (transfers)", "bn": "তাৎক্ষণিক", "pos": "adjective"},
    "instructions": {"lemma": "instruction", "en": "instructions / directions", "bn": "নির্দেশাবলী", "pos": "noun"},
    "intensif": {"lemma": "intensif", "en": "intensive", "bn": "নিবিড় / গভীর", "pos": "adjective"},
    "interactif": {"lemma": "interactif", "en": "interactive", "bn": "ইন্টারেক্টিভ", "pos": "adjective"},
    "interactive": {"lemma": "interactif", "en": "interactive (feminine)", "bn": "ইন্টারেক্টিভ", "pos": "adjective"},
    "interlocuteur": {"lemma": "interlocuteur", "en": "interviewer / conversational partner", "bn": "কথোপকথনকারী / কর্মকর্তা", "pos": "noun"},
    "international": {"lemma": "international", "en": "international", "bn": "আন্তর্জাতিক", "pos": "adjective"},
    "internationale": {"lemma": "international", "en": "international (feminine)", "bn": "আন্তর্জাতিক", "pos": "adjective"},
    "internet": {"lemma": "internet", "en": "internet", "bn": "ইন্টারনেট", "pos": "noun"},
    "intéressé": {"lemma": "intéresser", "en": "interested", "bn": "আগ্রহী", "pos": "adjective"},
    "intéressante": {"lemma": "intéressant", "en": "interesting / attractive", "bn": "আকর্ষণীয়", "pos": "adjective"},
    "intérêt": {"lemma": "intérêt", "en": "interest", "bn": "আগ্রহ", "pos": "noun"},
    "intérieure": {"lemma": "intérieur", "en": "inner / interior (courtyard)", "bn": "অভ্যন্তরীণ", "pos": "adjective"},
    "invite": {"lemma": "inviter", "en": "invites", "bn": "আমন্ত্রণ জানায়", "pos": "verb"},
    "jambe": {"lemma": "jambe", "en": "leg", "bn": "পা", "pos": "noun"},
    "jaune": {"lemma": "jaune", "en": "yellow", "bn": "হলুদ", "pos": "adjective"},
    "jaunes": {"lemma": "jaune", "en": "yellow (plural)", "bn": "হলুদ", "pos": "adjective"},
    "jeudi": {"lemma": "jeudi", "en": "Thursday", "bn": "বৃহস্পতিবার", "pos": "noun"},
    "joli": {"lemma": "joli", "en": "pretty / nice", "bn": "সুন্দর", "pos": "adjective"},
    "jolie": {"lemma": "joli", "en": "pretty (feminine)", "bn": "সুন্দর", "pos": "adjective"},
    "jouer": {"lemma": "jouer", "en": "to play", "bn": "খেলা", "pos": "verb"},
    "jour": {"lemma": "jour", "en": "day", "bn": "দিন", "pos": "noun"},
    "jours": {"lemma": "jour", "en": "days", "bn": "দিনগুলো", "pos": "noun"},
    "journal": {"lemma": "journal", "en": "newspaper", "bn": "সংবাদপত্র", "pos": "noun"},
    "journaux": {"lemma": "journal", "en": "newspapers", "bn": "সংবাদপত্রসমূহ", "pos": "noun"},
    "journée": {"lemma": "journée", "en": "day (duration)", "bn": "দিন", "pos": "noun"},
    "jus": {"lemma": "jus", "en": "juice", "bn": "রস / জুস", "pos": "noun"},
    "jusquau": {"lemma": "jusque", "en": "up to / until", "bn": "পর্যন্ত", "pos": "preposition"},
    "justificatif": {"lemma": "justificatif", "en": "supporting document / proof", "bn": "প্রমাণপত্র / প্রত্যয়ন", "pos": "noun"},
    "justificatifs": {"lemma": "justificatif", "en": "supporting documents", "bn": "প্রমাণপত্রসমূহ", "pos": "noun"},
    "laboratoire": {"lemma": "laboratoire", "en": "laboratory / computer lab", "bn": "ল্যাবরেটরি / ল্যাব", "pos": "noun"},
    "laisse": {"lemma": "laisser", "en": "leaves (behind)", "bn": "রেখে যায়", "pos": "verb"},
    "lait": {"lemma": "lait", "en": "milk", "bn": "দুধ", "pos": "noun"},
    "laitiers": {"lemma": "laitier", "en": "dairy (products)", "bn": "দুগ্ধজাত", "pos": "adjective"},
    "langue": {"lemma": "langue", "en": "language / tongue", "bn": "ভাষা", "pos": "noun"},
    "langues": {"lemma": "langue", "en": "languages", "bn": "ভাষাসমূহ", "pos": "noun"},
    "lecteur": {"lemma": "lecteur", "en": "scanner / reader", "bn": "স্ক্যানার / রিডার", "pos": "noun"},
    "lettre": {"lemma": "lettre", "en": "letter / cover letter", "bn": "চিঠি / আবেদনপত্র", "pos": "noun"},
    "lettres": {"lemma": "lettre", "en": "letters / mail", "bn": "চিঠিপত্র", "pos": "noun"},
    "licence": {"lemma": "licence", "en": "bachelor's degree (3-year)", "bn": "স্নাতক ডিগ্রি (লাইসেন্স)", "pos": "noun"},
    "lieu": {"lemma": "lieu", "en": "place / take place", "bn": "স্থান / অনুষ্ঠিত হওয়া", "pos": "noun"},
    "ligne": {"lemma": "ligne", "en": "line (metro / telephone / online)", "bn": "লাইন / সংযোগ", "pos": "noun"},
    "linux": {"lemma": "Linux", "en": "Linux operating system", "bn": "লিনাক্স অপারেটিং সিস্টেম", "pos": "noun"},
    "lire": {"lemma": "lire", "en": "to read", "bn": "পড়া", "pos": "verb"},
    "lit": {"lemma": "lire", "en": "reads / bed", "bn": "পড়ে / বিছানা", "pos": "verb"},
    "liste": {"lemma": "liste", "en": "list", "bn": "তালিকা", "pos": "noun"},
    "livraison": {"lemma": "livraison", "en": "delivery", "bn": "ডেলিভারি / পৌঁছানো", "pos": "noun"},
    "local": {"lemma": "local", "en": "local / storage room", "bn": "স্থানীয় / সাধারণ স্টোররুম", "pos": "noun"},
    "locaux": {"lemma": "local", "en": "premises / local (plural)", "bn": "কক্ষসমূহ / স্থানীয়", "pos": "noun"},
    "locataire": {"lemma": "locataire", "en": "tenant / renter", "bn": "ভাড়াটিয়া", "pos": "noun"},
    "location": {"lemma": "location", "en": "rental", "bn": "ভাড়া", "pos": "noun"},
    "logement": {"lemma": "logement", "en": "housing / accommodation", "bn": "বাসস্থান / থাকার ঘর", "pos": "noun"},
    "long": {"lemma": "long", "en": "long", "bn": "লম্বা", "pos": "adjective"},
    "longue": {"lemma": "long", "en": "long (feminine)", "bn": "দীর্ঘ / লম্বা", "pos": "adjective"},
    "louer": {"lemma": "louer", "en": "to rent", "bn": "ভাড়া নেওয়া / ভাড়া দেওয়া", "pos": "verb"},
    "loyer": {"lemma": "loyer", "en": "rent (monthly)", "bn": "মাসিক বাড়িভাড়া", "pos": "noun"},
    "loyers": {"lemma": "loyer", "en": "rents", "bn": "বাড়িভাড়াগুলো", "pos": "noun"},
    "lumière": {"lemma": "lumière", "en": "light", "bn": "আলো", "pos": "noun"},
    "lumineux": {"lemma": "lumineux", "en": "bright / luminous", "bn": "উজ্জ্বল / আলোকময়", "pos": "adjective"},
    "lumineuse": {"lemma": "lumineux", "en": "bright (feminine)", "bn": "উজ্জ্বল", "pos": "adjective"},
    "lundi": {"lemma": "lundi", "en": "Monday", "bn": "সোমবার", "pos": "noun"},
    "légumes": {"lemma": "légume", "en": "vegetables", "bn": "শাকসবজি", "pos": "noun"},
    "léger": {"lemma": "léger", "en": "light / carefree", "bn": "হালকা / ভারমুক্ত", "pos": "adjective"},
}

print(f"Loaded Lexicon D-L: {len(LEXICON_D_L)} entries.")
