# -*- coding: utf-8 -*-
import sys, re, json
sys.path.append('scripts')

from stories_definitions import STORIES_A1
from stories_definitions_a2 import STORIES_A2
from match_text_parser import tokenize_sentence

# Core Elision and Compound pieces
CORE_EXTRA = {
    "tariq": {"lemma": "Tariq", "en": "Tariq (first name)", "bn": "তারিক (নাম)", "pos": "noun"},
    "kabir": {"lemma": "Kabir", "en": "Kabir (first name)", "bn": "কবীর (নাম)", "pos": "noun"},
    "rahim": {"lemma": "Rahim", "en": "Rahim (first name)", "bn": "রহিম (নাম)", "pos": "noun"},
    "fahim": {"lemma": "Fahim", "en": "Fahim (first name)", "bn": "ফাহিম (নাম)", "pos": "noun"},
    "samir": {"lemma": "Samir", "en": "Samir (first name)", "bn": "সমীর (নাম)", "pos": "noun"},
    "pierre": {"lemma": "Pierre", "en": "Pierre (first name)", "bn": "পিয়ের (ফরাসি নাম)", "pos": "noun"},
    "laurent": {"lemma": "Laurent", "en": "Laurent (name)", "bn": "লরেন্ট (নাম)", "pos": "noun"},
    "bernard": {"lemma": "Bernard", "en": "Bernard (name)", "bn": "বার্নার্ড (নাম)", "pos": "noun"},
    "dupont": {"lemma": "Dupont", "en": "Dupont (surname)", "bn": "ডুপন্ট (পদবি)", "pos": "noun"},
    "martin": {"lemma": "Martin", "en": "Martin (surname)", "bn": "মার্টিন (পদবি)", "pos": "noun"},
    "vasseur": {"lemma": "Vasseur", "en": "Vasseur (surname)", "bn": "ভাসুর (পদবি)", "pos": "noun"},
    "leroux": {"lemma": "Leroux", "en": "Leroux (surname)", "bn": "লারু (পদবি)", "pos": "noun"},
    "thomas": {"lemma": "Thomas", "en": "Thomas (first name)", "bn": "টমাস (নাম)", "pos": "noun"},
    "paris": {"lemma": "Paris", "en": "Paris", "bn": "প্যারিস", "pos": "noun"},
    "france": {"lemma": "France", "en": "France", "bn": "ফ্রান্স", "pos": "noun"},
    "travail": {"lemma": "France Travail", "en": "France Travail (national employment agency)", "bn": "ফ্রান্স ত্রাভাই (কর্মসংস্থান সংস্থা)", "pos": "noun"},
    "châtelet": {"lemma": "Châtelet", "en": "Châtelet (metro station)", "bn": "শাতলে (মেট্রো স্টেশন)", "pos": "noun"},
    "clignancourt": {"lemma": "Clignancourt", "en": "Clignancourt (place in Paris)", "bn": "ক্লিনিয়াঁকুর", "pos": "noun"},

    # Elision components
    "d": {"lemma": "de", "en": "of / from (elision)", "bn": "এর / থেকে", "pos": "preposition"},
    "l": {"lemma": "le", "en": "the (elision)", "bn": "টি / টা", "pos": "article"},
    "s": {"lemma": "se", "en": "himself / herself (elision)", "bn": "নিজেকে", "pos": "pronoun"},
    "j": {"lemma": "je", "en": "I (elision)", "bn": "আমি", "pos": "pronoun"},
    "c": {"lemma": "ce", "en": "it / this (c'est)", "bn": "এটা / এই", "pos": "pronoun"},
    "qu": {"lemma": "que", "en": "that / what (elision)", "bn": "যা / কী", "pos": "pronoun"},
    "n": {"lemma": "ne", "en": "not (elision)", "bn": "না", "pos": "adverb"},
    "m": {"lemma": "me", "en": "me (elision)", "bn": "আমাকে", "pos": "pronoun"},
    "t": {"lemma": "te", "en": "you (elision)", "bn": "তোমাকে", "pos": "pronoun"},

    # Splitted hyphenated pieces
    "aujourd": {"lemma": "aujourd'hui", "en": "today", "bn": "আজ", "pos": "adverb"},
    "hui": {"lemma": "aujourd'hui", "en": "today (part of aujourd'hui)", "bn": "আজ", "pos": "adverb"},
    "aujourd'hui": {"lemma": "aujourd'hui", "en": "today", "bn": "আজ", "pos": "adverb"},
    "aujourdhui": {"lemma": "aujourd'hui", "en": "today", "bn": "আজ", "pos": "adverb"},
    "est-ce": {"lemma": "est-ce que", "en": "is it / (question marker)", "bn": "কী / নাকি", "pos": "expression"},
    "qu'est-ce": {"lemma": "qu'est-ce que", "en": "what is it", "bn": "কী", "pos": "expression"},
    "questce": {"lemma": "qu'est-ce que", "en": "what is it", "bn": "কী", "pos": "expression"},
    "petit-déjeuner": {"lemma": "petit-déjeuner", "en": "breakfast", "bn": "সকালের নাস্তা", "pos": "noun"},
    "petitdéjeuner": {"lemma": "petit-déjeuner", "en": "breakfast", "bn": "সকালের নাস্তা", "pos": "noun"},
    "s'il": {"lemma": "si", "en": "if he / please", "bn": "যদি / দয়া করে", "pos": "conjunction"},
    "sil": {"lemma": "si", "en": "if he", "bn": "যদি", "pos": "conjunction"},
    "plaît": {"lemma": "plaire", "en": "pleases (s'il vous plaît)", "bn": "পছন্দ হয় / দয়া করে", "pos": "verb"},
    "puis-je": {"lemma": "pouvoir", "en": "may I / can I", "bn": "আমি কি পারি", "pos": "verb"},
    "désirez-vous": {"lemma": "désirer", "en": "would you like", "bn": "আপনি কি চান", "pos": "verb"},
    "n'est-ce": {"lemma": "être", "en": "isn't it (n'est-ce pas)", "bn": "তাই না", "pos": "expression"},
    "n'hésitez": {"lemma": "hésiter", "en": "don't hesitate", "bn": "দ্বিধা করবেন না", "pos": "verb"},
    "avez-vous": {"lemma": "avoir", "en": "do you have", "bn": "আপনার কি আছে", "pos": "verb"},
    "comment": {"lemma": "comment", "en": "how / what", "bn": "কেমন / কীভাবে / কী", "pos": "adverb"},
    "nano": {"lemma": "nano", "en": "nano (SIM)", "bn": "ন্যানো", "pos": "adjective"},
    "nano-sim": {"lemma": "nano-SIM", "en": "nano-SIM card", "bn": "ন্যানো সিম", "pos": "noun"},
    "nanosim": {"lemma": "nano-SIM", "en": "nano-SIM card", "bn": "ন্যানো সিম", "pos": "noun"},
    "rendez-vous": {"lemma": "rendez-vous", "en": "appointment / meeting", "bn": "সাক্ষাৎ / অ্যাপয়েন্টমেন্ট", "pos": "noun"},
    "rendezvous": {"lemma": "rendez-vous", "en": "appointment", "bn": "সাক্ষাৎ", "pos": "noun"},
    "sous-préfecture": {"lemma": "sous-préfecture", "en": "sub-prefecture", "bn": "সাব-প্রিফেকচার", "pos": "noun"},
    "souspréfecture": {"lemma": "sous-préfecture", "en": "sub-prefecture", "bn": "সাব-প্রিফেকচার", "pos": "noun"},
    "après-midi": {"lemma": "après-midi", "en": "afternoon", "bn": "বিকাল / দুপুর", "pos": "noun"},
    "aprèsmidi": {"lemma": "après-midi", "en": "afternoon", "bn": "বিকাল", "pos": "noun"},
    "l'après-midi": {"lemma": "après-midi", "en": "in the afternoon", "bn": "বিকালে", "pos": "noun"},
    "lapresmidi": {"lemma": "après-midi", "en": "in the afternoon", "bn": "বিকালে", "pos": "noun"},
    "centre-ville": {"lemma": "centre-ville", "en": "city centre / downtown", "bn": "শহরের কেন্দ্রস্থল", "pos": "noun"},
    "centreville": {"lemma": "centre-ville", "en": "city centre", "bn": "শহরের কেন্দ্রস্থল", "pos": "noun"},
    "code-barres": {"lemma": "code-barres", "en": "barcode", "bn": "বারকোড", "pos": "noun"},
    "codebarres": {"lemma": "code-barres", "en": "barcode", "bn": "বারকোড", "pos": "noun"},
    "demi-écrémé": {"lemma": "demi-écrémé", "en": "semi-skimmed (milk)", "bn": "সেমি-স্কিমড (দুধ)", "pos": "adjective"},
    "demiécrémé": {"lemma": "demi-écrémé", "en": "semi-skimmed", "bn": "সেমি-স্কিমড", "pos": "adjective"},
    "asseyez-vous": {"lemma": "asseoir", "en": "take a seat / sit down", "bn": "বসুন", "pos": "verb"},
    "asseyezvous": {"lemma": "asseoir", "en": "take a seat", "bn": "বসুন", "pos": "verb"},
    "excusez-moi": {"lemma": "excuser", "en": "excuse me", "bn": "মাফ করবেন", "pos": "expression"},
    "excusezmoi": {"lemma": "excuser", "en": "excuse me", "bn": "মাফ করবেন", "pos": "expression"},
    "sous-sol": {"lemma": "sous-sol", "en": "basement", "bn": "বেজমেন্ট", "pos": "noun"},
    "soussol": {"lemma": "sous-sol", "en": "basement", "bn": "বেজমেন্ট", "pos": "noun"},
    "jusqu'au": {"lemma": "jusque", "en": "up to / until", "bn": "পর্যন্ত", "pos": "preposition"},
    "jusquau": {"lemma": "jusque", "en": "up to", "bn": "পর্যন্ত", "pos": "preposition"},
    "vingt-cinq": {"lemma": "vingt-cinq", "en": "twenty-five", "bn": "পঁচিশ", "pos": "adjective"},
    "vingtcinq": {"lemma": "vingt-cinq", "en": "twenty-five", "bn": "পঁচিশ", "pos": "adjective"},
    "quarante-huit": {"lemma": "quarante-huit", "en": "forty-eight", "bn": "আটচল্লিশ", "pos": "adjective"},
    "quarantehuit": {"lemma": "quarante-huit", "en": "forty-eight", "bn": "আটচল্লিশ", "pos": "adjective"},
    "parlez-moi": {"lemma": "parler", "en": "tell me", "bn": "আমাকে বলুন", "pos": "verb"},
    "parlezmoi": {"lemma": "parler", "en": "tell me", "bn": "আমাকে বলুন", "pos": "verb"},
    "réagissez-vous": {"lemma": "réagir", "en": "how do you react", "bn": "আপনি কীভাবে প্রতিক্রিয়া জানান", "pos": "verb"},
    "réagissezvous": {"lemma": "réagir", "en": "how do you react", "bn": "কীভাবে প্রতিক্রিয়া জানান", "pos": "verb"},
    "lorsqu'un": {"lemma": "lorsque", "en": "when a / when an", "bn": "যখন একজন", "pos": "conjunction"},
    "lorsquun": {"lemma": "lorsque", "en": "when a", "bn": "যখন একজন", "pos": "conjunction"},
    "demi-journées": {"lemma": "demi-journée", "en": "half-days", "bn": "অর্ধ-দিবস", "pos": "noun"},
    "demijournées": {"lemma": "demi-journée", "en": "half-days", "bn": "অর্ধ-দিবস", "pos": "noun"},
    "g": {"lemma": "gigaoctet", "en": "gigabyte / G (4G, 5G)", "bn": "জিবি / জি", "pos": "noun"},
    "gb": {"lemma": "gigaoctet", "en": "gigabyte (GB)", "bn": "গিগাবাইট", "pos": "noun"},
    "go": {"lemma": "gigaoctet", "en": "gigabytes (Go)", "bn": "গিগাবাইট", "pos": "noun"},
    "mo": {"lemma": "mégaoctet", "en": "megabyte (Mo)", "bn": "মেগাবাইট", "pos": "noun"},
}

print("Core extra loaded.")
